Repository aws/eks-anywhere-build-tooling, pull requests merged in 2021-11, with the labels that each got.

#131 Remove confusing unused file
  projects/aws/eks-anywhere-test/BASE_TAG_FILE
Labels: approved, lgtm, size/XS

#130 Adding rolloutCiliumPods to true
  projects/cilium/cilium/manifests/cilium-eksa.yaml
Labels: approved, lgtm, size/XS

#116 Helm Chart Build
  Common.mk
  build/lib/helm_build.sh
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere-test/helm/eks-anywhere-test/Chart.yaml
Labels: approved, lgtm, size/M

#132 eks-anywhere-test helm chart: Adds config and secret annotations
  projects/aws/eks-anywhere-test/helm/eks-anywhere-test/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#133 Common make - Clone URL should be region specific
  Common.mk
Labels: approved, lgtm, size/XS

#134 Fix helm push permissions
  build/lib/helm_build.sh
Labels: approved, lgtm, size/XS

#135 Make Clone URLs region specific
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
Labels: approved, lgtm, size/M

#136 Remove eks-anywhere-test yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test.yaml
Labels: approved, lgtm, size/M

#137 Fix attribution generation for Flux projects and CAPI
  build/update-attribution-files/make_attribution.sh
Labels: approved, lgtm, size/S

#138 Add patch to be able to configure the cert-manager version in clusterctl
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-ability-to-configure-the-cert-manager-version-in.patch
Labels: approved, lgtm, size/L

#69 Tag artifacts based on branch they are built from
  Common.mk
  build/lib/common.sh
  build/lib/upload_artifacts.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/cilium/cilium/Makefile
  projects/cilium/cilium/build/upload_artifacts.sh
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/upload_artifacts.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/upload_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/upload_artifacts.sh
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/build/upload_artifacts.sh
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/kubernetes/cloud-provider-vsphere/build/upload_artifacts.sh
Labels: approved, lgtm, size/L

#139 Fix artifacts upload script for projects
  projects/cilium/cilium/build/upload_artifacts.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/upload_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/upload_artifacts.sh
  projects/kubernetes-sigs/kind/build/upload_artifacts.sh
  projects/kubernetes-sigs/vsphere-csi-driver/build/upload_artifacts.sh
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/kubernetes/cloud-provider-vsphere/build/upload_artifacts.sh
Labels: approved, lgtm, size/S

#140 Updated the EKS-D versions to the latest ones
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#141 More fixup for uploading artifacts
  build/lib/upload_artifacts.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm, size/XS

#142 Create another version
  projects/aws/eks-anywhere-test/GIT_TAG
Labels: approved, lgtm, size/XS

#143 Update etcdadm-controller tag to v0.1.2
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/XS

#144 Install openssl in staging build release
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#145 Remove redundant yum package installation
  projects/cilium/cilium/build/create_manifests.sh
  projects/fluxcd/source-controller/build/install_deps.sh
  projects/kubernetes-sigs/image-builder/build/setup_bottlerocket.sh
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ova.yml
Labels: approved, lgtm, size/S

#147 Fix filepath for mounted SSH key secret
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#148 Install QEMU during build setup
  build/lib/setup.sh
  projects/kubernetes-sigs/kind/buildspec.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#151 Standardize patching, artifacts and binary targets
  Common.mk
  build/lib/simple_create_binaries.sh
  build/lib/update_checksum_docker.sh
  build/lib/version.sh
  docs/development/add-new-project.md
  projects/aws/eks-anywhere-test/Makefile
  projects/brancz/kube-rbac-proxy/CHECKSUMS
  projects/brancz/kube-rbac-proxy/Makefile
  projects/brancz/kube-rbac-proxy/build/create_binaries.sh
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/build/create_binaries.sh
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/build/create_binaries.sh
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/build/create_binaries.sh
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/build/create_binaries.sh
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/build/create_binaries.sh
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/build/create_binaries.sh
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/build/create_binaries.sh
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/cri-tools/build/create_binaries.sh
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/etcdadm/build/create_binaries.sh
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/build/create_binaries.sh
  projects/mrajashree/etcdadm-controller/Makefile
  projects/mrajashree/etcdadm-controller/build/create_binaries.sh
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/Makefile
  projects/plunder-app/kube-vip/build/create_binaries.sh
  projects/rancher/local-path-provisioner/CHECKSUMS
  projects/rancher/local-path-provisioner/Makefile
  projects/rancher/local-path-provisioner/build/create_binaries.sh
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/Makefile
  projects/replicatedhq/troubleshoot/build/create_binaries.sh
  projects/vmware/govmomi/Makefile
  projects/vmware/govmomi/build/create_binaries.sh
Labels: approved, lgtm, size/XXL

#153 cilium: convert to common.mk
  build/lib/create_release_checksums.sh
  projects/cilium/cilium/Makefile
  projects/cilium/cilium/build/create_manifests.sh
  projects/cilium/cilium/expected_artifacts
Labels: approved, lgtm, size/M

#154 capv: switch to common.mk
  projects/kubernetes-sigs/cluster-api-provider-vsphere/.gitignore
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_attribution.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_binaries.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_tarballs.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/upload_artifacts.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/docker/linux/Dockerfile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/expected_artifacts
Labels: approved, lgtm, size/L

#156 diag-image: switch to common.mk
  projects/aws/eks-anywhere/.gitignore
  projects/aws/eks-anywhere/Makefile
  projects/aws/eks-anywhere/build/fetch_binaries.sh
  projects/aws/eks-anywhere/docker/linux/Dockerfile
Labels: approved, lgtm, size/L

#157 vsphere-csi-driver: switch to common.mk
  projects/kubernetes-sigs/vsphere-csi-driver/.gitignore
  projects/kubernetes-sigs/vsphere-csi-driver/CHECKSUMS
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/build/create_attribution.sh
  projects/kubernetes-sigs/vsphere-csi-driver/build/create_tarballs.sh
  projects/kubernetes-sigs/vsphere-csi-driver/build/upload_artifacts.sh
  projects/kubernetes-sigs/vsphere-csi-driver/docker/linux/csi-driver/Dockerfile
  projects/kubernetes-sigs/vsphere-csi-driver/docker/linux/csi-syncer/Dockerfile
  projects/kubernetes-sigs/vsphere-csi-driver/expected_artifacts
Labels: approved, lgtm, size/L

#159 Copy top-level manifests folder when pushing to S3
  projects/cilium/cilium/build/create_manifests.sh
  projects/cilium/cilium/expected_artifacts
Labels: approved, size/XS

#158 cloud-provider-vsphere: convert to common.mk and introduce release br…
  Common.mk
  Makefile
  build/lib/run_target_docker.sh
  build/lib/simple_create_tarballs.sh
  build/lib/update_checksum_docker.sh
  build/lib/update_checksums.sh
  build/lib/validate_checksums.sh
  projects/kubernetes/cloud-provider-vsphere/.gitignore
  projects/kubernetes/cloud-provider-vsphere/1-18/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-18/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-18/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-19/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-19/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-19/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-20/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-21/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/kubernetes/cloud-provider-vsphere/build/create_attribution.sh
  projects/kubernetes/cloud-provider-vsphere/build/create_binaries.sh
  projects/kubernetes/cloud-provider-vsphere/build/create_tarballs.sh
  projects/kubernetes/cloud-provider-vsphere/build/upload_artifacts.sh
  projects/kubernetes/cloud-provider-vsphere/docker/linux/Dockerfile
  projects/kubernetes/cloud-provider-vsphere/expected_artifacts
Labels: approved, lgtm, size/XXL

#160 Make buildspecs consistent, add artifacts upload target to filter
  Common.mk
  projects/fluxcd/helm-controller/buildspec.yml
  projects/fluxcd/kustomize-controller/buildspec.yml
  projects/fluxcd/notification-controller/buildspec.yml
  projects/fluxcd/source-controller/buildspec.yml
  projects/jetstack/cert-manager/buildspec.yml
  projects/replicatedhq/troubleshoot/buildspec.yml
Labels: approved, lgtm, size/M

#161 Override image component for diagnostic collector
  projects/aws/eks-anywhere/Makefile
Labels: approved, lgtm, size/XS

#164 Build S3 artifacts in release make target
  Common.mk
Labels: approved, lgtm, size/XS

#165 Add target to upload source controller artifacts
  projects/fluxcd/source-controller/Makefile
Labels: approved, lgtm, size/XS

#166 Add upload artifacts script for source controller project
  projects/fluxcd/source-controller/build/upload_artifacts.sh
Labels: approved, lgtm, size/M

#162 bootlerocket-bootstrap: use common.mk
  Common.mk
  Makefile
  build/lib/common.sh
  build/lib/update_checksums.sh
  projects/aws/bottlerocket-bootstrap/.gitignore
  projects/aws/bottlerocket-bootstrap/ATTRIBUTION.txt
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/LICENSE
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/README.md
  projects/aws/bottlerocket-bootstrap/build/fetch_binaries.sh
  projects/aws/bottlerocket-bootstrap/docker/linux/Dockerfile
  projects/aws/bottlerocket-bootstrap/scripts/kubeadm-controlplane-init
  projects/aws/bottlerocket-bootstrap/scripts/kubeadm-controlplane-join
  projects/aws/bottlerocket-bootstrap/scripts/kubeadm-the-hard-way
  projects/aws/bottlerocket-bootstrap/scripts/kubeadm-worker-join
Labels: approved, lgtm, size/XXL

#167 Override image component for Bottlerocket bootstrap image
  projects/aws/bottlerocket-bootstrap/Makefile
Labels: approved, lgtm, size/XS

#168 image-builder: improve ova built stability
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/config/additional_components.json.tmpl
  projects/kubernetes-sigs/image-builder/packer/config/validate_goss_inline_vars.json.tmpl
  projects/kubernetes-sigs/image-builder/patches/0007-additional-eks-specific-goss-validations.patch
Labels: approved, lgtm, size/S

#169 source-controller: switch to common.mk
  Common.mk
  build/lib/common.sh
  build/lib/gather_non_golang_licenses.sh
  build/lib/simple_create_binaries.sh
  build/lib/validate_artifacts.sh
  build/lib/validate_checksums.sh
  projects/fluxcd/source-controller/.gitignore
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/build/Dockerfile.deps
  projects/fluxcd/source-controller/build/create_attribution.sh
  projects/fluxcd/source-controller/build/create_binaries.sh
  projects/fluxcd/source-controller/build/create_tarballs.sh
  projects/fluxcd/source-controller/docker/build/Dockerfile
  projects/fluxcd/source-controller/docker/linux/Dockerfile
  projects/fluxcd/source-controller/expected_artifacts
Labels: approved, lgtm, size/L

#170 Add version info to generated list, update tags in README
  UPSTREAM_PROJECTS.yaml
  build/lib/generate_projects_list.sh
  docs/development/add-new-project.md
  hack/boilerplate.yq.txt
  projects/mrajashree/etcdadm-bootstrap-provider/README.md
  projects/mrajashree/etcdadm-controller/README.md
Labels: approved, lgtm, size/M

#176 Enable packer logs during OVA build
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#177 Force-delete existing VMs of same name during OVA build
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#178 Revert "image-builder: improve ova built stability (#168)"
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/config/additional_components.json.tmpl
  projects/kubernetes-sigs/image-builder/packer/config/validate_goss_inline_vars.json.tmpl
  projects/kubernetes-sigs/image-builder/patches/0007-additional-eks-specific-goss-validations.patch
Labels: approved, lgtm, size/S

#163 kind: switch to common.mk
  Makefile
  build/lib/eksd_releases.sh
  build/lib/run_target_docker.sh
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
  projects/kubernetes-sigs/kind/build/build-kind-base-image.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/build-kindnetd-image.sh
  projects/kubernetes-sigs/kind/build/create_attribution.sh
  projects/kubernetes-sigs/kind/build/create_binaries.sh
  projects/kubernetes-sigs/kind/build/create_tarballs.sh
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/build/upload_artifacts.sh
  projects/kubernetes-sigs/kind/buildspec.yml
  projects/kubernetes-sigs/kind/expected_artifacts
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/download-images.sh
  projects/kubernetes-sigs/kind/images/kindnetd/Dockerfile
  projects/kubernetes-sigs/kind/images/node/Dockerfile
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
Labels: approved, lgtm, size/XXL

#179 Run local registry container in detached mode
  projects/kubernetes-sigs/kind/buildspec.yml
Labels: approved, lgtm, size/XS

#180 Fix tagging for kind node image dependencies
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/buildspec.yml
Labels: approved, lgtm, size/XS

#171 flux: update to latest versions
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/patches/0001-Replace-promptui-mod-to-mitigate-LGPL-dependency.patch
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/.gitignore
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/kustomize-controller/build/fetch_binaries.sh
  projects/fluxcd/kustomize-controller/docker/linux/Dockerfile
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/README.md
Labels: approved, lgtm, size/XXL

#183 kind: fix image taging and tarball directory
  Common.mk
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
Labels: approved, size/M

#182 attribution: no need to build binaries just need go mod download
  Common.mk
  Makefile
  build/lib/go_mod_download.sh
  build/lib/simple_create_binaries.sh
  build/update-attribution-files/make_attribution.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/cilium/cilium/Makefile
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/docker/build/Dockerfile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/replicatedhq/troubleshoot/Makefile
Labels: approved, lgtm, size/L

#185 Fix replacement of embedded images in kind node image
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/S

#186 kind: use proper etcdadm arch binary
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/S

#184 fix attribution target for the typical ATTRIBUTION.txt targets
  Common.mk
Labels: approved, lgtm, size/XS

#187 eks-a-tools: switch to common.mk
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/README.md
  projects/aws/eks-anywhere-build-tooling/build/fetch_binaries.sh
  projects/aws/eks-anywhere-build-tooling/docker/linux/Dockerfile
Labels: approved, lgtm, size/L

#190 cli-tools: fix image component
  projects/aws/eks-anywhere-build-tooling/Makefile
Labels: approved, lgtm, size/XS

#189 kind: improve base image crictl hash check
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
Labels: approved, lgtm, size/S

#191 kind: fix embedded arm images
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm, size/S

#193 etcadm: fix pull arm64 tar
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/patches/0010-Support-linux-other-arch.patch
Labels: approved, lgtm, size/M

#192 we only need s3 artifacts for a few projects
  Common.mk
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/brancz/kube-rbac-proxy/Makefile
  projects/brancz/kube-rbac-proxy/buildspec.yml
  projects/brancz/kube-rbac-proxy/expected_artifacts
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/buildspec.yml
  projects/fluxcd/helm-controller/expected_artifacts
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/buildspec.yml
  projects/fluxcd/kustomize-controller/expected_artifacts
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/buildspec.yml
  projects/fluxcd/notification-controller/expected_artifacts
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/buildspec.yml
  projects/fluxcd/source-controller/expected_artifacts
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/buildspec.yml
  projects/jetstack/cert-manager/expected_artifacts
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/expected_artifacts
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/build/create_binaries.sh
  projects/kubernetes-sigs/vsphere-csi-driver/buildspec.yml
  projects/kubernetes-sigs/vsphere-csi-driver/expected_artifacts
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/kubernetes/cloud-provider-vsphere/buildspec.yml
  projects/kubernetes/cloud-provider-vsphere/expected_artifacts
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/buildspec.yml
  projects/mrajashree/etcdadm-bootstrap-provider/expected_artifacts
  projects/mrajashree/etcdadm-controller/Makefile
  projects/mrajashree/etcdadm-controller/buildspec.yml
  projects/mrajashree/etcdadm-controller/expected_artifacts
  projects/plunder-app/kube-vip/Makefile
  projects/plunder-app/kube-vip/buildspec.yml
  projects/plunder-app/kube-vip/expected_artifacts
  projects/rancher/local-path-provisioner/Makefile
  projects/rancher/local-path-provisioner/buildspec.yml
  projects/rancher/local-path-provisioner/expected_artifacts
Labels: approved, lgtm, size/L

#194 kind: arm64 support for etcd when run with etcdadm
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/XS

#195 fetch-binaries: move to common.mk and update projects
  Common.mk
  build/lib/fetch_binaries.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/build/fetch_binaries.sh
  projects/aws/bottlerocket-bootstrap/docker/linux/Dockerfile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/build/fetch_binaries.sh
  projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh
  projects/aws/eks-anywhere-build-tooling/docker/linux/Dockerfile
  projects/aws/eks-anywhere/.gitignore
  projects/aws/eks-anywhere/Makefile
  projects/aws/eks-anywhere/build/fetch_binaries.sh
  projects/aws/eks-anywhere/docker/linux/Dockerfile
  projects/kubernetes-sigs/cluster-api/.gitignore
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/build/fetch_binaries.sh
  projects/kubernetes-sigs/cluster-api/docker/linux/cluster-api-docker-controller/Dockerfile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/organize_binaries.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
  projects/kubernetes-sigs/kind/images/node/files/etc/systemd/system/etcd.service.d/env.conf
Labels: approved, lgtm, size/XL

#196 buildkit: enable inline caching in latest image
  Common.mk
Labels: approved, lgtm, size/XS

#188 Revert "Revert "image-builder: improve ova built stability (#168)" (#…
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/config/additional_components.json.tmpl
  projects/kubernetes-sigs/image-builder/packer/config/validate_goss_inline_vars.json.tmpl
  projects/kubernetes-sigs/image-builder/patches/0007-additional-eks-specific-goss-validations.patch
Labels: approved, lgtm, size/S

#197 move adding users/groups to container image to common
  Common.mk
  build/lib/docker/linux/useradd/Dockerfile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/docker/linux/Dockerfile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/docker/linux/Dockerfile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/docker/linux/Dockerfile
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/docker/linux/Dockerfile
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/docker/linux/cert-manager-acmesolver/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-cainjector/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-controller/Dockerfile
Labels: approved, lgtm, size/L

#199 kindnetd: extract manifest for use in capd cluster
  build/lib/validate_artifacts.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/expected_artifacts
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/M

#200 kindnetd: fix manifest targets and artifacts
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/expected_artifacts
Labels: approved, lgtm, size/XS

#202 cli-tools: add sleep binary for reusing the container
  projects/aws/eks-anywhere-build-tooling/docker/linux/Dockerfile
Labels: approved, lgtm, size/S

#201 only export image cache when pushing images
  Common.mk
  projects/kubernetes-sigs/kind/Makefile
Labels: approved, lgtm, size/XS

#204 update checksums in attribution periodic
  Common.mk
  build/update-attribution-files/create_pr.sh
  build/update-attribution-files/make_attribution.sh
Labels: approved, lgtm, size/L

#207 small changes to common scripts to better match eks-distro
  Common.mk
  build/lib/buildkit.sh
  build/lib/update_checksum_docker.sh
  build/lib/validate_artifacts.sh
  build/update-attribution-files/create_pr.sh
  docs/development/add-new-project.md
Labels: approved, lgtm, size/M

#203 remove release-upload and use release in buildspecs
  Common.mk
  Makefile
  docs/development/building-locally.md
  projects/cilium/cilium/buildspec.yml
  projects/fluxcd/flux2/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-aws/buildspec.yml
  projects/kubernetes-sigs/cluster-api/buildspec.yml
  projects/kubernetes-sigs/cri-tools/buildspec.yml
  projects/kubernetes-sigs/etcdadm/buildspec.yml
Labels: approved, lgtm, size/M

#210 create-pr: handle dry-run with multiple changes
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#205 image-builder: switch to use common.mk and remove 1-18 and 1-19
  EKSD_LATEST_RELEASES
  Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_bottlerocket.sh
  projects/kubernetes-sigs/image-builder/build/setup_image_builder.sh
  projects/kubernetes-sigs/image-builder/build/upload_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-18-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-18-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-19-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-19-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ova.yml
Labels: approved, lgtm, size/L

#214 fix image-builder and kind
  EKSD_LATEST_RELEASES
  projects/kubernetes-sigs/kind/buildspec.yml
Labels: approved, lgtm, size/S

#215 Run artifacts upload in dry-run mode outside of Codebuild
  Common.mk
  build/lib/common.sh
  build/lib/upload_artifacts.sh
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/M

#217 image-builder: fix builds and clean up artifact uploads
  Common.mk
  build/lib/create_release_checksums.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/expected_artifacts
Labels: approved, lgtm, size/L

#218 Remove unnecessary script invocation
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS
