Repository aws/eks-anywhere-build-tooling, pull requests merged in 2021-12, with the labels that each got.

#219 Add packer log to list of expected artifacts
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/expected_artifacts
Labels: approved, lgtm, size/XS

#213 Update cert-manager tag to v1.5.3
  UPSTREAM_PROJECTS.yaml
  projects/jetstack/cert-manager/CHECKSUMS
  projects/jetstack/cert-manager/GIT_TAG
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/README.md
  projects/jetstack/cert-manager/patches/0001-Merge-pull-request-3877-from-irbekrm-move_crypto_for.patch
Labels: approved, lgtm, size/XL

#216 Update capv to v1.0.1
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Adding-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/M

#221 Mark CAPV as producing S3 artifacts
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/expected_artifacts
Labels: approved, lgtm, size/S

#223 Add support for cipher suites in etcdadm
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/patches/0011-Add-support-for-cipher-suites.patch
Labels: approved, lgtm, size/L

#225 Capv v1beta1
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Adding-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/M

#224 Revert "Update capv to v1.0.1"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Adding-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/M

#222 Update etcdadm provider tags to use v1beta1
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/S

#229 Add v1beta1 contract for etcdadm providers
  projects/mrajashree/etcdadm-bootstrap-provider/manifests/metadata.yaml
  projects/mrajashree/etcdadm-controller/manifests/metadata.yaml
Labels: approved, lgtm, size/S

#230 CAPT controller image and artifacts build
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/.gitignore
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/build/create_manifests.sh
  projects/tinkerbell/cluster-api-provider-tinkerbell/buildspec.yml
  projects/tinkerbell/cluster-api-provider-tinkerbell/docker/linux/Dockerfile
  projects/tinkerbell/cluster-api-provider-tinkerbell/expected_artifacts
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-PBNJ-integration-with-CAPT.patch
Labels: approved, lgtm, size/XXL

#150 Add pvc to chart
  projects/aws/eks-anywhere-test/conf/entrypoint.sh
  projects/aws/eks-anywhere-test/conf/index.template
  projects/aws/eks-anywhere-test/helm/eks-anywhere-test/templates/deployment.yaml
  projects/aws/eks-anywhere-test/helm/eks-anywhere-test/templates/pvc.yaml
Labels: approved, lgtm, size/M

#232 eks-anywhere-test: cleanup attribution handling for helm chart
  Common.mk
  build/lib/helm_build.sh
Labels: approved, lgtm, size/XS

#208 more sync changes from eks-distro
  Common.mk
  build/lib/go_mod_download.sh
  build/lib/validate_artifacts.sh
  docs/development/add-new-project.md
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/brancz/kube-rbac-proxy/Makefile
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/jetstack/cert-manager/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-controller/Makefile
  projects/plunder-app/kube-vip/Makefile
  projects/rancher/local-path-provisioner/Makefile
  projects/replicatedhq/troubleshoot/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/vmware/govmomi/Makefile
Labels: approved, lgtm, size/L

#233 Add etcdadm controller and bootstrapper changes for cipher suite support
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/S

#235 Mark etcdadm bootstrap provider and controller as producing S3 artifacts
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/expected_artifacts
  projects/mrajashree/etcdadm-controller/Makefile
  projects/mrajashree/etcdadm-controller/expected_artifacts
Labels: approved, lgtm, size/M

#236 Mark CAPV, etcdadm bootstrap provider and controller as producing S3 artifacts
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/expected_artifacts
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/build/create_manifests.sh
  projects/mrajashree/etcdadm-bootstrap-provider/expected_artifacts
  projects/mrajashree/etcdadm-controller/Makefile
  projects/mrajashree/etcdadm-controller/build/create_manifests.sh
  projects/mrajashree/etcdadm-controller/expected_artifacts
Labels: approved, lgtm, size/M

#238 Update etcdadm provider tags
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/XS

#240 fetch-binaries: use latest tag when deciding s3 folder instead of jus…
  Common.mk
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
Labels: approved, lgtm, size/M

#242 Fix OVA S3 upload destinations
  Common.mk
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
Labels: approved, lgtm, size/S

#243 Automated cherry pick of #240: fetch-binaries: use latest tag when deciding s3 folder
  Common.mk
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
Labels: approved, lgtm, size/M

#244 Remove trailing parenthesis in script
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/XS

#245 Remove trailing parenthesis in script
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/XS

#246 Bump CAPV to v1.0.1
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Adding-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/M

#241 Adding hegel project to build tooling
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hegel/.gitignore
  projects/tinkerbell/hegel/ATTRIBUTION.txt
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/hegel/STRPTIME_LICENSE.txt
  projects/tinkerbell/hegel/buildspec.yml
  projects/tinkerbell/hegel/docker/linux/Dockerfile
Labels: approved, lgtm, size/XL

#247 source-controller: fix cgo builder image to be builder-base
  Common.mk
Labels: approved, lgtm, size/XS

#248 etcdadm: fix version by setting proper ldflags
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/etcdadm/README.md
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/S

#250 Add user to cert-manager webhook container image
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/docker/linux/cert-manager-webhook/Dockerfile
Labels: approved, lgtm, size/XS

#252 fix latest tag for other branches
  Common.mk
Labels: approved, lgtm, size/XS

#254 fix create_pr for attribution on release branches
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#255 Update clusterctl ldflags to match upstream changes
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/Makefile
Labels: approved, lgtm, size/S

#256 Update base image for capd
  projects/kubernetes-sigs/cluster-api/Makefile
Labels: approved, lgtm, size/XS

#257 fix kind node image latest and release branch cleanup
  Common.mk
  docs/development/cherry-picks.md
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
Labels: approved, lgtm, size/S

#253 add generated help to all projects
  Common.mk
  Makefile
  build/lib/generate_help_body.sh
  build/update-attribution-files/make_attribution.sh
  projects/aws/bottlerocket-bootstrap/Help.mk
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-anywhere-build-tooling/Help.mk
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-test/Help.mk
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere/Help.mk
  projects/aws/eks-anywhere/Makefile
  projects/brancz/kube-rbac-proxy/Help.mk
  projects/brancz/kube-rbac-proxy/Makefile
  projects/fluxcd/flux2/Help.mk
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Help.mk
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Help.mk
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Help.mk
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Help.mk
  projects/fluxcd/source-controller/Makefile
  projects/jetstack/cert-manager/Help.mk
  projects/jetstack/cert-manager/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Help.mk
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cri-tools/Help.mk
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/etcdadm/Help.mk
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/kind/Help.mk
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/Help.mk
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes/cloud-provider-vsphere/Help.mk
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/Help.mk
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-controller/Help.mk
  projects/mrajashree/etcdadm-controller/Makefile
  projects/plunder-app/kube-vip/Help.mk
  projects/plunder-app/kube-vip/Makefile
  projects/rancher/local-path-provisioner/Help.mk
  projects/rancher/local-path-provisioner/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Help.mk
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hegel/Help.mk
  projects/tinkerbell/hegel/Makefile
  projects/vmware/govmomi/Help.mk
  projects/vmware/govmomi/Makefile
Labels: approved, lgtm, size/XXL

#258 Adding cloudflare/cfssl project to build tooling
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/cloudflare/cfssl/.gitignore
  projects/cloudflare/cfssl/ATTRIBUTION.txt
  projects/cloudflare/cfssl/CHECKSUMS
  projects/cloudflare/cfssl/GIT_TAG
  projects/cloudflare/cfssl/Makefile
  projects/cloudflare/cfssl/README.md
  projects/cloudflare/cfssl/buildspec.yml
  projects/cloudflare/cfssl/docker/linux/Dockerfile
  projects/cloudflare/cfssl/expected_artifacts
Labels: approved, lgtm, size/XXL

#249 Add jonahjon to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#260 Updatin checksums for projects after go version bump
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/source-controller/CHECKSUMS
  projects/jetstack/cert-manager/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/vsphere-csi-driver/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-20/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-21/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/hegel/CHECKSUMS
Labels: approved, lgtm, size/M

#259 Tink build tooling
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  projects/tinkerbell/tink/.gitignore
  projects/tinkerbell/tink/ATTRIBUTION.txt
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/buildspec.yml
  projects/tinkerbell/tink/docker/linux/tink-cli/Dockerfile
  projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
  projects/tinkerbell/tink/docker/linux/tink-worker/Dockerfile
  projects/tinkerbell/tink/patches/0001-Adding-build-comment-for-go1.16-go-licenses-compatab.patch
Labels: approved, lgtm, size/XXL

#261 attribution: fix periodic and add support for release-branch periodic
  Common.mk
  build/lib/install_go_versions.sh
  build/update-attribution-files/create_pr.sh
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/S

#266 Update etcdadm providers to include cipher field in v1beta1
  projects/mrajashree/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-controller/ATTRIBUTION.txt
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/XXL

#269 Update attributions - release 0.6
  Common.mk
  build/lib/install_go_versions.sh
  build/update-attribution-files/create_pr.sh
  projects/aws/bottlerocket-bootstrap/ATTRIBUTION.txt
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/jetstack/cert-manager/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/etcdadm/ATTRIBUTION.txt
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/vsphere-csi-driver/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-20/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-21/ATTRIBUTION.txt
  projects/mrajashree/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/mrajashree/etcdadm-controller/ATTRIBUTION.txt
  projects/plunder-app/kube-vip/ATTRIBUTION.txt
Labels: approved, size/M

#270 [PR BOT] Update CHECKSUMS files
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/source-controller/CHECKSUMS
  projects/jetstack/cert-manager/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/vsphere-csi-driver/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-20/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-21/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/plunder-app/kube-vip/CHECKSUMS
Labels: approved, lgtm, size/M

#271 Add vi swp file to gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#237 Cert manager helm chart
  Common.mk
  build/lib/helm_build.sh
  build/lib/helm_push.sh
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere-test/eks-anywhere-test/.helmignore
  projects/aws/eks-anywhere-test/eks-anywhere-test/Chart.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/_helpers.tpl
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/config.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/deployment.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/pvc.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/secret.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/service.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/tests/test-connection.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/values.yaml
  projects/aws/eks-anywhere-test/helm/files.txt
  projects/aws/eks-anywhere-test/helm/sedfile.template
  projects/jetstack/cert-manager/.gitignore
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/README.md
  projects/jetstack/cert-manager/helm/files.txt
  projects/jetstack/cert-manager/helm/patches/0001-Minor-clean-up-to-helm-chart.patch
  projects/jetstack/cert-manager/helm/patches/0002-Add-registry-to-helm-values.yaml.patch
  projects/jetstack/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/L

#281 Adding a patch for CAPT template actions
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0002-Modifying-workflow-action-to-image2disk.patch
Labels: approved, lgtm, size/S

#283 helm: new project build for helm cli
  projects/helm/helm/.gitignore
  projects/helm/helm/ATTRIBUTION.txt
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/GIT_TAG
  projects/helm/helm/Makefile
  projects/helm/helm/expected_artifacts
Labels: approved, lgtm, size/XXL

#288 bump eks-d release numbers
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#290 helm: add buildspec
  projects/helm/helm/buildspec.yml
Labels: approved, lgtm, size/S

#286 licenses: no need to keep code
  build/lib/common.sh
Labels: approved, lgtm, size/XS

#289 Automated cherry pick of #288: bump eks-d release numbers
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#292 Bump kube versions in EKS-D releases list
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#291 Bump kube versions in EKS-D releases list
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#294 Automated cherry pick of #262: Update base image tag file(s)
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_CSI_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
Labels: approved, lgtm, size/XS

#284 cli-tools: add helm cli to cli tools image
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh
Labels: approved, lgtm, size/XS

#293 Fix image tagging for bottlerocket bootstrap image
  Common.mk
Labels: approved, lgtm, size/XS

#296 Fix image tagging for release-branch specific projects
  Common.mk
Labels: approved, lgtm, size/XS

#295 add help update to periodic and cleanup helm help
  Common.mk
  Makefile
  build/lib/generate_help_body.sh
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/M

#298 capi: remove coredns migration patch
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-update-coredns-corefile-migration-to-support-1.8.3.patch
Labels: approved, lgtm, size/M

#297 Automated cherry pick of #286: licenses: no need to keep code
  build/lib/common.sh
Labels: approved, size/XS

#299 Automated cherry pick of #298: capi: remove coredns migration patch
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-update-coredns-corefile-migration-to-support-1.8.3.patch
Labels: approved, lgtm, size/M

#300 fix help generation on builder base
  Makefile
  build/lib/generate_help_body.sh
  build/update-attribution-files/make_attribution.sh
Labels: approved, lgtm, size/S

#302 avoid make output in generated help
  build/lib/generate_help_body.sh
Labels: approved, size/XS

#282 Flux helm
  Common.mk
  build/lib/helm_build.sh
  build/lib/helm_push.sh
  build/lib/image_shasum.sh
  projects/fluxcd/flux2/.gitignore
  projects/fluxcd/flux2/HELM_GIT_TAG
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/docker/linux/Dockerfile
  projects/fluxcd/flux2/helm/files.txt
  projects/fluxcd/flux2/helm/patches/0001-Disable-image-automation.patch
  projects/fluxcd/flux2/helm/patches/0002-Allow-modification-of-image-tags.patch
  projects/fluxcd/flux2/helm/sedfile.template
Labels: approved, lgtm, size/L

#305 handle nonstandard attribution file names and ignored files
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#308 Use whatever repo we are supposed to and docker config.json
  Common.mk
  build/lib/helm_push.sh
Labels: approved, lgtm, size/S

#309 Avoid mirror for now
  Common.mk
Labels: approved, lgtm, size/XS

#311 Fix readme links
  docs/development/attribution-files.md
Labels: approved, lgtm, size/XS

#312 Add helm to license gather
  Common.mk
Labels: approved, lgtm, size/XS

#314 Have the cert-manager helm chart use digest
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/helm/patches/0003-Activate-digests-with-templates.patch
  projects/jetstack/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/M
