Repository aws/eks-anywhere-build-tooling, pull requests merged in 2021-09, with the labels that each got.

#34 Remove script for tag update PR automation
  scripts/pr_automation/eks_distro_base_pr_body
  scripts/pr_automation/update_tag.sh
Labels: approved, lgtm

#35 Add Github issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#36 Remove year from license verbiage
  OWNERS
  projects/aws/eks-anywhere/build/create_attribution.sh
  projects/brancz/kube-rbac-proxy/build/create_attribution.sh
  projects/fluxcd/flux2/build/create_attribution.sh
  projects/fluxcd/helm-controller/build/create_attribution.sh
  projects/fluxcd/kustomize-controller/build/create_attribution.sh
  projects/fluxcd/notification-controller/build/create_attribution.sh
  projects/fluxcd/source-controller/build/create_attribution.sh
  projects/jetstack/cert-manager/build/create_attribution.sh
  projects/kubernetes-sigs/cluster-api-provider-aws/build/create_attribution.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_attribution.sh
  projects/kubernetes-sigs/cluster-api/build/create_attribution.sh
  projects/kubernetes-sigs/cri-tools/build/create_attribution.sh
  projects/kubernetes-sigs/etcdadm/build/create_attribution.sh
  projects/kubernetes-sigs/kind/build/build-kind-base-image.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/build-kindnetd-image.sh
  projects/kubernetes-sigs/kind/build/create_attribution.sh
  projects/kubernetes-sigs/kind/images/base/kubeadm-override.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/download-images.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/run.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/hack/print-workspace-status.sh
  projects/kubernetes-sigs/vsphere-csi-driver/build/create_attribution.sh
  projects/kubernetes/cloud-provider-vsphere/build/create_attribution.sh
  projects/mrajashree/etcdadm-bootstrap-provider/build/create_attribution.sh
  projects/mrajashree/etcdadm-controller/build/create_attribution.sh
  projects/plunder-app/kube-vip/build/create_attribution.sh
  projects/rancher/local-path-provisioner/build/create_attribution.sh
  projects/vmware/govmomi/build/create_attribution.sh
Labels: approved, lgtm, kind/cleanup

#37 Collapse base image tracker table
  README.md
Labels: approved, lgtm

#32 Remove secondary ECR repo references
  Makefile
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/aws/eks-anywhere/build/create_binaries.sh
  projects/brancz/kube-rbac-proxy/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/jetstack/cert-manager/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/build/create_binaries.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_binaries.sh
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/build/create_binaries.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/build-kindnetd-image.sh
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/build/create_binaries.sh
  projects/mrajashree/etcdadm-controller/Makefile
  projects/mrajashree/etcdadm-controller/build/create_binaries.sh
  projects/plunder-app/kube-vip/Makefile
  projects/rancher/local-path-provisioner/Makefile
Labels: approved, lgtm, size/L

#39 Fix build arg for base image
  projects/aws/eks-anywhere/Makefile
Labels: approved, lgtm

#40 Fix docker URI in kind node image script
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm

#43 work around codebuild gopath shennanigans by pre-installing controlle…
  projects/replicatedhq/troubleshoot/build/create_binaries.sh
Labels: approved, lgtm

#44 Check if docker machine or cluster is paused before reconciling
  projects/kubernetes-sigs/cluster-api/patches/0027-capd-do-not-reconcile-machine-if-cluster-or-machine-is-paused.patch
Labels: approved, lgtm, ok-to-test

#46 update base image comment to reflect reality
  projects/aws/eks-anywhere/docker/linux/eksa-diagnostic-collector/Dockerfile
Labels: approved, lgtm

#47 add yum clean to diagnostic collector image build
  projects/aws/eks-anywhere/docker/linux/eksa-diagnostic-collector/Dockerfile
Labels: approved, lgtm

#49 Update git tag for eks-anywhere project
  projects/aws/eks-anywhere/GIT_COMMIT
Labels: approved, lgtm

#41 Add capi patch for bottlerocket registry mirror support
  projects/kubernetes-sigs/cluster-api/patches/0028-add-support-for-registry-mirror-for-bottlerocket.patch
Labels: approved, lgtm, size/L

#51 update git commit tag to include collector image in bundle
  projects/aws/eks-anywhere/GIT_COMMIT
Labels: approved, lgtm, size/XS

#54 Converting from string to base 8 integer
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go
Labels: approved, lgtm, size/XS

#53 OWNERS file clean up
  OWNERS
Labels: approved, lgtm, size/XS

#56 remove goproxy overrides so in prow these use athens
  projects/aws/eks-anywhere/Makefile
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/jetstack/cert-manager/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/plunder-app/kube-vip/Makefile
  projects/replicatedhq/troubleshoot/Makefile
Labels: approved, lgtm, size/M

#59 Add eric to owners
  OWNERS
Labels: approved, lgtm, size/S

#60 bump to latest eks-d release
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#61 Automated cherry pick of #52: Update base image tag file(s)
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_CSI_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GLIBC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_IPTABLES_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NONROOT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_TAG_FILE
Labels: approved, lgtm, size/S

#62 Automated cherry pick of #60: bump to latest eks-d release
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#63 Add kubectl to collector image
  projects/aws/eks-anywhere/Makefile
  projects/aws/eks-anywhere/build/fetch_binaries.sh
  projects/aws/eks-anywhere/docker/linux/Dockerfile
Labels: approved, lgtm, size/M

#65 Fix proxy template for bottlerocket bootstrap
  projects/kubernetes-sigs/cluster-api/patches/0029-Fix-proxy-template-for-bottlerocket-bootstrap.patch
Labels: approved, lgtm, size/M
