Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-06, with the labels that each got.

#863 add harbor-scanner-trivy
  Makefile
  projects/aquasecurity/harbor-scanner-trivy/.gitignore
  projects/aquasecurity/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/Help.mk
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/harbor-scanner-trivy/README.md
  projects/aquasecurity/harbor-scanner-trivy/expected_artifacts
Labels: approved, lgtm, size/XL

#866 CAPT rufio patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Automated-powerOn-powerOff-with-rufio.patch
Labels: approved, lgtm, size/XL

#871 Updates go-licenses and silences some new noisy messages
  build/lib/common.sh
  build/lib/install_go_versions.sh
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
Labels: approved, lgtm, size/M

#872 Rufio helm chart
  projects/tinkerbell/helm-chart/templates/baseboardmanagement-crd.yaml
  projects/tinkerbell/helm-chart/templates/bmcjob-crd.yaml
  projects/tinkerbell/helm-chart/templates/bmctask-crd.yaml
  projects/tinkerbell/helm-chart/templates/rufio-cluster-role-binding.yaml
  projects/tinkerbell/helm-chart/templates/rufio-cluster-role.yaml
  projects/tinkerbell/helm-chart/templates/rufio-deployment.yaml
  projects/tinkerbell/helm-chart/templates/rufio-leader-election-role-binding.yaml
  projects/tinkerbell/helm-chart/templates/rufio-leader-election-role.yaml
  projects/tinkerbell/helm-chart/templates/rufio-manager-configmap.yaml
  projects/tinkerbell/helm-chart/templates/rufio-secrets-viewer-role-binding.yaml
  projects/tinkerbell/helm-chart/templates/rufio-secrets-viewer-role.yaml
  projects/tinkerbell/helm-chart/templates/rufio-service-account.yaml
  projects/tinkerbell/helm-chart/values.yaml
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
Labels: approved, lgtm, size/XL

#862 add trivy scanner
  Makefile
  projects/aquasecurity/trivy/.gitignore
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/Help.mk
  projects/aquasecurity/trivy/Makefile
  projects/aquasecurity/trivy/README.md
  projects/aquasecurity/trivy/expected_artifacts
  projects/distribution/distribution/README.md
Labels: approved, lgtm, size/XXL

#864 Add logic to build and publish the tinkerbell helm chart
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/tinkerbell/tinkerbell-chart/chart/.helmignore
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/baseboardmanagement-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/bmcjob-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/bmctask-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots-deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hardware-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel-deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/namespace.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-cluster-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-cluster-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-leader-election-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-leader-election-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-manager-configmap.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-secrets-viewer-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-secrets-viewer-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/template-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller-cluster-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller-cluster-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller-deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-leader-election-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-leader-election-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server-deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/workflow-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/values.yaml
Labels: approved, lgtm, size/M

#873 Changing entrypoint for Rufio manager image
  projects/tinkerbell/rufio/docker/linux/Dockerfile
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-deployment.yaml
Labels: approved, lgtm, size/XS

#838 Increases build stability when wget licenses and docker pull
  build/lib/common.sh
  build/lib/setup.sh
  projects/distribution/distribution/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/goharbor/harbor/Makefile
  projects/helm/helm/Makefile
  projects/jetstack/cert-manager/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/create-kind-cluster.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/download-images.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/replicatedhq/troubleshoot/Makefile
Labels: approved, lgtm, size/M

#876 Patch hook to skip pulling registry cert
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0001-Download-registry-cert-only-if-tinkerbell_tls-is-tru.patch
Labels: approved, lgtm, size/M

#870 Add harbor-trivy
  projects/goharbor/harbor/Help.mk
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile
Labels: approved, lgtm, size/M

#875 Updates go-licenses and silences some new noisy messages (#871)
  build/lib/common.sh
  build/lib/install_go_versions.sh
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
Labels: approved, lgtm, size/M

#877 fix where trivy image is pushed to
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/XS

#879 Adds RHEL v1-23 build specs
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-rhel-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-rhel-raw.yml
Labels: approved, lgtm, size/M

#885 Helm add configs for hello app
  projects/aws-containers/hello-eks-anywhere/helm/requires-config.yaml
Labels: approved, lgtm, size/XS

#841 Generate staging buildspec from Makefiles
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/all_projects.sh
  build/lib/fetch_binaries.sh
  build/lib/generate_projects_list.sh
  build/lib/generate_staging_buildspec.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/fluxcd/flux2/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/sandbox-local-registry/DO_NOT_BUILD
  projects/tinkerbell/sandbox/DO_NOT_BUILD
  projects/tinkerbell/tink/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/XL

#881 Helm charts with no files.txt
  build/lib/helm_replace.sh
  projects/aws-containers/hello-eks-anywhere/helm/files.txt
  projects/aws/eks-anywhere-packages/helm/files.txt
  projects/fluxcd/flux2/helm/files.txt
  projects/goharbor/harbor/helm/files.txt
  projects/jetstack/cert-manager/helm/files.txt
Labels: approved, lgtm, size/S

#886 Helm add Harbor requires configs
  projects/goharbor/harbor/helm/requires-config.yaml
Labels: approved, lgtm, size/M

#890 Add GIT_TAG for tinkerbell-helm
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/tinkerbell/tinkerbell-chart/scripts/verify.sh
Labels: approved, lgtm, size/M

#889 update harbor helm chart
  projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch
  projects/goharbor/harbor/helm/sedfile.template
Labels: approved, lgtm, size/XS

#891 fix permission issue
  projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile
Labels: approved, lgtm, size/XS

#892 remove kube-rbac-proxy from helm list for packages
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/XS

#874 Patch writefile workflow template:
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0001-Write-DHCP-offer-to-static-Netplan-file.patch
Labels: approved, lgtm, size/L

#895 Implement retry logic for tink-worker docker image pull...
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0002-Implement-retry-for-tink-worker-docker-image-pull-to.patch
Labels: approved, lgtm, size/M

#893 CAPT Rufio updates and patches
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/baseboardmanagement-crd.yaml
Labels: approved, lgtm, size/S

#902 Adding a patch to add CAPT BMCjob watch
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0002-Adding-watch-on-Rufio-BMCJob.patch
Labels: approved, lgtm, size/L

#903 Fix EOF errors occuring during Packer build
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/XS

#904 Remove CAPI labels from the crds
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/bmcjob-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/bmctask-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/workflow-crd.yaml
Labels: approved, lgtm, size/S

#907 Update EKSD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#911 CAPT job power reset action
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0004-Replace-poweroff-poweron-with-reset.patch
Labels: approved, lgtm, size/M

#909 Update EKS Anywhere Packages tag to 11
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#914 Revert "CAPT job power reset action"
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0004-Replace-poweroff-poweron-with-reset.patch
Labels: approved, lgtm, size/M

#915 Patch to allow kubeadm bootstrap token TTL to be configurable via clusterctl
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0020-Allow-kubeadm-bootstrap-token-TTL-to-be-configurable.patch
Labels: approved, lgtm, size/M

#900 Upgrade harbor-scanner-trivy to v0.28.0
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/L

#920 Patch writefile workflow template:
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0001-Write-DHCP-offer-to-static-Netplan-file.patch
Labels: approved, lgtm, size/M

#884 Create a patch for retrying to list members in the join command
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/patches/0014-Add-retry-on-listing-members-in-join-command.patch
Labels: approved, lgtm, size/M

#925 Updating Rufio commit and adding temp patch
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/patches/0001-Temp-fix-for-ipmitool-status-message.patch
Labels: approved, lgtm, size/M

#927 add go1.18
  build/lib/common.sh
  build/lib/install_go_versions.sh
Labels: approved, lgtm, size/XS

#901 Upgrade trivy to v0.28.1
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/Makefile
  projects/aquasecurity/trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/L

#930 Upgrade harbor-scanner-trivy to v0.29.0
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/XL

#928 Fix Harbor HELM_GIT_TAG
  projects/goharbor/harbor/HELM_GIT_TAG
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/XS

#922 Update README with 1.23
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#921 Add 1.23 builds for Bottlerocket
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/S

#926 Parametrize image OS and release branch in image-builder buildspecs
  Common.mk
  build/lib/generate_staging_buildspec.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-rhel-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-rhel-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-rhel-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-rhel-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-rhel-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-rhel-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-rhel-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-rhel-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-ubuntu-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#936 Bump up etcdadm related controllers versions
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#944 Fix unset environment variable in harbor-trivy image
  projects/goharbor/harbor/HELM_GIT_TAG
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch
  projects/goharbor/harbor/helm/sedfile.template
Labels: approved, lgtm, size/L

#947 Update versions
  projects/aquasecurity/harbor-scanner-trivy/README.md
  projects/aquasecurity/trivy/README.md
  projects/goharbor/harbor/README.md
Labels: approved, lgtm, size/S

#949 Fixes update checksum in docker target
  build/lib/run_target_docker.sh
Labels: approved, lgtm, size/S

#950 Bump CAPT and remove patches
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Automated-powerOn-powerOff-with-rufio.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0002-Adding-watch-on-Rufio-BMCJob.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0003-Adding-MachineReady-label-to-TinkerbellMAchine-and-c.patch
Labels: approved, lgtm, size/XXL

#946 Image builder for Bottlerocket Metal Variant
  build/lib/common.sh
  build/lib/validate_artifacts.sh
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ova
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ova_bottlerocket
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_raw
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_raw_bottlerocket
Labels: approved, lgtm, size/L

#919 Add readme check script
  Makefile
  build/lib/readme_check.sh
  projects/aws-containers/hello-eks-anywhere/README.md
  projects/aws/eks-anywhere-packages/README.md
  projects/cilium/cilium/README.md
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
  projects/kubernetes-sigs/cluster-api/README.md
  projects/redis/redis/README.md
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/rufio/README.md
  projects/tinkerbell/tink/README.md
Labels: approved, lgtm, size/M

#951 Security patch for Trivy
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/XL

#956 Bump CAPAS version to 0.1.5
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/S

#958 Bumping up linux kernel and go version to match hook commit
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/LINUX_KERNEL_VERSION
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
Labels: approved, lgtm, size/S

#960 Upgrade troubleshoot to v0.36.0
  UPSTREAM_PROJECTS.yaml
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/GIT_TAG
  projects/replicatedhq/troubleshoot/README.md
  projects/replicatedhq/troubleshoot/expected_artifacts
  projects/replicatedhq/troubleshoot/patches/0002-Add-nil-check-to-analyzer-processing.patch
Labels: approved, lgtm, size/M

#962 Changing harbor values to strings
  projects/goharbor/harbor/helm/requires-config.yaml
Labels: approved, lgtm, size/M

#964 Fix typo
  projects/goharbor/harbor/helm/requires-config.yaml
Labels: approved, lgtm, size/XS

#965 Bumps to latest ekd-s releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#957 Add servies for hegel and tink-server in tinkerbell chart
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel-daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel-service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip-daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server-service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/values.yaml
Labels: approved, lgtm, size/L

#610 Move cert-manager to new repository owner
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/.gitignore
  projects/cert-manager/cert-manager/ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/Help.mk
  projects/cert-manager/cert-manager/Makefile
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/build/create_manifests.sh
  projects/cert-manager/cert-manager/docker/linux/cert-manager-acmesolver/Dockerfile
  projects/cert-manager/cert-manager/docker/linux/cert-manager-cainjector/Dockerfile
  projects/cert-manager/cert-manager/docker/linux/cert-manager-controller/Dockerfile
  projects/cert-manager/cert-manager/docker/linux/cert-manager-ctl/Dockerfile
  projects/cert-manager/cert-manager/docker/linux/cert-manager-webhook/Dockerfile
  projects/cert-manager/cert-manager/expected_artifacts
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#967 [Bugfix] Add bottlerocket control image on joining nodes
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-update-coredns-corefile-migration-to-support-1.8.7.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Allow-kubeadm-bootstrap-token-TTL-to-be-configurable.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
Labels: approved, lgtm, size/L, ok-to-test

#963 [release-0.9][Bugfix] Add bottlerocket control image on joining nodes
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-update-coredns-corefile-migration-to-support-1.8.7.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
Labels: approved, lgtm, size/L, ok-to-test

#953 Fix README version field for projects with dashes in tag
  build/lib/readme_check.sh
  projects/cilium/cilium/README.md
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
  projects/tinkerbell/rufio/README.md
  projects/tinkerbell/tink/README.md
Labels: approved, lgtm, size/S

#977 add packages to support air-gapped use case of harbor-trivy
  projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile
Labels: approved, lgtm, size/XS

#973 bump tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: lgtm, size/XS

#974 Adding Ubuntu RAW images to release staging build
  projects/kubernetes-sigs/image-builder/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#988 Skip BR raw image operations for Kubernetes version 1.20
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#991 Add cert-manager helm chart
  build/lib/helm_push.sh
  build/lib/helm_replace.sh
  projects/cert-manager/cert-manager/Makefile
  projects/cert-manager/cert-manager/helm/patches/0001-Use-registry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Generate-readme-and-chart-templates.patch
  projects/cert-manager/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/L

#910 Add metallb binaries + images build
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/.gitignore
  projects/metallb/metallb/ATTRIBUTION.txt
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/Help.mk
  projects/metallb/metallb/Makefile
  projects/metallb/metallb/README.md
  projects/metallb/metallb/docker/linux/controller/Dockerfile
  projects/metallb/metallb/docker/linux/speaker/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#997 bumping tag
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#955 Metallb helm
  projects/metallb/metallb/Makefile
  projects/metallb/metallb/docker/linux/speaker/Dockerfile
  projects/metallb/metallb/helm/patches/0001-initial-patch.yaml
  projects/metallb/metallb/helm/sedfile.template
Labels: approved, lgtm, size/XL

#1000 Move kube-vip project to the kube-vip org
  UPSTREAM_PROJECTS.yaml
  projects/kube-vip/kube-vip/.gitignore
  projects/kube-vip/kube-vip/ATTRIBUTION.txt
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kube-vip/kube-vip/GIT_TAG
  projects/kube-vip/kube-vip/Help.mk
  projects/kube-vip/kube-vip/Makefile
  projects/kube-vip/kube-vip/README.md
  projects/kube-vip/kube-vip/docker/linux/Dockerfile
  projects/kube-vip/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1006 Update cert-manager.yaml manifest to 1.7.2
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
Labels: approved, lgtm, size/XXL

#1008 Add CRDs to cert-manager helm chart
  projects/cert-manager/cert-manager/helm/patches/0001-Use-registry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Generate-readme-and-chart-templates.patch
Labels: approved, lgtm, size/XXL

#1010 Bumping CAPC to v0.4.5-rc4 which fixes a couple bugs
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1014 Fixing CAPC affinity group deletion bug
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1019 Replacing CAPC commit hash with tag
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/XS
