Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-10, with the labels that each got.

#1344 Fix helm_push for ecr public
  build/lib/helm_push.sh
Labels: approved, lgtm, size/S

#1376 Update hello EKS to v0.1.2
  projects/aws-containers/hello-eks-anywhere/GIT_TAG
  projects/aws-containers/hello-eks-anywhere/helm/patches/0001-Adding-imagePullSecret-support.patch
  projects/aws-containers/hello-eks-anywhere/helm/patches/0001-Adding-namespace-and-imagePullSecret-support.patch
Labels: approved, lgtm, size/L

#1332 Initial checkin to create nutanix image for eks-a
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/kubernetes-sigs/image-builder/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
Labels: approved, lgtm, size/L, ok-to-test

#1375 Update packages build to go 1.18
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/S

#1380 Update Golang version for CAPX
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
Labels: approved, lgtm, size/XS, ok-to-test

#1383 Add verbose logging to source-controller build
  build/update-attribution-files/create_pr.sh
  projects/fluxcd/source-controller/Makefile
Labels: approved, size/M

#1386 Run release branch specific builds for kind in staging
  build/lib/generate_staging_buildspec.sh
  projects/kubernetes-sigs/kind/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1389 Adds docker option for cgo builds
  Common.mk
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/source-controller/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1387 Export required environment vars for raw redhat builds
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#1395 Fix kind dependency for CLI tools image in staging build
  build/lib/generate_staging_buildspec.sh
  release/staging-build.yml
Labels: approved, lgtm, size/S

#1393 Remove namespace from chart
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
Labels: approved, lgtm, size/S

#1391 Include cert manager schema
  projects/cert-manager/cert-manager/helm/schema.json
Labels: approved, lgtm, size/XXL

#1394 Added EKS-D 1.24-1 prod
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#1396 Breaks binary and image build up for kind in staging
  build/lib/generate_staging_buildspec.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/buildspecs/binaries.yml
  projects/kubernetes-sigs/kind/buildspecs/images.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#1400 Breaks vsphere-cpi up into different builds for staging
  build/lib/generate_staging_buildspec.sh
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1399 Patch to exclude kernel updates for Redhat
  projects/kubernetes-sigs/image-builder/patches/0010-Exclude-kernel-updates-for-Redhat.patch
Labels: approved, lgtm, size/S

#1403 bumping packages tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1401 now patching the repo before building nutanix image
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/S, ok-to-test

#1402 Backport staging batch build improvements
  build/lib/generate_staging_buildspec.sh
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/buildspecs/binaries.yml
  projects/kubernetes-sigs/kind/buildspecs/images.yml
  projects/kubernetes/cloud-provider-vsphere/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/L

#1390 Upgrade cert manager
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/Makefile
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
Labels: approved, lgtm, size/XL

#1408 metrics-server Enable Building 1-24
  projects/kubernetes-sigs/metrics-server/1-24/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-24/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/Makefile
Labels: approved, lgtm, size/XXL

#1409 Rename cluster-autoscaler helm destination repo
  projects/kubernetes/autoscaler/Makefile
Labels: approved, lgtm, size/XS

#1414 Correct cluster-autoscaler Default Source Registry
  projects/kubernetes/autoscaler/1-21/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-22/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-23/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0004-Use-eks-anywhere-default-registry.patch
Labels: approved, lgtm, size/L

#1412 Remove null types from metrics-cluster schema.json
  projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
Labels: approved, lgtm, size/XS

#1413 Add git hash to cluster autoscaler helm tags
  projects/kubernetes/autoscaler/Makefile
Labels: approved, lgtm, size/XS

#1418 Handle unsupported os and format combinations for Image Builder
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#1398 Specify correct appVersion in Cluster Autoscaler
  projects/kubernetes/autoscaler/1-21/helm/sedfile.template
  projects/kubernetes/autoscaler/1-22/helm/sedfile.template
  projects/kubernetes/autoscaler/1-23/helm/sedfile.template
  projects/kubernetes/autoscaler/1-24/helm/sedfile.template
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/XS

#1419 Update EKS-D for 1.20 - 1.23
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1420 Bump up kube-vip to v0.5.5
  UPSTREAM_PROJECTS.yaml
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kube-vip/kube-vip/GIT_TAG
  projects/kube-vip/kube-vip/README.md
Labels: approved, lgtm, size/S

#1422 Align Image Pull Secrets to Convention
  projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
  projects/kubernetes/autoscaler/1-21/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-21/helm/schema.json
  projects/kubernetes/autoscaler/1-22/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-22/helm/schema.json
  projects/kubernetes/autoscaler/1-23/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-23/helm/schema.json
  projects/kubernetes/autoscaler/1-24/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-24/helm/schema.json
Labels: approved, lgtm, size/XL

#1426 Bump packages v.0.2.10
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1428 Bumping packages tag to v0.2.10-alpha1
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1429 Image builder support for Cloudstack
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/L

#1430 Bumping packages to v0.2.11
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1432 Add d8660091 to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#1433 Update CAPX version
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
Labels: approved, lgtm, size/L, ok-to-test

#1437 Upgrade packages to v0.2.12
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1427 Bumping CAPC to newer version to include bugfixes
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S, ok-to-test

#1443 add ahreehong to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1436 Cloudstack - Redhat Image Builds on CI
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
Labels: approved, lgtm, size/M

#1444 Update bottlerocket to v1.10.0 and update bottlerocket-admin-container to v1.9.2
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1435 Upgrade metallb to 0.13.5 and split the crds chart
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/ATTRIBUTION.txt
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/Makefile
  projects/metallb/metallb/helm/patches/0001-Use-CRD-format-from-v0.13.x-and-convert-to-configmap.patch
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
  projects/metallb/metallb/helm/patches/0002-Adding-imagePullSecrets-and-extracting-default-names.patch
  projects/metallb/metallb/helm/schema.json
Labels: approved, lgtm, size/XXL

#1447 Add support for dependencies in requires.yaml
  build/lib/helm_require.sh
  projects/metallb/metallb/Makefile
Labels: approved, lgtm, size/S

#1450 Add 1.24 BR ova release
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#1454 Include cert manager namespace and image Pull secret to chart
  projects/cert-manager/cert-manager/helm/patches/0004-Configure-cert-manager-namespace-and-imagePullSecret.patch
Labels: approved, lgtm, size/L

#1458 Fix dependencies being empty if undefined
  build/lib/helm_require.sh
Labels: approved, lgtm, size/XS

#1463 remove / from name
  projects/metallb/metallb/Makefile
Labels: approved, lgtm, size/XS

#1464 Update package controller to v0.2.13
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1465 Bumping CAPC to use newer version
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1470 Fix CA & Metrics Server imagePullSecrets Schema
  projects/kubernetes-sigs/metrics-server/1-21/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-22/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-23/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
  projects/kubernetes/autoscaler/1-21/helm/schema.json
  projects/kubernetes/autoscaler/1-22/helm/schema.json
  projects/kubernetes/autoscaler/1-23/helm/schema.json
  projects/kubernetes/autoscaler/1-24/helm/schema.json
Labels: approved, lgtm, size/L

#1476 Fix output image extension for metal builds
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#1477 Fix cert manager webhook
  projects/cert-manager/cert-manager/helm/patches/0005-Update-cert-manager-namespace-config.patch
Labels: approved, lgtm, size/S

#1481 Standardize namespace setting and add missing on webhook
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/L

#1484 Remove autoassign from l2adv
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/S

#1488 Helm evaluates false as undefined, fix metallb autoAssign
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/S

#1491 Make sourceRegistry Top Level Value
  projects/kubernetes-sigs/metrics-server/1-21/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-22/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-23/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
  projects/kubernetes/autoscaler/1-21/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-21/helm/schema.json
  projects/kubernetes/autoscaler/1-22/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-22/helm/schema.json
  projects/kubernetes/autoscaler/1-23/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-23/helm/schema.json
  projects/kubernetes/autoscaler/1-24/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-24/helm/schema.json
Labels: approved, lgtm, size/L

#1493 Standardize templates for easier maintenance and add peer
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/M

#1494 Sync ipaddresspool caps with upstream
  projects/metallb/metallb/helm/schema.json
Labels: approved, lgtm, size/S

#1497 Update to packages v0.2.14
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1501 Bumping CAPC to v0.4.8 release
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/XS

#1503 Updated EKS-D to latest for all versions
  EKSD_LATEST_RELEASES
  projects/kubernetes/cloud-provider-vsphere/1-22/CHECKSUMS
Labels: approved, lgtm, size/S

#1514 Bump BR release version
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1516 Update package release
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S
