Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-04, with the labels that each got.

#529 capv: upgrade to 1.1.1
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Adding-capv-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0002-Requeue-vsphereMachine.patch
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0002-update-revive-dep-to-fix-go-mod-checksum-mismatch.patch
Labels: approved, lgtm, size/XL

#638 Adding CAPT patch to update PBNJ version
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0013-Updating-PBNJ-commit-version.patch
Labels: approved, lgtm, size/L

#645 add missing projects to all_projects list and update checksums
  Common.mk
  Makefile
  build/lib/common.sh
  build/lib/install_go_versions.sh
  projects/apache/cloudstack-cloudmonkey/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/grpc-ecosystem/grpc-health-probe/CHECKSUMS
  release/staging-build.yml
Labels: approved, lgtm, size/M

#647 hook: use latest var instead of hardcoded latest
  projects/tinkerbell/hook/Makefile
Labels: approved, lgtm, size/XS

#644 kind: upgrade to 0.12.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
Labels: approved, lgtm, size/XL

#652 Bump EKS Anywhere Packages to v0.1.5
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#656 Implement retry logic for tink-worker docker image pull...
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0002-Implement-retry-for-tink-worker-docker-image-pull-to.patch
Labels: approved, lgtm, size/M

#660 Update readme
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/XS

#662 Bump packages to v0.1.6
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#633 Add reboot action to hub
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/hub/docker/linux/reboot/Dockerfile
Labels: approved, lgtm, size/S

#663 add local registry for tinkerbell to host container images and OS images
  projects/tinkerbell/sandbox-local-registry/.env
  projects/tinkerbell/sandbox-local-registry/README.md
  projects/tinkerbell/sandbox-local-registry/docker-compose.yml
  projects/tinkerbell/sandbox-local-registry/registry/download.sh
  projects/tinkerbell/sandbox-local-registry/registry/os_images.txt
  projects/tinkerbell/sandbox-local-registry/registry/registry_images.txt
  projects/tinkerbell/sandbox-local-registry/registry/upload.sh
  projects/tinkerbell/sandbox-local-registry/state/webroot/misc/osie/current/.keep
  projects/tinkerbell/sandbox-local-registry/state/webroot/misc/ubuntu/v1.20/.keep
  projects/tinkerbell/sandbox-local-registry/state/webroot/misc/ubuntu/v1.21/.keep
  projects/tinkerbell/sandbox-local-registry/state/webroot/misc/ubuntu/v1.22/.keep
  projects/tinkerbell/sandbox-local-registry/state/webroot/workflow/.keep
  projects/tinkerbell/sandbox-local-registry/tls/ca-config.json
  projects/tinkerbell/sandbox-local-registry/tls/ca-csr.json
  projects/tinkerbell/sandbox-local-registry/tls/csr.json
  projects/tinkerbell/sandbox-local-registry/tls/generate.sh
  projects/tinkerbell/sandbox-local-registry/tls/trust.sh
Labels: approved, lgtm, size/XL

#666 Using CAPC 0.4.2
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
Labels: approved, lgtm, size/XS

#670 Bump CAPAS version to 0.1.4
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#665 Upgrade helm version
  projects/helm/helm/ATTRIBUTION.txt
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/GIT_TAG
  projects/helm/helm/Makefile
  projects/helm/helm/README.md
  projects/helm/helm/patches/0001-Insecure-flag-for-oci-push-pull-install.patch
Labels: approved, lgtm, size/L

#671 Rename imageRegistry to sourceRegistry
  projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch
Labels: approved, lgtm, size/M

#539 Update kube-vip manifest for AMIs
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
Labels: approved, lgtm, size/S

#668 Adding hello-eks-anywhere test image for Packages
  projects/aws-containers/hello-eks-anywhere/ATTRIBUTION.txt
  projects/aws-containers/hello-eks-anywhere/GIT_TAG
  projects/aws-containers/hello-eks-anywhere/Help.mk
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-containers/hello-eks-anywhere/README.md
  projects/aws-containers/hello-eks-anywhere/conf/default.conf
  projects/aws-containers/hello-eks-anywhere/conf/hello.sh
  projects/aws-containers/hello-eks-anywhere/conf/index.html
  projects/aws-containers/hello-eks-anywhere/docker/linux/Dockerfile
  projects/aws-containers/hello-eks-anywhere/helm/files.txt
  projects/aws-containers/hello-eks-anywhere/helm/requires-config.yaml
  projects/aws-containers/hello-eks-anywhere/helm/sedfile.template
Labels: approved, lgtm, size/L

#672 Populate tag in helm chart requires.yaml
  build/lib/helm_require.sh
Labels: approved, lgtm, size/S

#669 Fix upload paths for imagebuilder targets
  build/lib/validate_artifacts.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/expected_artifacts_ova
  projects/kubernetes-sigs/image-builder/expected_artifacts_ova_bottlerocket
Labels: approved, lgtm, size/M

#680 Put packer config files at the appropriate location where packer builds look for them
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/S

#681 Fix packer log path for OVA builds
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#685 Remove eks-anywhere-test in favor of hello app
  projects/aws/eks-anywhere-test/ATTRIBUTION.txt
  projects/aws/eks-anywhere-test/GIT_TAG
  projects/aws/eks-anywhere-test/Help.mk
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere-test/README.md
  projects/aws/eks-anywhere-test/conf/default.conf
  projects/aws/eks-anywhere-test/conf/entrypoint.sh
  projects/aws/eks-anywhere-test/conf/index.template
  projects/aws/eks-anywhere-test/docker/linux/Dockerfile
  projects/aws/eks-anywhere-test/eks-anywhere-test/.helmignore
  projects/aws/eks-anywhere-test/eks-anywhere-test/Chart.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/_helpers.tpl
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/config.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/deployment.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/pvc.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/secret.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/service.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/tests/test-connection.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/values.yaml
  projects/aws/eks-anywhere-test/helm/files.txt
  projects/aws/eks-anywhere-test/helm/requires-config.yaml
  projects/aws/eks-anywhere-test/helm/sedfile.template
Labels: approved, lgtm, size/L

#684 Add ivyostosh to owners
  OWNERS
Labels: approved, lgtm, size/XS

#682 Remove setting HELM_REGISTRY and use sourceRegistry instread
  build/lib/helm_replace.sh
  projects/aws-containers/hello-eks-anywhere/helm/sedfile.template
  projects/aws/eks-anywhere-packages/helm/sedfile.template
  projects/fluxcd/flux2/helm/sedfile.template
  projects/jetstack/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/XS

#689 Add config and version to hello app
  projects/aws-containers/hello-eks-anywhere/.gitignore
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-containers/hello-eks-anywhere/conf/hello.sh
  projects/aws-containers/hello-eks-anywhere/conf/index.template
  projects/aws-containers/hello-eks-anywhere/docker/linux/Dockerfile
Labels: approved, lgtm, size/M

#690 Fix the hello build badge
  projects/aws-containers/hello-eks-anywhere/README.md
Labels: approved, lgtm, size/XS

#694 Add hello eks app to all projects
  Makefile
  projects/aws-containers/hello-eks-anywhere/Help.mk
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
Labels: approved, lgtm, size/S

#687 Update CAPI tag to v1.1.3
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Templating-bottlerocket-init-data-formats.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Generating-proper-vip-destnation-path-for-bottlerock.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Fix-kube-vip-config-patching-by-creating-new-Files-a.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Adding-pause-and-bottlerocket-bootstrap-Cluster-conf.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-Add-bottlerocket-API-changes-to-v1beta1-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Set-bottlerocket-bootstrap-container-and-pause-conta.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-proxy-config-fields-to-v1beta1-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Support-proxy-configuration-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-network-settings-only-when-there-is-a-proxy-defi.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Remove-userdata-logging-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Unstacked-etcd-API-and-config-changes.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Unstacked-etcd-Changes-in-CAPI-core-controllers.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Unstacked-etcd-Changes-in-KCP-controller.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Unstacked-etcd-Change-in-docker-infra-provider.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Unstacked-etcd-Ignore-nodeRef-check-for-etcd-machine.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Delete-managed-external-etcd-cluster-last.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-update-coredns-corefile-migration-to-support-1.8.7.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Update-KCP-controller-to-use-renamed-etcd-endpoints-.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-external-etcd-api-changes-to-v1beta1-capi-CRDs.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Reconcile-docker-machine-address-after-clusterctl-mo.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Rename-controlplane-upgrade-annotation-variable.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-controlplane-upgrade-complete-annotation-to-sync.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Check-if-controlplane-is-paused-before-patching-it-w.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Patch-etcd-cluster-with-upgrade-complete-annotation-.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Fix-etcdMachine-to-cluster-reconciler-so-it-listens-.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Update-log-message-based-on-1.0.1-tag.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Fix-watch-on-machine-object-for-etcdMachine-to-clust.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-external-etcd-api-to-v1alpha4.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Update-semver-build-indentifier-comparison-to-suppor.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Use-shared-semver-compare-package-for-cert-manager-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Retain-update-permission-on-etcdadmcluster-for-KCP-c.patch
  projects/kubernetes-sigs/cluster-api/patches/0046-update-coredns-corefile-migration-to-support-1.8.7.patch
Labels: approved, lgtm, size/XXL

#698 Fix kcp components.yaml to include BR
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-update-coredns-corefile-migration-to-support-1.8.7.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Change-format-for-storing-etcd-machine-address.patch
Labels: approved, lgtm, size/L

#700 Add RHEL 8 to RHEL versions list in image-builder Makefile
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/S

#701 Use S3 URL for downloading RHEL ISO
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/XS

#702 Fix hello registry/repository thing
  projects/aws-containers/hello-eks-anywhere/Makefile
Labels: approved, lgtm, size/XS

#683 HELM_IMAGES replaced HELM_ADDITIONAL_KEY_VALUES
  Common.mk
  build/lib/helm_replace.sh
Labels: approved, lgtm, size/XS

#703 Check the 'State' field of Hardware object is set to 'HardwareAvailable"
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0014-When-checking-availability-while-picking-hardware-to.patch
Labels: approved, lgtm, size/M

#705 Remove patch for hardware availability state check
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0014-When-checking-availability-while-picking-hardware-to.patch
Labels: approved, lgtm, size/M

#706 Fixing hello build job
  projects/aws-containers/hello-eks-anywhere/Makefile
Labels: approved, lgtm, size/XS

#708 avoid assign shell calls in makefile macros
  Common.mk
  Makefile
  projects/apache/cloudstack-cloudmonkey/Makefile
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/cluster-api-provider-cloudstack/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/brancz/kube-rbac-proxy/Makefile
  projects/cilium/cilium/Makefile
  projects/cloudflare/cfssl/Makefile
  projects/distribution/distribution/Makefile
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/goharbor/harbor/Makefile
  projects/grpc-ecosystem/grpc-health-probe/Makefile
  projects/helm/helm/Makefile
  projects/jetstack/cert-manager/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-controller/Makefile
  projects/plunder-app/kube-vip/Makefile
  projects/rancher/local-path-provisioner/Makefile
  projects/redis/redis/Makefile
  projects/replicatedhq/troubleshoot/Makefile
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/tink/Makefile
  projects/vmware/govmomi/Makefile
Labels: approved, lgtm, size/L

#709 generate attribution before building images
  Common.mk
Labels: approved, lgtm, size/XS

#711 Revert "Fixing hello build job"
  projects/aws-containers/hello-eks-anywhere/Makefile
Labels: approved, lgtm, size/XS

#710 Snow EKS-A admin AMI packer build
  projects/aws/eks-a-snow-admin-image/Help.mk
  projects/aws/eks-a-snow-admin-image/Makefile
  projects/aws/eks-a-snow-admin-image/README.md
  projects/aws/eks-a-snow-admin-image/build/export-ami-to-s3.sh
  projects/aws/eks-a-snow-admin-image/build/get_kubectl_url.sh
  projects/aws/eks-a-snow-admin-image/provisioners/cleanup.sh
  projects/aws/eks-a-snow-admin-image/provisioners/download_eksa_artifacts.sh
  projects/aws/eks-a-snow-admin-image/provisioners/install_docker.sh
  projects/aws/eks-a-snow-admin-image/provisioners/install_eksa.sh
  projects/aws/eks-a-snow-admin-image/provisioners/install_kubectl.sh
  projects/aws/eks-a-snow-admin-image/provisioners/test/download_eksa_artifacts.sh
  projects/aws/eks-a-snow-admin-image/provisioners/test/install_docker.sh
  projects/aws/eks-a-snow-admin-image/provisioners/test/install_eksa.sh
  projects/aws/eks-a-snow-admin-image/provisioners/test/install_kubectl.sh
  projects/aws/eks-a-snow-admin-image/provisioners/upgrade_linux.sh
  projects/aws/eks-a-snow-admin-image/snow-admin.pkr.hcl
Labels: approved, lgtm, size/XL

#712 Add patch to install Open VM tools during RHEL 8 OVA build
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Install-Open-VM-tools-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/M

#713 Update to hello-eks-anywhere v0.1.1
  projects/aws-containers/hello-eks-anywhere/GIT_TAG
Labels: approved, lgtm, size/XS

#717 Bumped EKS-D prod versions for 1.19-1.22
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#718 Use HTTP server as boot media path for RHEL 8 OVA builds
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Install-Open-VM-tools-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/L

#719 Add markapruett and jacobweinstack to owners
  OWNERS
Labels: approved, lgtm, size/XS

#707 better handling for projects with multiple go mod paths
  Common.mk
  docs/development/add-new-project.md
  projects/aws-containers/hello-eks-anywhere/ATTRIBUTION.txt
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/expected_artifacts
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
Labels: approved, lgtm, size/XL

#721 flux: bump to latest versions
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/gather_licenses.sh
  build/lib/install_go_versions.sh
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/helm-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/notification-controller/patches/0001-replace-containrrr-shoutrrr-due-to-checksum-mismatch.patch
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
Labels: approved, lgtm, size/XXL

#725 Update notification controller git tag in upstream projects tracker
  UPSTREAM_PROJECTS.yaml
Labels: approved, lgtm, size/XS

#726 Revert "flux: bump to latest versions"
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/gather_licenses.sh
  build/lib/install_go_versions.sh
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/helm-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/notification-controller/patches/0001-replace-containrrr-shoutrrr-due-to-checksum-mismatch.patch
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
Labels: approved, lgtm, size/XXL

#727 Fix source controller
  projects/fluxcd/source-controller/CHECKSUMS
Labels: size/XS

#728 troubleshoot: fix gather-licenses target
  projects/replicatedhq/troubleshoot/Makefile
Labels: approved, lgtm, size/XS

#729 Bring back flux upgrade with runasnonroot fix
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/gather_licenses.sh
  build/lib/install_go_versions.sh
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/helm-controller/docker/linux/Dockerfile
  projects/fluxcd/helm-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/kustomize-controller/docker/linux/Dockerfile
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/notification-controller/docker/linux/Dockerfile
  projects/fluxcd/notification-controller/patches/0001-replace-containrrr-shoutrrr-due-to-checksum-mismatch.patch
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/docker/linux/Dockerfile
  projects/fluxcd/source-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
Labels: approved, lgtm, size/XXL

#724 Increase file monitoring timeout to 40s
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/utils/waiters.go
Labels: approved, lgtm, size/XS, ok-to-test

#730 Cleanup of old sign/promo jobs
  Makefile
  build/lib/helm_promotion.sh
  build/lib/sign_file.sh
Labels: approved, lgtm, size/M

#732 Install gdisk utility on RHEL 8 OS images
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/S

#733 Update tinkerbell/tink to the latest tag and add tink-controller
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/docker/linux/tink-controller/Dockerfile
  projects/tinkerbell/tink/patches/0001-Fixing-go.mod-replace-commit.patch
  projects/tinkerbell/tink/patches/0002-Make-registry-credentials-command-line-parameters-op.patch
Labels: approved, lgtm, size/L

#679 Add kevinsalerno to owners
  OWNERS
Labels: approved, lgtm, size/XS

#738 Bump bottlerocket OVA version to latest
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/S

#737 Update tags for etcdadm providers
  UPSTREAM_PROJECTS.yaml
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-bootstrap-provider/Makefile
  projects/mrajashree/etcdadm-bootstrap-provider/README.md
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
  projects/mrajashree/etcdadm-controller/Makefile
  projects/mrajashree/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#743 new eks-d releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS
