Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-12, with the labels that each got.

#1623 Update adot helm chart appVersion
  projects/aws-observability/aws-otel-collector/helm/sedfile.template
Labels: approved, lgtm, size/XS

#1624 Remove mdsgabriel from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1625 Bump eksd versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1626 Updates to cilium 1.11.10
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#1627 Support multi DNI and static IP for snow
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/config/net.toml
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network_test.go
Labels: approved, lgtm, size/L

#1628 Pin RHEL version to 8.6
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-RHEL-to-8.6-version-to-avoid-cloud-init-bug.patch
Labels: approved, lgtm, size/S

#1621 upgraded nutanix capx to v1.1.0
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
Labels: approved, lgtm, size/XS, ok-to-test

#1629 Add snow kernel config, refactor executables
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/hack/tools/.gitignore
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient_test.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/executables.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/filesystem.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/filesystem_test.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/mocks/executables_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/main.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kernel.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kubernetes.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/mocks/apiclient_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/mocks/filesystem_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/reboot.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/volume.go
Labels: approved, lgtm, size/XXL

#1631 Exclude cloud-init from yum updates on Redhat
  projects/kubernetes-sigs/image-builder/patches/0010-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-RHEL-to-8.6-version-to-avoid-cloud-init-bug.patch
Labels: approved, lgtm, size/M

#1633 change registry.relativeurls default value to true
  projects/goharbor/harbor/helm/patches/0003-change-registry.relativeurls-default-value-to-true.patch
Labels: approved, lgtm, size/S

#1634 Revert "change registry.relativeurls default value to true"
  projects/goharbor/harbor/helm/patches/0003-change-registry.relativeurls-default-value-to-true.patch
Labels: approved, lgtm, size/S

#1635 Remove hardcoded VSphere library name
  projects/kubernetes-sigs/image-builder/packer/ova/vsphere-library.json
Labels: approved, lgtm, size/XS

#1638 Bumping CAPC to v0.4.9-rc2
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1641 Update Prometheus helm charts
  projects/prometheus/prometheus/helm/patches/0007-values-patch.diff
  projects/prometheus/prometheus/helm/sedfile.template
Labels: approved, lgtm, size/S

#1643 Fix bug updating objects in clusterresourceset
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0021-Implement-Reconcile-mode-for-ClusterResourceSet.patch
Labels: approved, lgtm, size/S

#1630 Add build info to eksa-packages binaries.
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
Labels: approved, lgtm, size/S

#1647 Fix snow bootstrap container cloud provider setting
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient_test.go
Labels: approved, lgtm, size/S

#1650 Bump packages to 0.2.22
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1649 Bumping CAPC to v0.4.9-rc3 to include new bug fix
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1653 Add library name to VSphere config
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/types.go
Labels: approved, lgtm, size/XS

#1657 Update snow bootstrap container apiclient with json arg, fix bugs
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient_test.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/config/net.toml
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kernel.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kubernetes.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network_test.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go
Labels: approved, lgtm, size/L

#1658 Update etcd controllers version
  UPSTREAM_PROJECTS.yaml
  projects/aws-containers/hello-eks-anywhere/README.md
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
  projects/aws/image-builder/README.md
  projects/cilium/cilium/README.md
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
  projects/kubernetes-sigs/image-builder/README.md
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/M

#1661 Update etcd version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#1666 Update prometheus helm chart
  projects/prometheus/prometheus/helm/patches/0005-configmap-reload-patch.diff
  projects/prometheus/prometheus/helm/patches/0006-values-patch.diff
  projects/prometheus/prometheus/helm/patches/0007-values-patch.diff
  projects/prometheus/prometheus/helm/schema.json
Labels: approved, lgtm, size/L

#1663 Add optional EBS initialization
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/waiters.go
Labels: approved, lgtm, size/L, ok-to-test

#1670 Cleans go-cache in presubmit for harbor/emissary
  Common.mk
  projects/emissary-ingress/emissary/Makefile
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/M

#1672 Bump CAPAS version to v0.1.11
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/L

#1679 Fixes generated files due to new yq version
  Makefile
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
Labels: approved, lgtm, size/XS

#1685 Bump etcdadm-bootstrap-provider version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
Labels: approved, lgtm, size/S

#1673 Patch locale disparities by explicitly erroring for unexpected locales
  Common.mk
  Makefile
Labels: approved, lgtm, size/S

#1687 Added 1.25 dev 1 for EKS-D
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#1688 Add EKS-D dev build 1.25 support
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-25/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1690 Upgrade snow provider to v0.1.12
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1695 Upgrade snow provider to v0.1.13
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/XS

#1696 Upgrade snow provider to v0.1.14
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS
