Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-02, with the labels that each got.

#386 Add supported release branches file
  Common.mk
  build/lib/run_target_docker.sh
  release/SUPPORTED_RELEASE_BRANCHES
Labels: approved, lgtm, size/XS

#370 Add CloudMonkey and CAPC v0.3.0 to build tools
  UPSTREAM_PROJECTS.yaml
  projects/apache/cloudstack-cloudmonkey/ATTRIBUTION.txt
  projects/apache/cloudstack-cloudmonkey/CHECKSUMS
  projects/apache/cloudstack-cloudmonkey/GIT_TAG
  projects/apache/cloudstack-cloudmonkey/Help.mk
  projects/apache/cloudstack-cloudmonkey/Makefile
  projects/apache/cloudstack-cloudmonkey/README.md
  projects/apache/cloudstack-cloudmonkey/buildspec.yml
  projects/apache/cloudstack-cloudmonkey/expected_artifacts
  projects/aws/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
  projects/aws/cluster-api-provider-cloudstack/Help.mk
  projects/aws/cluster-api-provider-cloudstack/Makefile
  projects/aws/cluster-api-provider-cloudstack/README.md
  projects/aws/cluster-api-provider-cloudstack/build/create_manifests.sh
  projects/aws/cluster-api-provider-cloudstack/buildspec.yml
  projects/aws/cluster-api-provider-cloudstack/docker/linux/Dockerfile
  projects/aws/cluster-api-provider-cloudstack/expected_artifacts
  projects/aws/eks-anywhere-build-tooling/Makefile
Labels: approved, lgtm, size/XXL

#387 Adding shell script to sign files for pipelines
  build/lib/sign_file.sh
Labels: approved, lgtm, size/M

#388 Enabling cmk build for cli-tools
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh
Labels: approved, lgtm, size/XS

#389 add builds for tink-actions
  Common.mk
  Makefile
  projects/tinkerbell/hub/.gitignore
  projects/tinkerbell/hub/CEXEC_ATTRIBUTION.txt
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/GIT_TAG
  projects/tinkerbell/hub/Help.mk
  projects/tinkerbell/hub/IMAGE2DISK_ATTRIBUTION.txt
  projects/tinkerbell/hub/KEXEC_ATTRIBUTION.txt
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/hub/OCI2DISK_ATTRIBUTION.txt
  projects/tinkerbell/hub/README.md
  projects/tinkerbell/hub/WRITEFILE_ATTRIBUTION.txt
  projects/tinkerbell/hub/buildspec.yml
  projects/tinkerbell/hub/docker/linux/Dockerfile
Labels: approved, lgtm, size/XXL

#377 Add build logic for PBNJ project
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  projects/tinkerbell/pbnj/.gitignore
  projects/tinkerbell/pbnj/ATTRIBUTION.txt
  projects/tinkerbell/pbnj/BMCLIB_GIT_COMMIT
  projects/tinkerbell/pbnj/CHECKSUMS
  projects/tinkerbell/pbnj/GIT_TAG
  projects/tinkerbell/pbnj/Help.mk
  projects/tinkerbell/pbnj/IPMITOOL_GIT_TAG
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/pbnj/buildspec.yml
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
  projects/tinkerbell/pbnj/patches/0001-Replace-bmclib-mod-with-local-relative-path-for-LGPL.patch
  projects/tinkerbell/pbnj/patches/bmclib/0001-Remove-goipmi-provider-from-bmclib.patch
Labels: approved, lgtm, size/XXL

#393 Clone ipmitool repo outside docker build stage
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
Labels: approved, lgtm, size/S

#396 Align CLI Tools and diagnostic collector tags with EKS-A CLI
  projects/aws/eks-anywhere-build-tooling/GIT_TAG
  projects/aws/eks-anywhere/GIT_TAG
Labels: approved, lgtm, size/XS

#398 Add badges for newer projects
  UPSTREAM_PROJECTS.yaml
  docs/development/add-new-project.md
  projects/aws/cluster-api-provider-cloudstack/README.md
  projects/aws/eks-anywhere-test/README.md
  projects/cloudflare/cfssl/README.md
  projects/kubernetes-sigs/image-builder/README.md
  projects/replicatedhq/troubleshoot/README.md
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/hub/README.md
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/tink/README.md
Labels: approved, lgtm, size/M

#399 kind: fix high cpu agetty processes
  Common.mk
  projects/kubernetes-sigs/kind/Help.mk
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
Labels: approved, lgtm, size/M

#385 Add 1-22 release branch for cloud-provider-vsphere
  projects/kubernetes/cloud-provider-vsphere/1-22/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-22/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-22/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-22/GOLANG_VERSION
Labels: approved, lgtm, size/XXL

#402 Moving to individual Dockerfile for images
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/hub/docker/linux/cexec/Dockerfile
  projects/tinkerbell/hub/docker/linux/image2disk/Dockerfile
  projects/tinkerbell/hub/docker/linux/kexec/Dockerfile
  projects/tinkerbell/hub/docker/linux/oci2disk/Dockerfile
  projects/tinkerbell/hub/docker/linux/writefile/Dockerfile
Labels: approved, lgtm, size/M

#403 Update Bottlerocket to 1.6.0
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/XS

#404 Update Bottlerocket to 1.6.0
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/XS

#405 Fix ubuntu ami builds to work with new make targets
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ami.yml
Labels: approved, lgtm, size/S

#406 Move kindnetd manifest to versioned folder
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/expected_artifacts
Labels: approved, lgtm, size/S

#407 Create manifest target directory
  projects/kubernetes-sigs/kind/Makefile
Labels: approved, lgtm, size/XS

#401 Add EKS-D 1-22 dev build support
  EKSD_LATEST_RELEASES
  build/lib/eksd_releases.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-ubuntu-raw.yml
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/create-kind-cluster.sh
  projects/kubernetes-sigs/kind/images/base/kubeadm.config.tmpl
  release/SUPPORTED_RELEASE_BRANCHES
Labels: approved, lgtm, size/M

#408 Point to eksd release 2
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#414 Updating GIT_TAG for kube-vip
  UPSTREAM_PROJECTS.yaml
  projects/plunder-app/kube-vip/ATTRIBUTION.txt
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/README.md
Labels: approved, lgtm, size/XL

#416 Revert "Updating GIT_TAG for kube-vip (#414)"
  UPSTREAM_PROJECTS.yaml
  projects/plunder-app/kube-vip/ATTRIBUTION.txt
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/README.md
Labels: approved, lgtm, size/XL

#417 Adding GATHER_LICENSES_TARGETS for ipxe copy target
  projects/tinkerbell/boots/Makefile
Labels: approved, lgtm, size/XS

#415 Extra scripts for Snow provider in ubuntu ami
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/ansible/roles/load_additional_files/defaults/main.yml
  projects/kubernetes-sigs/image-builder/ansible/roles/load_additional_files/tasks/files.yml
  projects/kubernetes-sigs/image-builder/ansible/roles/load_additional_files/tasks/main.yml
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
  projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml
  projects/kubernetes-sigs/image-builder/packer/ami/packer.json
Labels: approved, lgtm, size/L

#411 Bump PBNJ commit, remove go mod patches
  UPSTREAM_PROJECTS.yaml
  build/update-attribution-files/create_pr.sh
  projects/tinkerbell/pbnj/.gitignore
  projects/tinkerbell/pbnj/ATTRIBUTION.txt
  projects/tinkerbell/pbnj/BMCLIB_GIT_COMMIT
  projects/tinkerbell/pbnj/CHECKSUMS
  projects/tinkerbell/pbnj/GIT_TAG
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/pbnj/patches/0001-Replace-bmclib-mod-with-local-relative-path-for-LGPL.patch
  projects/tinkerbell/pbnj/patches/bmclib/0001-Remove-goipmi-provider-from-bmclib.patch
Labels: approved, lgtm, size/XL

#421 Add pbnj files to the image
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#423 Re-order dockerfile copy root to the top
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#424 Add CAPT patch to remove requirement on machine.Spec.Version
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0009-Remove-requirement-for-machine.Spec.Version.patch
Labels: approved, lgtm, size/M

#428 Fix install cmd for pbnj
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#430 pbnj: fix lanplus by adding openssl-dev when building ipmitool
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#425 Add changes to boots...
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/patches/0001-Add-environment-variables-for.patch
Labels: approved, lgtm, size/L

#431 pbnj: use destdir when make installing impitool
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#395 Adding project tinkerbell/hook
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hook/.gitignore
  projects/tinkerbell/hook/BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/Help.mk
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/hook/TINK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/buildspec.yml
  projects/tinkerbell/hook/docker/linux/bootkit/Dockerfile
  projects/tinkerbell/hook/docker/linux/kernel/Dockerfile
  projects/tinkerbell/hook/docker/linux/tink-docker/Dockerfile
  projects/tinkerbell/hook/expected_artifacts
Labels: approved, lgtm, size/XL

#432 Creating ARTIFACTS_PATH before cp
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/expected_artifacts
Labels: approved, lgtm, size/S

#434 Capc v1beta1
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/.gitignore
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
  projects/aws/cluster-api-provider-cloudstack/Makefile
  projects/aws/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#439 Using kernel version 5.10.57
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
Labels: approved, lgtm, size/XS

#444 Rename add-on => package
  projects/aws/eks-anywhere-test/eks-anywhere-test/Chart.yaml
Labels: approved, lgtm, size/XS

#442 Add chrisdoherty4 to OWNERS
  OWNERS
Labels: lgtm, size/XS, ok-to-test, do-not-merge/invalid-owners-file

#445 Fix owners file format
  OWNERS
Labels: approved, lgtm, size/XS

#438 Adding wget and sleep to tink images
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/docker/linux/tink-cli/Dockerfile
  projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
Labels: approved, lgtm, size/M

#437 Accept kube-vip image as input to bootstrap scripts in Snow ami
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
Labels: approved, lgtm, size/S

#447 add patch for support node taints in bottle rocket
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0043-Support-worker-node-taints.patch
Labels: approved, lgtm, size/L

#448 Adding back dependency pcre for wget
  projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
Labels: approved, lgtm, size/XS

#450 Restructure EKS-D latest releases file for easier unmarshalling
  EKSD_LATEST_RELEASES
  build/lib/eksd_releases.sh
  projects/aws/bottlerocket-bootstrap/Makefile
Labels: approved, lgtm, size/S

#454 Bottle rocket control plane taints support
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0044-support-bottle-rocket-control-plane-taints.patch
Labels: approved, lgtm, size/M

#449 Add gwesterfieldjr to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#451 Add tinkerbell stack to tinkerbell project
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/sandbox/.env
  projects/tinkerbell/sandbox/README.md
  projects/tinkerbell/sandbox/docker-compose.yml
  projects/tinkerbell/sandbox/registry/registry_images.txt
  projects/tinkerbell/sandbox/registry/upload.sh
  projects/tinkerbell/sandbox/state/webroot/workflow/.keep
  projects/tinkerbell/sandbox/tls/ca-config.json
  projects/tinkerbell/sandbox/tls/ca-csr.json
  projects/tinkerbell/sandbox/tls/csr.json
  projects/tinkerbell/sandbox/tls/generate.sh
  projects/tinkerbell/sandbox/tls/trust.sh
  projects/tinkerbell/tink/README.md
Labels: approved, lgtm, size/L

#457 Updated EKS-D versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#460 remove duplicated validate-checksums target
  Common.mk
  projects/aws/bottlerocket-bootstrap/Help.mk
  projects/brancz/kube-rbac-proxy/Help.mk
  projects/cloudflare/cfssl/Help.mk
  projects/fluxcd/flux2/Help.mk
  projects/fluxcd/helm-controller/Help.mk
  projects/fluxcd/kustomize-controller/Help.mk
  projects/fluxcd/notification-controller/Help.mk
  projects/fluxcd/source-controller/Help.mk
  projects/helm/helm/Help.mk
  projects/jetstack/cert-manager/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-aws/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Help.mk
  projects/kubernetes-sigs/cluster-api/Help.mk
  projects/kubernetes-sigs/cri-tools/Help.mk
  projects/kubernetes-sigs/etcdadm/Help.mk
  projects/kubernetes-sigs/image-builder/Help.mk
  projects/kubernetes-sigs/kind/Help.mk
  projects/kubernetes-sigs/vsphere-csi-driver/Help.mk
  projects/kubernetes/cloud-provider-vsphere/Help.mk
  projects/mrajashree/etcdadm-bootstrap-provider/Help.mk
  projects/mrajashree/etcdadm-controller/Help.mk
  projects/plunder-app/kube-vip/Help.mk
  projects/rancher/local-path-provisioner/Help.mk
  projects/replicatedhq/troubleshoot/Help.mk
  projects/tinkerbell/boots/Help.mk
  projects/tinkerbell/cluster-api-provider-tinkerbell/Help.mk
  projects/tinkerbell/hegel/Help.mk
  projects/tinkerbell/hook/Help.mk
  projects/tinkerbell/hub/Help.mk
  projects/tinkerbell/pbnj/Help.mk
  projects/tinkerbell/tink/Help.mk
  projects/vmware/govmomi/Help.mk
Labels: approved, lgtm, size/L

#462 release07: update kubernetes and trigger full rebuild
  Common.mk
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#464 Add make target to check for project paths existence
  Makefile
  projects/apache/cloudstack-cloudmonkey/buildspec.yml
  projects/aws/bottlerocket-bootstrap/buildspec.yml
  projects/aws/cluster-api-provider-cloudstack/buildspec.yml
  projects/aws/eks-anywhere-build-tooling/buildspec.yml
  projects/aws/eks-anywhere-test/buildspec.yml
  projects/aws/eks-anywhere/buildspec.yml
  projects/brancz/kube-rbac-proxy/buildspec.yml
  projects/cilium/cilium/buildspec.yml
  projects/cloudflare/cfssl/buildspec.yml
  projects/fluxcd/flux2/buildspec.yml
  projects/fluxcd/helm-controller/buildspec.yml
  projects/fluxcd/kustomize-controller/buildspec.yml
  projects/fluxcd/notification-controller/buildspec.yml
  projects/fluxcd/source-controller/buildspec.yml
  projects/grpc-ecosystem/grpc-health-probe/buildspec.yml
  projects/helm/helm/buildspec.yml
  projects/jetstack/cert-manager/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-aws/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/buildspec.yml
  projects/kubernetes-sigs/cluster-api/buildspec.yml
  projects/kubernetes-sigs/cri-tools/buildspec.yml
  projects/kubernetes-sigs/etcdadm/buildspec.yml
  projects/kubernetes-sigs/kind/buildspec.yml
  projects/kubernetes-sigs/vsphere-csi-driver/buildspec.yml
  projects/kubernetes/cloud-provider-vsphere/buildspec.yml
  projects/mrajashree/etcdadm-bootstrap-provider/buildspec.yml
  projects/mrajashree/etcdadm-controller/buildspec.yml
  projects/plunder-app/kube-vip/buildspec.yml
  projects/rancher/local-path-provisioner/buildspec.yml
  projects/redis/redis/buildspec.yml
  projects/replicatedhq/troubleshoot/buildspec.yml
  projects/tinkerbell/boots/buildspec.yml
  projects/tinkerbell/cluster-api-provider-tinkerbell/buildspec.yml
  projects/tinkerbell/hegel/buildspec.yml
  projects/tinkerbell/hook/buildspec.yml
  projects/tinkerbell/hub/buildspec.yml
  projects/tinkerbell/pbnj/buildspec.yml
  projects/tinkerbell/tink/buildspec.yml
  projects/vmware/govmomi/buildspec.yml
Labels: approved, lgtm, size/M

#465 Add make target to check for project paths existence (#464)
  Makefile
  projects/aws/bottlerocket-bootstrap/buildspec.yml
  projects/aws/eks-anywhere-build-tooling/buildspec.yml
  projects/aws/eks-anywhere-test/buildspec.yml
  projects/aws/eks-anywhere/buildspec.yml
  projects/brancz/kube-rbac-proxy/buildspec.yml
  projects/cilium/cilium/buildspec.yml
  projects/cloudflare/cfssl/buildspec.yml
  projects/fluxcd/flux2/buildspec.yml
  projects/fluxcd/helm-controller/buildspec.yml
  projects/fluxcd/kustomize-controller/buildspec.yml
  projects/fluxcd/notification-controller/buildspec.yml
  projects/fluxcd/source-controller/buildspec.yml
  projects/helm/helm/buildspec.yml
  projects/jetstack/cert-manager/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-aws/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/buildspec.yml
  projects/kubernetes-sigs/cluster-api/buildspec.yml
  projects/kubernetes-sigs/cri-tools/buildspec.yml
  projects/kubernetes-sigs/etcdadm/buildspec.yml
  projects/kubernetes-sigs/kind/buildspec.yml
  projects/kubernetes-sigs/vsphere-csi-driver/buildspec.yml
  projects/kubernetes/cloud-provider-vsphere/buildspec.yml
  projects/mrajashree/etcdadm-bootstrap-provider/buildspec.yml
  projects/mrajashree/etcdadm-controller/buildspec.yml
  projects/plunder-app/kube-vip/buildspec.yml
  projects/rancher/local-path-provisioner/buildspec.yml
  projects/redis/redis/buildspec.yml
  projects/replicatedhq/troubleshoot/buildspec.yml
  projects/tinkerbell/cluster-api-provider-tinkerbell/buildspec.yml
  projects/tinkerbell/hegel/buildspec.yml
  projects/tinkerbell/tink/buildspec.yml
  projects/vmware/govmomi/buildspec.yml
Labels: approved, lgtm, size/M

#461 add capas to support snow infra
  Makefile
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/Help.mk
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/cluster-api-provider-aws-snow/README.md
  projects/aws/cluster-api-provider-aws-snow/build/create_manifests.sh
  projects/aws/cluster-api-provider-aws-snow/buildspec.yml
  projects/aws/cluster-api-provider-aws-snow/expected_artifacts
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
  projects/aws/cluster-api-provider-aws-snow/manifests/metadata.yaml
Labels: approved, lgtm, size/XXL

#472 Add common buildspec for all projects
  buildspec.yml
Labels: approved, lgtm, size/S

#474 Revert "remove duplicated validate-checksums target (#460)"
  Common.mk
  projects/aws/bottlerocket-bootstrap/Help.mk
  projects/aws/cluster-api-provider-aws-snow/Help.mk
  projects/brancz/kube-rbac-proxy/Help.mk
  projects/cloudflare/cfssl/Help.mk
  projects/fluxcd/flux2/Help.mk
  projects/fluxcd/helm-controller/Help.mk
  projects/fluxcd/kustomize-controller/Help.mk
  projects/fluxcd/notification-controller/Help.mk
  projects/fluxcd/source-controller/Help.mk
  projects/helm/helm/Help.mk
  projects/jetstack/cert-manager/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-aws/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Help.mk
  projects/kubernetes-sigs/cluster-api/Help.mk
  projects/kubernetes-sigs/cri-tools/Help.mk
  projects/kubernetes-sigs/etcdadm/Help.mk
  projects/kubernetes-sigs/image-builder/Help.mk
  projects/kubernetes-sigs/kind/Help.mk
  projects/kubernetes-sigs/vsphere-csi-driver/Help.mk
  projects/kubernetes/cloud-provider-vsphere/Help.mk
  projects/mrajashree/etcdadm-bootstrap-provider/Help.mk
  projects/mrajashree/etcdadm-controller/Help.mk
  projects/plunder-app/kube-vip/Help.mk
  projects/rancher/local-path-provisioner/Help.mk
  projects/replicatedhq/troubleshoot/Help.mk
  projects/tinkerbell/boots/Help.mk
  projects/tinkerbell/cluster-api-provider-tinkerbell/Help.mk
  projects/tinkerbell/hegel/Help.mk
  projects/tinkerbell/hook/Help.mk
  projects/tinkerbell/hub/Help.mk
  projects/tinkerbell/pbnj/Help.mk
  projects/tinkerbell/tink/Help.mk
  projects/vmware/govmomi/Help.mk
Labels: approved, lgtm, size/L

#475 Add image pull secrets to CAPAS controller deployment
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/XS

#476 Make snow controller image configurable
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/XS

#484 Remove ECR public env var from buildspecs
  projects/aws/eks-anywhere-test/buildspec.yml
  projects/jetstack/cert-manager/buildspec.yml
  projects/redis/redis/buildspec.yml
Labels: approved, lgtm, size/S

#483 Remove individual project buildspecs
  projects/apache/cloudstack-cloudmonkey/buildspec.yml
  projects/aws/bottlerocket-bootstrap/buildspec.yml
  projects/aws/cluster-api-provider-aws-snow/buildspec.yml
  projects/aws/cluster-api-provider-cloudstack/buildspec.yml
  projects/aws/eks-anywhere-build-tooling/buildspec.yml
  projects/aws/eks-anywhere-test/buildspec.yml
  projects/aws/eks-anywhere/buildspec.yml
  projects/brancz/kube-rbac-proxy/buildspec.yml
  projects/cilium/cilium/buildspec.yml
  projects/cloudflare/cfssl/buildspec.yml
  projects/fluxcd/flux2/buildspec.yml
  projects/fluxcd/helm-controller/buildspec.yml
  projects/fluxcd/kustomize-controller/buildspec.yml
  projects/fluxcd/notification-controller/buildspec.yml
  projects/fluxcd/source-controller/buildspec.yml
  projects/grpc-ecosystem/grpc-health-probe/buildspec.yml
  projects/helm/helm/buildspec.yml
  projects/jetstack/cert-manager/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-aws/buildspec.yml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/buildspec.yml
  projects/kubernetes-sigs/cluster-api/buildspec.yml
  projects/kubernetes-sigs/cri-tools/buildspec.yml
  projects/kubernetes-sigs/etcdadm/buildspec.yml
  projects/kubernetes-sigs/kind/buildspec.yml
  projects/kubernetes-sigs/vsphere-csi-driver/buildspec.yml
  projects/kubernetes/cloud-provider-vsphere/buildspec.yml
  projects/mrajashree/etcdadm-bootstrap-provider/buildspec.yml
  projects/mrajashree/etcdadm-controller/buildspec.yml
  projects/plunder-app/kube-vip/buildspec.yml
  projects/rancher/local-path-provisioner/buildspec.yml
  projects/redis/redis/buildspec.yml
  projects/replicatedhq/troubleshoot/buildspec.yml
  projects/tinkerbell/boots/buildspec.yml
  projects/tinkerbell/cluster-api-provider-tinkerbell/buildspec.yml
  projects/tinkerbell/hegel/buildspec.yml
  projects/tinkerbell/hook/buildspec.yml
  projects/tinkerbell/hub/buildspec.yml
  projects/tinkerbell/pbnj/buildspec.yml
  projects/tinkerbell/tink/buildspec.yml
  projects/vmware/govmomi/buildspec.yml
Labels: approved, lgtm, size/L

#490 remove openssl install, it's already on the base image for codebuild
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#495 Add fake snow GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#486 * Remove local registry and nginx from tinkerbell stack
  projects/tinkerbell/sandbox/.env
  projects/tinkerbell/sandbox/docker-compose.yml
  projects/tinkerbell/sandbox/registry/registry_images.txt
  projects/tinkerbell/sandbox/registry/upload.sh
  projects/tinkerbell/sandbox/state/webroot/workflow/.keep
Labels: approved, lgtm, size/L

#497 Convert image_shasum.sh to use skopeo
  build/lib/image_shasum.sh
Labels: approved, lgtm, size/S
