Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-05, with the labels that each got.

#746 cli-tools: remove clusterawsadm
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh
Labels: approved, lgtm, size/XS

#742 Harbor upgrade and security patch
  UPSTREAM_PROJECTS.yaml
  projects/goharbor/harbor/ATTRIBUTION.txt
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/GIT_TAG
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/README.md
  projects/goharbor/harbor/docker/linux/harbor-db/Dockerfile
  projects/goharbor/harbor/docker/linux/harbor-portal/Dockerfile
  projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch
  projects/goharbor/harbor/helm/requires-config.yaml
  projects/goharbor/harbor/helm/sedfile.template
  projects/goharbor/harbor/patches/0001-remove-base-image-check-for-cert-installation.patch
  projects/goharbor/harbor/patches/0001-tailor-cert-installation-script-for-al2.patch
  projects/goharbor/harbor/patches/0002-remove-cert-soft-links-in-al2.patch
  projects/goharbor/harbor/patches/0003-security-patch.patch
Labels: approved, lgtm, size/XXL

#747 Specify commit for tink-cli binary instead of using latest
  build/lib/fetch_binaries.sh
  projects/aws/eks-anywhere-build-tooling/Makefile
Labels: approved, lgtm, size/XS

#749 Use proper git tag for overriden artifacts
  build/lib/common.sh
  build/lib/fetch_binaries.sh
Labels: approved, lgtm, size/S

#750 Update etcdadm-controller tag to skip periodic healthcheck if cluster is paused
  UPSTREAM_PROJECTS.yaml
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
  projects/mrajashree/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#745 Patch to change hardware, template, workflow CRDs to namespaced scope
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0015-Make-hardware-template-workflow-CRDs-namespace-scope.patch
Labels: approved, lgtm, size/L

#757 update helm chart patch
  projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch
  projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch
Labels: approved, lgtm, size/XXL

#715 create admin ova image for eka-a baremetal lab
  .gitignore
  projects/aws/eks-a-admin-image/Help.mk
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/README.md
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
  projects/aws/eks-a-admin-image/build/get_kind_url.sh
  projects/aws/eks-a-admin-image/build/get_kubectl_url.sh
  projects/aws/eks-a-admin-image/common.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-ci.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
  projects/aws/eks-a-admin-image/ova/linux/ubuntu/data/meta-data
  projects/aws/eks-a-admin-image/ova/linux/ubuntu/data/user-data
  projects/aws/eks-a-admin-image/ova/linux/ubuntu/vsphere.ubuntu.pkrvars.hcl
  projects/aws/eks-a-admin-image/provisioners/cleanup.sh
  projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh
  projects/aws/eks-a-admin-image/provisioners/install_awscli.sh
  projects/aws/eks-a-admin-image/provisioners/install_docker.sh
  projects/aws/eks-a-admin-image/provisioners/install_eksa.sh
  projects/aws/eks-a-admin-image/provisioners/install_golang.sh
  projects/aws/eks-a-admin-image/provisioners/install_kind.sh
  projects/aws/eks-a-admin-image/provisioners/install_kubectl.sh
  projects/aws/eks-a-admin-image/provisioners/install_ssm_agent.sh
  projects/aws/eks-a-admin-image/provisioners/test/download_eksa_artifacts.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_awscli.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_docker.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_eksa.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_golang.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_kind.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_kubectl.sh
  projects/aws/eks-a-admin-image/provisioners/test/install_ssm_agent.sh
  projects/aws/eks-a-admin-image/provisioners/upgrade_linux.sh
  projects/aws/eks-a-snow-admin-image/Makefile
  projects/aws/eks-a-snow-admin-image/README.md
Labels: approved, lgtm, size/XXL

#754 Generate tink manifest
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/build/create_manifests.sh
  projects/tinkerbell/tink/expected_artifacts
  projects/tinkerbell/tink/patches/0001-Remove-.ONESHELL-from-rules.mk.patch
Labels: approved, lgtm, size/M

#760 Add 'tinkerbell/tink' in the image URI for tink manifest
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/build/create_manifests.sh
Labels: approved, lgtm, size/S

#762 Build eks-anywhere-packages and include it in releases
  release/staging-build.yml
Labels: approved, lgtm, size/S

#764 add namespace to all nginx service types
  projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch
Labels: approved, lgtm, size/S

#766 update harbor badge and sourceRegistry
  projects/goharbor/harbor/README.md
  projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch
Labels: approved, lgtm, size/XS

#768 Update packages to v0.1.7
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#767 Add target to build latest snow raw admin image
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/build/get_latest_eksa_version_by_date.sh
  projects/aws/eks-a-admin-image/common.pkr.hcl
Labels: approved, lgtm, size/M

#769 Adds new target to create ecr repos
  Common.mk
  build/lib/buildkit.sh
Labels: approved, lgtm, size/S

#758 🐧 Add torvalds/linux to projects for building bootconfig
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  projects/torvalds/linux/.gitignore
  projects/torvalds/linux/ATTRIBUTION.txt
  projects/torvalds/linux/CHECKSUMS
  projects/torvalds/linux/GIT_TAG
  projects/torvalds/linux/Help.mk
  projects/torvalds/linux/Makefile
  projects/torvalds/linux/README.md
  projects/torvalds/linux/expected_artifacts
Labels: approved, lgtm, size/XXL

#770 Add retries to EC2 instance creation
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/S

#774 Update to packages v0.1.8
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#771 Add junshun to owners
  OWNERS
Labels: approved, lgtm, size/XS

#772 Select Availability zone randomly for EC2 instance creation
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#777 bumping tag
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#776 Use the availability zone that the subnet exists in
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/S

#784 Bumping CAPC to v0.4.3
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
  projects/aws/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#785 Patch WriteFile to support bootconfig
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0001-Add-Bootconfig-support-to-WriteFile-action.patch
Labels: approved, lgtm, size/L

#790 Use rsync to exclude git files in helm copy
  build/lib/helm_copy.sh
Labels: approved, lgtm, size/XS

#791 Support creating ECR public repos too.
  Common.mk
Labels: approved, lgtm, size/XS

#792 Remove extraneous white space
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/XS

#783 Docs: docker registry login
  docs/development/building-locally.md
  docs/development/docker-auth.md
Labels: approved, lgtm, size/L

#798 Bump up hegel git tag to latest
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/Makefile
Labels: approved, lgtm, size/XS

#799 Bump up tink GIT_TAG to latest commit
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
Labels: approved, lgtm, size/S

#802 Update cilium to 1.10.8
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
  projects/cilium/cilium/manifests/cilium-eksa.yaml
Labels: approved, lgtm, size/S

#800 Bump up boots to the latest commit and update Makefile
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/boots/ipxe/ipxe.efi
  projects/tinkerbell/boots/ipxe/snp-hua.efi
  projects/tinkerbell/boots/ipxe/snp-nolacp.efi
  projects/tinkerbell/boots/ipxe/undionly.kpxe
  projects/tinkerbell/boots/patches/0001-Add-environment-variables-for.patch
Labels: approved, lgtm, size/L

#805 Use consistent sorting between macOS/Linux
  build/lib/validate_artifacts.sh
Labels: lgtm, size/M

#808 Revert "Update cilium to 1.10.8"
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
  projects/cilium/cilium/manifests/cilium-eksa.yaml
Labels: approved, lgtm, size/S

#809 fix presubmit packer validation
  projects/aws/eks-a-admin-image/common.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-ci.pkr.hcl
Labels: approved, lgtm, size/S

#803 Update CAPT GIT_TAG and go version
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-PBNJ-integration-with-CAPT.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0002-Modifying-workflow-action-to-image2disk.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0003-Add-templateOverride-for-default-CAPT-template.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0004-Modifying-BMC-CRD-to-read-from-Secret.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0005-Adding-PBNJ-PowerAction-to-BMC-controller.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0006-Adding-PBNJ-BootDevice-to-BMC-CRD-and-client.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0007-Adding-BmcRef-to-hardware-and-PowerOn-machine.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0008-Deprovision-hardware-after-hardware-release.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0009-Remove-requirement-for-machine.Spec.Version.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0010-Adding-mutex-to-lock-hardware-selection.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0011-Temporary-comment-error-return.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0012-Update-tinkerbell-hardware-state-through-CAPT.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0013-Updating-PBNJ-commit-version.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0015-Make-hardware-template-workflow-CRDs-namespace-scope.patch
Labels: approved, lgtm, size/XXL

#812 Add EKS-D 1-23 dev build support
  EKSD_LATEST_RELEASES
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-ubuntu-ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-ubuntu-raw.yml
  projects/kubernetes/cloud-provider-vsphere/1-23/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-23/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-23/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/README.md
  release/SUPPORTED_RELEASE_BRANCHES
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#794 Create helm chart repos
  Common.mk
Labels: approved, lgtm, size/S

#815 Bump-up CAPT version
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
Labels: approved, lgtm, size/XS

#816 cilium: Upgrade to 1.10.11-eksa2
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/XS

#818 bumping to capc v0.4.5-rc1, which fixes several identified bugs from v0.4.4
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
  projects/aws/cluster-api-provider-cloudstack/Makefile
  projects/aws/cluster-api-provider-cloudstack/README.md
  projects/aws/cluster-api-provider-cloudstack/build/create_manifests.sh
Labels: approved, lgtm, size/S

#817 Skip checksum validation for bootconfig
  Common.mk
  projects/torvalds/linux/CHECKSUMS
  projects/torvalds/linux/Makefile
Labels: approved, lgtm, size/XS

#821 Update EKSD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#824 Bumping capc to latest version which fixes some bugs
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
Labels: approved, lgtm, size/XS

#823 Supprt custom tar file prefixes when fetching dep binaries
  Common.mk
  build/lib/common.sh
  build/lib/fetch_binaries.sh
Labels: approved, lgtm, size/S

#827 Bumping capc to latest version which fixes some bugs (#824)
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
  projects/aws/cluster-api-provider-cloudstack/Makefile
  projects/aws/cluster-api-provider-cloudstack/README.md
  projects/aws/cluster-api-provider-cloudstack/build/create_manifests.sh
Labels: approved, lgtm, size/S

#833 retries docker pull and use builder base tag
  Common.mk
  Makefile
  build/lib/setup.sh
Labels: approved, lgtm, size/S

#835 fix builder image for cgo in codebuild
  Common.mk
Labels: approved, lgtm, size/XS

#830 Package BootConfig with Writefile action
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/Help.mk
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/hub/docker/linux/writefile/Dockerfile
  projects/tinkerbell/hub/patches/0001-Add-Bootconfig-support-to-WriteFile-action.patch
Labels: approved, lgtm, size/S

#837 Patch writefile to pull user-data from hegel & write to disk
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0001-Get-user-data-from-Hegel-and-write-to-disk.patch
Labels: approved, lgtm, size/M

#844 Make glibc base image for writefile
  projects/tinkerbell/hub/Makefile
Labels: approved, lgtm, size/XS

#840 Read local apiserver health check port from init/join yaml
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils_test.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/parsers.go
Labels: approved, lgtm, size/L, ok-to-test

#825 Updates eks-d release
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#847 Bumped dev release number for 1.23
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#846 Tinkerbell rufio build
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/Help.mk
  projects/tinkerbell/rufio/.gitignore
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/Help.mk
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/README.md
  projects/tinkerbell/rufio/build/create_manifests.sh
  projects/tinkerbell/rufio/docker/linux/Dockerfile
  projects/tinkerbell/rufio/expected_artifacts
Labels: approved, lgtm, size/XXL

#843 Support compressed user-data for Snow
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh
Labels: approved, lgtm, size/M, ok-to-test

#851 Revert "Read local apiserver health check port from init/join yaml"
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils_test.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/parsers.go
Labels: approved, lgtm, size/L

#856 Helm chart to install tinkerbell
  projects/tinkerbell/helm-chart/.helmignore
  projects/tinkerbell/helm-chart/Chart.yaml
  projects/tinkerbell/helm-chart/templates/boots-deployment.yaml
  projects/tinkerbell/helm-chart/templates/boots-role.yaml
  projects/tinkerbell/helm-chart/templates/boots-rolebinding.yaml
  projects/tinkerbell/helm-chart/templates/boots-service-account.yaml
  projects/tinkerbell/helm-chart/templates/hardware-crd.yaml
  projects/tinkerbell/helm-chart/templates/hegel-deployment.yaml
  projects/tinkerbell/helm-chart/templates/hegel-role.yaml
  projects/tinkerbell/helm-chart/templates/hegel-rolebinding.yaml
  projects/tinkerbell/helm-chart/templates/hegel-service-account.yaml
  projects/tinkerbell/helm-chart/templates/namespace.yaml
  projects/tinkerbell/helm-chart/templates/template-crd.yaml
  projects/tinkerbell/helm-chart/templates/tink-controller-cluster-role-binding.yaml
  projects/tinkerbell/helm-chart/templates/tink-controller-cluster-role.yaml
  projects/tinkerbell/helm-chart/templates/tink-controller-deployment.yaml
  projects/tinkerbell/helm-chart/templates/tink-controller-service-account.yaml
  projects/tinkerbell/helm-chart/templates/tink-leader-election-role.yaml
  projects/tinkerbell/helm-chart/templates/tink-leader-election-rolebinding.yaml
  projects/tinkerbell/helm-chart/templates/tink-server-deployment.yaml
  projects/tinkerbell/helm-chart/templates/tink-server-role.yaml
  projects/tinkerbell/helm-chart/templates/tink-server-rolebinding.yaml
  projects/tinkerbell/helm-chart/templates/tink-server-service-account.yaml
  projects/tinkerbell/helm-chart/templates/workflow-crd.yaml
  projects/tinkerbell/helm-chart/values.yaml
Labels: approved, lgtm, size/XXL

#861 Bump up boots to latest
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
Labels: approved, lgtm, size/XS

#855 Read local apiserver health check endpoint from apiserver manifest
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
Labels: approved, lgtm, size/M, ok-to-test
