Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-03, with the labels that each got.

#496 Bottlerocket control container uri support
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0045-Support-configuring-bottlerocket-control-container-uri.patch
Labels: approved, lgtm, size/XXL, ok-to-test

#494 Add eks-anywhere-packages
  projects/aws/eks-anywhere-packages/.gitignore
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Help.mk
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/eks-anywhere-packages/docker/linux/Dockerfile
Labels: approved, lgtm, size/XXL

#489 This patch makes registry certificate hosting URL and tink-worker image
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/patches/0001-Add-environment-variables-for.patch
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0001-Make-registry-certificate-hosting-URL-and-tink-worke.patch
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/patches/0002-Make-registry-credentials-command-line-parameters-op.patch
Labels: approved, lgtm, size/L

#504 Add etcdadm patch to accept multiple endpoints
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/patches/0012-Allow-using-multiple-endpoints-for-etcd-client.patch
Labels: approved, lgtm, size/L

#507 Patch kube-vip to use hostname for apiserver calls
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
Labels: approved, lgtm, size/M

#508 eks-d: update to dev release 5 of 1.22
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#509 Revert "Patch kube-vip to use hostname for apiserver calls"
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
Labels: approved, lgtm, size/M

#510 kind: fix kubeadm version validation
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm, size/XS

#511 Update CAPAS infrastructure components
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/M

#512 Updating PBNJ git tag to latest on main
  projects/tinkerbell/pbnj/ATTRIBUTION.txt
  projects/tinkerbell/pbnj/CHECKSUMS
  projects/tinkerbell/pbnj/GIT_TAG
Labels: approved, lgtm, size/XS

#514 Update default registry for Harbor helm chart
  projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch
Labels: approved, lgtm, size/XS

#513 Improve bootstrap scripts for Snow AMI
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
Labels: approved, lgtm, size/M

#506 Cert manager ctl
  projects/jetstack/cert-manager/CHECKSUMS
  projects/jetstack/cert-manager/Help.mk
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/docker/linux/cert-manager-ctl/Dockerfile
  projects/jetstack/cert-manager/helm/patches/0004-Add-registry-and-digest-for-ctl.patch
  projects/jetstack/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/M

#515 Increase default number of retries during join
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/patches/0013-Increase-wait-backoff-retries-during-join.patch
Labels: approved, lgtm, size/S

#518 cilium: fix manifest generationt to use proper tag
  Makefile
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/HELM_REPO_VERSION
  projects/cilium/cilium/Help.mk
  projects/cilium/cilium/Makefile
  projects/cilium/cilium/build/create_manifests.sh
  projects/cilium/cilium/manifests/cilium-eksa.yaml
Labels: approved, lgtm, size/M

#520 eksd: bump to 1.22 dev release 6
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#521 capi: patch to support core dns 1.8.7 from 1.22
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0046-update-coredns-corefile-migration-to-support-1.8.7.patch
Labels: approved, lgtm, size/M

#524 Pull CAPAS image from public repo
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/XS

#525 Increase eks-d AMI sice to 25GB
  projects/kubernetes-sigs/image-builder/packer/ami/packer.json
Labels: approved, lgtm, size/XS

#527 Local RHEL Image Builder for Qemu
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/build/build_qemu_rhel_local.sh
Labels: approved, lgtm, size/M

#528 Update etcdadm-controller tag to v1.0.0-rc5
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/XS

#523 Fix build pipeline readme
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/XS

#532 Update etcdadm-controller tag to rc6
  projects/mrajashree/etcdadm-controller/ATTRIBUTION.txt
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/XS

#536 Add 1.22 builds for Bottlerocket
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/XS

#540 snow: add image build to push to our ecr
  config/docker-ecr-config.json
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/cluster-api-provider-aws-snow/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#541 Fix CAPAS manager image name
  projects/aws/cluster-api-provider-aws-snow/Makefile
Labels: approved, lgtm, size/XS

#533 Add support for loading userdata from secretsmanager
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/go.sum
  projects/aws/bottlerocket-bootstrap/pkg/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/service/secretsmanager.go
  projects/aws/bottlerocket-bootstrap/pkg/service/secretsmanager_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata_test.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/utils.go
Labels: approved, lgtm, size/L, ok-to-test

#543 CAPT patches mutex lock and error return
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0010-Adding-mutex-to-lock-hardware-selection.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0011-Temporary-comment-error-return.patch
Labels: approved, lgtm, size/M

#546 update Cilium git tag to test 1.11 with kernel version 4.14
  projects/cilium/cilium/GIT_TAG
Labels: approved, lgtm, size/XS

#545 Upgrading capc to v0.4.0
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
  projects/aws/cluster-api-provider-cloudstack/GIT_TAG
  projects/aws/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#547 Update snow metadata
  projects/aws/cluster-api-provider-aws-snow/manifests/metadata.yaml
Labels: approved, lgtm, size/S

#440 Add package requirements to helm chart
  Common.mk
  build/lib/helm_replace.sh
  build/lib/helm_require.sh
  build/lib/image_shasum.sh
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/_helpers.tpl
  projects/aws/eks-anywhere-test/eks-anywhere-test/values.yaml
  projects/aws/eks-anywhere-test/helm/requires-config.yaml
  projects/aws/eks-anywhere-test/helm/sedfile.template
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/helm/patches/0002-Allow-modification-of-image-tags.patch
  projects/fluxcd/flux2/helm/sedfile.template
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch
  projects/goharbor/harbor/helm/sedfile.template
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/helm/patches/0003-Activate-digests-with-templates.patch
  projects/jetstack/cert-manager/helm/patches/0004-Add-registry-and-digest-for-ctl.patch
  projects/jetstack/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/L

#542 Export EKS-D AMI to raw format after build
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/export-ami-to-s3.sh
  projects/kubernetes-sigs/image-builder/packer/ami/packer.json
Labels: approved, lgtm, size/M

#552 Make latest raw ami in s3 public
  projects/kubernetes-sigs/image-builder/build/export-ami-to-s3.sh
Labels: approved, lgtm, size/XS

#553 Update etcdadm controller tags
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/S

#555 Update upstream CAPAS image registry repo name
  projects/aws/cluster-api-provider-aws-snow/Makefile
Labels: approved, lgtm, size/XS

#522 kind: set os-release and include etcd + coredns
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/M

#569 Revert "kind: set os-release and include etcd + coredns"
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/M

#568 eks-d: update to latest dev releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#573 capv + cpi: add user agents to vcenter api calls
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0003-set-user-agent-for-vsphere-api-calls.patch
  projects/kubernetes/cloud-provider-vsphere/1-20/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-20/patches/0001-set-user-agent-for-vsphere-api-calls.patch
  projects/kubernetes/cloud-provider-vsphere/1-21/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-21/patches/0001-set-user-agent-for-vsphere-api-calls.patch
  projects/kubernetes/cloud-provider-vsphere/1-22/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-22/patches/0001-set-user-agent-for-vsphere-api-calls.patch
Labels: approved, lgtm, size/L

#574 Fix local image building for RHEL
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_qemu_rhel_local.sh
Labels: approved, lgtm, size/XS

#575 kind: make sure etcd and coredns are included
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/M

#579 Added logging to Snow AMI bootstrap scripts.
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh
  projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#581 Update CAPAS image
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#584 Updated EKS-D prod releases and 1-22 dev
  EKSD_LATEST_RELEASES
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/S

#583 Fix space issues in harbor presubmit
  build/lib/buildkit.sh
Labels: approved, lgtm, size/XS

#586 Add EKS Anywhere Packages helm build
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/helm/files.txt
  projects/aws/eks-anywhere-packages/helm/sedfile.template
Labels: approved, lgtm, size/S

#587 Align CLI Tools and diagnostic collector tags with EKS-A CLI
  UPSTREAM_PROJECTS.yaml
  projects/aws/cluster-api-provider-cloudstack/README.md
  projects/aws/eks-anywhere-build-tooling/GIT_TAG
  projects/aws/eks-anywhere/GIT_TAG
  projects/mrajashree/etcdadm-bootstrap-provider/README.md
  projects/mrajashree/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#588 Fix eks-anywhere-packages checksums
  projects/aws/eks-anywhere-packages/CHECKSUMS
Labels: approved, lgtm, size/XS

#582 Add eks-anywhere-packages to all projects
  Makefile
Labels: approved, lgtm, size/XS

#585 Change helm charts to use semantic versioning
  build/lib/helm_push.sh
  build/lib/helm_require.sh
Labels: approved, lgtm, size/S

#589 Modify staging release buildspec to support batch builds
  release/staging-build.yml
Labels: approved, lgtm, size/L

#591 Update CAPAS image and manifests
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/S

#593 Update latest to 1-22
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#595 Add helm patch to allow push to insecure OCI registry
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/patches/0001-Push-to-OCI-insecure-registry.patch
Labels: approved, lgtm, size/L

#590 Adding package promotion scripts (squashed)
  Makefile
  build/lib/buildspecs/promotion-buildspec.yml
  build/lib/helm_promotion.sh
  projects/aws/eks-anywhere-test/GIT_TAG
  projects/aws/eks-anywhere-test/Makefile
Labels: approved, lgtm, size/M

#597 Patch for adding insecure registry flag for pull, push and install
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/patches/0001-Insecure-flag-for-oci-push-pull-install.patch
Labels: approved, lgtm, size/M

#412 Add K8s 1.22 specific version information and build statuses to README
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes/cloud-provider-vsphere/README.md
Labels: approved, lgtm, size/XS

#601 Build tink project as prequisite to CLI tools
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#603 make flux2 dependent on source_controller build
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#599 Tweak helm chart semantic version generation.
  build/lib/helm_push.sh
  build/lib/helm_require.sh
  projects/aws/eks-anywhere-test/eks-anywhere-test/Chart.yaml
Labels: approved, lgtm, size/S

#604 Add source registry
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/_helpers.tpl
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/deployment.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/values.yaml
  projects/aws/eks-anywhere-test/helm/requires-config.yaml
Labels: approved, lgtm, size/S

#605 Disable cert-manager and flux helm builds
  projects/fluxcd/flux2/Makefile
  projects/jetstack/cert-manager/Makefile
Labels: approved, lgtm, size/S

#534 Patch kube-vip to use hostname for apiserver calls
  UPSTREAM_PROJECTS.yaml
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/README.md
  projects/plunder-app/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
Labels: approved, lgtm, size/M

#611 Updated EKS-D dev for 1.22-10
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#608 Add requires config for packages
  projects/aws/eks-anywhere-packages/helm/requires-config.yaml
Labels: approved, lgtm, size/XS

#609 Add requires config for harbor
  projects/goharbor/harbor/helm/requires-config.yaml
Labels: approved, lgtm, size/XS

#613 Fix pipeline builds
  projects/aws/eks-anywhere-packages/helm/sedfile.template
  projects/goharbor/harbor/helm/sedfile.template
Labels: approved, lgtm, size/XS

#616 Updated EKS-D prod for 1.22-4
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#618 Update EKSD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#617 Use mac as dhcp-identifier in netplan config file
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh
Labels: approved, lgtm, size/XS, needs-ok-to-test

#619 Build Ubuntu raw images with EFI support, add RHEL 8 raw builds
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
Labels: approved, lgtm, size/L

#620 Update eksa-packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/helm/patches/0001-Allow-setting-of-image-tags.patch
Labels: approved, lgtm, size/M

#624 Kick v0.1.4 build
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#627 Add CAPT patch to update hardware state
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0012-Update-tinkerbell-hardware-state-through-CAPT.patch
Labels: approved, lgtm, size/L

#622 Revert order swapping of Ubuntu partitions
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
Labels: approved, lgtm, size/M

#628 Remove RHEL builds in CI
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#629 Install reboot in tink-docker
  projects/tinkerbell/hook/docker/linux/tink-docker/Dockerfile
Labels: approved, lgtm, size/XS

#632 Adding busybox reboot to tink-docker
  projects/tinkerbell/hook/docker/linux/tink-docker/Dockerfile
Labels: approved, lgtm, size/S

#631 Fix the pipeline build for charts
  build/lib/helm_require.sh
Labels: approved, lgtm, size/S
