Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-09, with the labels that each got.

#1248 Run bottlerocket targets if the version exists in BR releases
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/S

#1251 Add ADOT helm chart json schema
  projects/aws-observability/aws-otel-collector/helm/schema.json
Labels: approved, lgtm, size/XL

#1252 Update git tag for curated packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1253 Added a patch of allowing insecure pull from local registry
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0003-Added-support-for-allowing-image-pull-from-local-reg.patch
Labels: approved, lgtm, size/M

#1257 bumping hello-eks-anywhere test replication
  projects/aws-containers/hello-eks-anywhere/conf/hello.sh
Labels: approved, lgtm, size/XS

#1254 Update image-builder to v0.1.12
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
Labels: approved, lgtm, size/L

#1244 Add EKS-D 1.24 dev build support
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes/cloud-provider-vsphere/1-24/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-24/GOLANG_VERSION
  release/SUPPORTED_RELEASE_BRANCHES
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1239 Debundle helm make targets with other image make targets for build and release
  Common.mk
Labels: approved, lgtm, size/XS

#1261 Updating Image builder to latest commit
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-crictl-validation-from-input-checksum.patch
Labels: approved, lgtm, size/L

#1260 Update eks-a packages git tag
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1265 Emissary has no required configuration
  projects/emissary-ingress/emissary/helm/schema.json
Labels: approved, lgtm, size/XS

#1266 Update EKD-S
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1270 Update git tag for curated packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1271 Update package tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1272 Update EKS-D versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1275 Cherry pick image builder changes
  Common.mk
  UPSTREAM_PROJECTS.yaml
  build/lib/eksa_releases.sh
  projects/aws/image-builder/.gitignore
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-crictl-validation-from-input-checksum.patch
Labels: approved, lgtm, size/XL

#1277 Update bottlerocket to v1.9.2
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1279 image-builder: update checksum for Bottlerocket's new root.json
  projects/kubernetes-sigs/image-builder/bottlerocket-root-json-checksum
Labels: approved, lgtm, size/XS, ok-to-test

#1276 Add notes about CRDs in packages
  docs/development/update-helm-charts.md
Labels: approved, lgtm, size/XS

#1268 Build Cluster Autoscaler
  Common.mk
  UPSTREAM_PROJECTS.yaml
  build/lib/generate_staging_buildspec.sh
  build/lib/run_target_docker.sh
  docs/development/add-new-project.md
  projects/kubernetes/autoscaler/.gitignore
  projects/kubernetes/autoscaler/1-21/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-21/CHECKSUMS
  projects/kubernetes/autoscaler/1-21/GIT_TAG
  projects/kubernetes/autoscaler/1-21/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-21/LICENSES
  projects/kubernetes/autoscaler/1-21/patches/0001-Add-prometheus-implicit-testing-dependency.patch
  projects/kubernetes/autoscaler/1-22/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-22/CHECKSUMS
  projects/kubernetes/autoscaler/1-22/GIT_TAG
  projects/kubernetes/autoscaler/1-22/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-22/LICENSES
  projects/kubernetes/autoscaler/1-23/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-23/CHECKSUMS
  projects/kubernetes/autoscaler/1-23/GIT_TAG
  projects/kubernetes/autoscaler/1-23/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-23/LICENSES
  projects/kubernetes/autoscaler/1-24/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-24/CHECKSUMS
  projects/kubernetes/autoscaler/1-24/GIT_TAG
  projects/kubernetes/autoscaler/1-24/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-24/LICENSES
  projects/kubernetes/autoscaler/1-24/patches/0001-Replace-cloud-provider-azure.patch
  projects/kubernetes/autoscaler/1-24/patches/0002-Replace-broken-Go-module-for-Distribution-project-re.patch
  projects/kubernetes/autoscaler/Help.mk
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/autoscaler/README.md
  projects/kubernetes/autoscaler/docker/linux/Dockerfile
Labels: approved, lgtm, size/XXL

#1283 fix cross account issue
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/patches/0004-fix-cross-account-issue-for-AWS-ECR.patch
Labels: approved, lgtm, size/M

#1285 Update packages tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1284 Add 24 as a supported release branch
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/builder/utils_test.go
Labels: approved, lgtm, size/L

#1290 Separate HELM_TAG from IMAGE_TAG
  Common.mk
  build/lib/helm_push.sh
  build/lib/helm_require.sh
Labels: approved, lgtm, size/S

#1296 Fix git commands on CI
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/S

#1297 Improve Image Builder Makefile to support multiple targets
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/S

#1216 Bumps cilium to 1.11.8
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#1305 Patch cluster-api for empty taints issue
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Fix-the-issue-of-passing-taints-to-kubeadm.patch
Labels: approved, lgtm, size/L

#1288 Bump CAPAS version to 0.1.7
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1307 Changes for dev package build
  build/lib/helm_push.sh
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/XS

#1299 Support for RHEL image builder on vSphere
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/L

#1309 Update HELM_TAG default value
  Common.mk
Labels: approved, lgtm, size/XS

#1306 Update ADOT helm charts
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws-observability/aws-otel-collector/helm/patches/0001-image-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0002-namespace-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/sedfile.template
Labels: approved, lgtm, size/L

#1315 Build business logic changes for release-branched helm support
  Common.mk
  build/lib/helm_require.sh
  projects/aws-observability/aws-otel-collector/Makefile
Labels: lgtm, size/S

#1314 Support RHEL creds for RHSM in image-builder
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/S

#1287 Autoscaler Helm Chart
  projects/kubernetes/autoscaler/1-21/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-21/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-21/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-21/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-21/helm/sedfile.template
  projects/kubernetes/autoscaler/1-22/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-22/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-22/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-22/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-22/helm/sedfile.template
  projects/kubernetes/autoscaler/1-23/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-23/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-23/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-23/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-23/helm/sedfile.template
  projects/kubernetes/autoscaler/1-24/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-24/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-24/helm/sedfile.template
  projects/kubernetes/autoscaler/Makefile
Labels: lgtm, size/L

#1317 Fix cross account issue for AWS ECR
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/patches/0004-fix-cross-account-issue-for-AWS-ECR.patch
Labels: approved, lgtm, size/L

#1318 Support uniform osFamily name "Redhat" instead of "Rhel"
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#1322 Remove build scripts for CAPA
  README.md
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-aws/.gitignore
  projects/kubernetes-sigs/cluster-api-provider-aws/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-aws/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-aws/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-aws/Help.mk
  projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
  projects/kubernetes-sigs/cluster-api-provider-aws/README.md
  projects/kubernetes-sigs/cluster-api-provider-aws/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-aws/docker/linux/cluster-api-aws-controller/Dockerfile
  projects/kubernetes-sigs/cluster-api-provider-aws/docker/linux/eks-bootstrap-controller/Dockerfile
  projects/kubernetes-sigs/cluster-api-provider-aws/docker/linux/eks-control-plane-controller/Dockerfile
  projects/kubernetes-sigs/cluster-api-provider-aws/expected_artifacts
  projects/kubernetes-sigs/cluster-api-provider-aws/manifests/infrastructure-components.yaml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1324 Fix makefile to use redhat instead of rhel string
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#1316 Add flag to deploy kubevip in tinkerbell-chart
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/rbac.yaml
  projects/tinkerbell/tinkerbell-chart/chart/values.yaml
Labels: approved, lgtm, size/XS

#1320 Cluster Autoscaler Packages schema.json
  projects/kubernetes/autoscaler/1-21/helm/schema.json
  projects/kubernetes/autoscaler/1-22/helm/schema.json
  projects/kubernetes/autoscaler/1-23/helm/schema.json
  projects/kubernetes/autoscaler/1-24/helm/schema.json
Labels: lgtm, size/XXL

#1325 Create distinct tags for each helm chart
  projects/kubernetes/autoscaler/Makefile
Labels: lgtm, size/XS

#1328 Create actual path instead of parent path
  projects/aws/eks-a-admin-image/Makefile
Labels: approved, lgtm, size/XS

#1326 Check if GIT_TAG is semver
  build/lib/helm_push.sh
Labels: approved, lgtm, size/XS

#1330 Clean up apt package cache before upgrade
  projects/aws/eks-a-admin-image/provisioners/upgrade_linux.sh
Labels: approved, lgtm, size/XS

#1333 Updating Procedure for adding imagePullSecret and namespaces to docs
  docs/development/update-helm-charts.md
Labels: approved, lgtm, size/XS

#1336 Use more robust filtering for skipped release branches
  Common.mk
  projects/kubernetes/autoscaler/Makefile
Labels: approved, lgtm, size/XS

#1337 Move package helm-chart doc
  docs/development/packages/update-helm-charts.md
Labels: approved, lgtm, size/XS

#1339 Add jonathanmeier5 to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1341 Update RHEL base image to 8.4
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#1340 Fallback to $SEMVER, not literal SEMVER
  build/lib/helm_push.sh
Labels: approved, lgtm, size/XS

#1342 Image builder change rhel target to call rhel-8
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/XS

#1338 Support Building Helm Charts From EKS-D Images
  build/lib/eksd_releases.sh
  build/lib/generate_projects_list.sh
Labels: approved, lgtm, size/S

#1335 Support multiple targets + redhat for local raw builds
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/S

#1343 Bump Snow Admin AMI generation wait time to 2 hours
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
Labels: approved, lgtm, size/XS

#1301 Bump CAPV to v1.3.1
  UPSTREAM_PROJECTS.yaml
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/image-builder/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0002-update-revive-dep-to-fix-go-mod-checksum-mismatch.patch
Labels: approved, lgtm, size/L

#1346 Redhat packer http endpoint for boot media
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/S

#1334 Updated git tag for latest image-builder with nutanix provider
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-crictl-validation-from-input-checksum.patch
Labels: approved, lgtm, size/M, ok-to-test

#1331 Metrics Server Helm Chart
  projects/kubernetes-sigs/metrics-server/.gitignore
  projects/kubernetes-sigs/metrics-server/1-21/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-21/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-21/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-22/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-22/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-22/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-23/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-23/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-23/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/Help.mk
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes-sigs/metrics-server/README.md
Labels: approved, lgtm, size/XL

#1347 Bump CAPAS to 0.1.8
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/L

#1345 Remove helm install from shasum
  build/lib/helm_push.sh
Labels: approved, lgtm, size/XS

#1351 bugfix: typo in the installation destination of go-licenses
  build/lib/install_go_versions.sh
Labels: approved, lgtm, size/XS

#1350 Revert the change where we bump for vsphere csi driver to 2.4.2
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/vsphere-csi-driver/ATTRIBUTION.txt
  projects/kubernetes-sigs/vsphere-csi-driver/CHECKSUMS
  projects/kubernetes-sigs/vsphere-csi-driver/GIT_TAG
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/README.md
  projects/kubernetes-sigs/vsphere-csi-driver/docker/linux/csi-syncer/Dockerfile
Labels: approved, lgtm, size/L

#1313 Add build info for CAPX
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/install_go_versions.sh
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/.gitignore
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Help.mk
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/build/create_manifests.sh
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/docker/linux/Dockerfile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/XXL, ok-to-test

#1353 Image builder support for Redhat on baremetal
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/L

#1359 Fix iso validation for ubuntu builds
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/S

#1360 Include json schema for release branched helm charts
  build/lib/helm_require.sh
Labels: approved, lgtm, size/XS

#1368 Add metrics-server schema.json
  projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
Labels: approved, lgtm, size/XXL

#1369 Fix Up Cluster Autoscaler Schema
  projects/kubernetes/autoscaler/1-21/helm/schema.json
  projects/kubernetes/autoscaler/1-22/helm/schema.json
  projects/kubernetes/autoscaler/1-23/helm/schema.json
  projects/kubernetes/autoscaler/1-24/helm/schema.json
Labels: approved, lgtm, size/XXL

#1367 Build metrics-server With Correct Image Tags
  build/lib/eksd_releases.sh
  projects/kubernetes-sigs/metrics-server/Makefile
Labels: approved, lgtm, size/XS
