Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-08, with the labels that each got.

#1105 Enable kube-rbac-proxy for CAPC Metrics Port
  UPSTREAM_PROJECTS.yaml
  projects/brancz/kube-rbac-proxy/CHECKSUMS
  projects/brancz/kube-rbac-proxy/GIT_TAG
  projects/brancz/kube-rbac-proxy/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/build/create_manifests.sh
Labels: approved, lgtm, size/S

#1110 Updates python base image and emissary to use it
  EKS_DISTRO_MINIMAL_BASE_PYTHON_TAG_FILE
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/docker/linux/emissary-image/Dockerfile
Labels: approved, lgtm, size/S

#1111 Update Bottlerocket release
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1100 Image builder CLI project
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/BUILD_TOOLING_GIT_TAG
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/Help.mk
  projects/aws/image-builder/LICENSE
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/root.go
  projects/aws/image-builder/cmd/version.go
  projects/aws/image-builder/expected_artifacts
  projects/aws/image-builder/go.mod
  projects/aws/image-builder/go.sum
  projects/aws/image-builder/main.go
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1116 Bump up kube-vip to v0.5.0
  UPSTREAM_PROJECTS.yaml
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kube-vip/kube-vip/GIT_TAG
  projects/kube-vip/kube-vip/README.md
Labels: approved, lgtm, size/S

#1117 Overriding kube-rbac-proxy image repo provided by CAPC with EKS-A default repo.
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/build/create_manifests.sh
Labels: approved, lgtm, size/XS

#1119 Fixing schema base64 script
  build/lib/helm_require.sh
Labels: approved, lgtm, size/XS

#1120 Change build-tooling pin for aws image-builder cli
  projects/aws/image-builder/BUILD_TOOLING_GIT_TAG
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/Makefile
Labels: approved, lgtm, size/S

#1115 update harbor-schema
  projects/goharbor/harbor/helm/schema.json
Labels: approved, lgtm, size/XL

#1121 CI to use aws image-builder cli to build OVAs
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_ova_image_cli.sh
  projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ova
Labels: approved, lgtm, size/L

#1124 Fix OVA builds on CI
  projects/kubernetes-sigs/image-builder/build/build_ova_image_cli.sh
  projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh
Labels: approved, lgtm, size/S

#1083 Add docs for updating helm charts
  docs/development/update-helm-charts.md
Labels: approved, lgtm, size/M

#1122 Add envoy to build-tooling
  UPSTREAM_PROJECTS.yaml
  projects/envoyproxy/envoy/GIT_TAG
  projects/envoyproxy/envoy/Help.mk
  projects/envoyproxy/envoy/Makefile
  projects/envoyproxy/envoy/README.md
  projects/envoyproxy/envoy/docker/linux/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1127 Remove envoy image name override
  projects/envoyproxy/envoy/Makefile
Labels: approved, lgtm, size/XS

#1125 Fix expected artifacts for CI
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ova
Labels: approved, lgtm, size/XS

#1114 MetalLB patches for GA
  projects/metallb/metallb/helm/patches/0001-Use-CRD-format-from-v0.13.x-and-convert-to-configmap.patch
  projects/metallb/metallb/helm/schema.json
Labels: approved, lgtm, size/L

#1133 Set proxy environment in HTTP client
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/patches/0002-Set-proxy-environment-in-HTTP-client.patch
Labels: approved, lgtm, size/S

#1138 Support kube channel 1-23 on image-builder cli
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/XS

#1139 Changed to use EKS-D 1.23-4
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#1141 Bump Helm to v3.9.2 (#1079)
  UPSTREAM_PROJECTS.yaml
  projects/helm/helm/ATTRIBUTION.txt
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/GIT_TAG
  projects/helm/helm/README.md
  projects/helm/helm/patches/0001-Insecure-flag-for-oci-push-pull-install.patch
Labels: approved, lgtm, size/L

#1134 Raw Image Builds on CI
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_raw
Labels: approved, lgtm, size/M

#1145 Make image-builder always pull latest eks-d artifacts
  projects/aws/image-builder/.gitignore
  projects/aws/image-builder/BUILD_TOOLING_GIT_TAG
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/S

#1144 Bump eksa packages to 0.2.0 alpha 1
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1147 Fix Raw builds on CI
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#1149 [ImageBuilder] Extracting tarball directly to download location
  projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh
Labels: approved, lgtm, size/XS

#1150 Bumping etcdadm release versions
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#1152 Removing old projects
  UPSTREAM_PROJECTS.yaml
  projects/grpc-ecosystem/grpc-health-probe/.gitignore
  projects/grpc-ecosystem/grpc-health-probe/ATTRIBUTION.txt
  projects/grpc-ecosystem/grpc-health-probe/CHECKSUMS
  projects/grpc-ecosystem/grpc-health-probe/GIT_TAG
  projects/grpc-ecosystem/grpc-health-probe/Help.mk
  projects/grpc-ecosystem/grpc-health-probe/Makefile
  projects/grpc-ecosystem/grpc-health-probe/README.md
  projects/grpc-ecosystem/grpc-health-probe/expected_artifacts
  projects/tinkerbell/pbnj/.gitignore
  projects/tinkerbell/pbnj/ATTRIBUTION.txt
  projects/tinkerbell/pbnj/CHECKSUMS
  projects/tinkerbell/pbnj/GIT_TAG
  projects/tinkerbell/pbnj/Help.mk
  projects/tinkerbell/pbnj/IPMITOOL_GIT_TAG
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1107 Add ecrtokenrefresher to eks-a-packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/ecrtokenrefresher/Dockerfile
  projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
Labels: approved, lgtm, size/M

#1153 Removing old projects (#1152)
  UPSTREAM_PROJECTS.yaml
  projects/grpc-ecosystem/grpc-health-probe/.gitignore
  projects/grpc-ecosystem/grpc-health-probe/ATTRIBUTION.txt
  projects/grpc-ecosystem/grpc-health-probe/CHECKSUMS
  projects/grpc-ecosystem/grpc-health-probe/GIT_TAG
  projects/grpc-ecosystem/grpc-health-probe/Help.mk
  projects/grpc-ecosystem/grpc-health-probe/Makefile
  projects/grpc-ecosystem/grpc-health-probe/README.md
  projects/grpc-ecosystem/grpc-health-probe/expected_artifacts
  projects/tinkerbell/pbnj/.gitignore
  projects/tinkerbell/pbnj/ATTRIBUTION.txt
  projects/tinkerbell/pbnj/CHECKSUMS
  projects/tinkerbell/pbnj/GIT_TAG
  projects/tinkerbell/pbnj/Help.mk
  projects/tinkerbell/pbnj/IPMITOOL_GIT_TAG
  projects/tinkerbell/pbnj/Makefile
  projects/tinkerbell/pbnj/README.md
  projects/tinkerbell/pbnj/docker/linux/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1129 Metallb and Harbor imagePullSecret and defaultNamespace
  projects/goharbor/harbor/helm/patches/0002-Adding-imagePullSecret-and-default-Namespace.patch
  projects/metallb/metallb/helm/patches/0002-Adding-imagePullSecrets-and-extracting-default-names.patch
Labels: approved, lgtm, size/XXL

#1154 Remove unused project directories for cert-manager and kube-vip (#1052)
  UPSTREAM_PROJECTS.yaml
  projects/jetstack/cert-manager/.gitignore
  projects/jetstack/cert-manager/ATTRIBUTION.txt
  projects/jetstack/cert-manager/CHECKSUMS
  projects/jetstack/cert-manager/GIT_TAG
  projects/jetstack/cert-manager/Help.mk
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/README.md
  projects/jetstack/cert-manager/build/create_manifests.sh
  projects/jetstack/cert-manager/docker/linux/cert-manager-acmesolver/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-cainjector/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-controller/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-ctl/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-webhook/Dockerfile
  projects/jetstack/cert-manager/expected_artifacts
  projects/jetstack/cert-manager/helm/patches/0001-Minor-clean-up-to-helm-chart.patch
  projects/jetstack/cert-manager/helm/patches/0002-Add-registry-to-helm-values.patch
  projects/jetstack/cert-manager/helm/patches/0003-Activate-digests-with-templates.patch
  projects/jetstack/cert-manager/helm/patches/0004-Add-registry-and-digest-for-ctl.patch
  projects/jetstack/cert-manager/helm/sedfile.template
  projects/jetstack/cert-manager/manifests/cert-manager.yaml
  projects/plunder-app/kube-vip/.gitignore
  projects/plunder-app/kube-vip/ATTRIBUTION.txt
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/Help.mk
  projects/plunder-app/kube-vip/Makefile
  projects/plunder-app/kube-vip/README.md
  projects/plunder-app/kube-vip/docker/linux/Dockerfile
  projects/plunder-app/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1156 Increase timeout for waitForKubelet to 90s
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/waiters.go
Labels: approved, lgtm, size/XS, ok-to-test

#1158 Add package attribution
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
Labels: approved, lgtm, size/XL

#1160 Bumping version for CAPC
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1091 Use envoy with LoadBalancerClass to expose Tinkerbell services
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/config-map.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip-service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/rbac.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/baseboardmanagement-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/bmcjob-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/bmctask-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/cluster-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/cluster-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/leader-election-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/leader-election-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/manager-configmap.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/secrets-viewer-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/secrets-viewer-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/cluster-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/cluster-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/hardware-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/leader-election-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/leader-election-rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/template-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/workflow-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/values.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/L, needed-next-release

#1163 Update required list
  projects/goharbor/harbor/helm/schema.json
Labels: approved, lgtm, size/XL

#1162 Update package Git tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1161 [ImageBuilder] Pull eks-a artifacts from bundles
  Common.mk
  build/lib/eksa_releases.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/L, needed-next-release

#1169 Bumping CAPC version to include account/domain conversion fix
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1171 Change raw image-builder base from AL2 to Ubuntu
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS, needed-next-release

#1167 Emissary namespace patch
  projects/emissary-ingress/emissary/helm/patches/0001-helm-changes.patch
Labels: approved, lgtm, size/XL

#1172 Remove dev from version - Image Builder
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
Labels: approved, lgtm, size/XS, needed-next-release

#1177 Typos and minor fixes for image-builder
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M

#1179 Adding namespace and imagePullSecret support to hello-eksa
  projects/aws-containers/hello-eks-anywhere/helm/patches/0001-Adding-namespace-and-imagePullSecret-support.patch
Labels: approved, lgtm, size/M

#1176 Imagepullsecret patch
  projects/emissary-ingress/emissary/helm/patches/0002-imagepullsecret.patch
Labels: approved, lgtm, size/S

#1183 bumping controller tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1184 updating packages tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: size/S

#1180 Excludes packages from staging bundle batch build
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/metallb/metallb/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1186 Split bottlerocket CI builds jobs from ubuntu
  projects/kubernetes-sigs/image-builder/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1188 Remove dependencies for EKS-A package-controller
  projects/aws/eks-anywhere-packages/Makefile
  release/staging-build.yml
Labels: size/XS

#1190 Fix exports on codebuild
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#1191 Skip Bottlerocket Raw release targets for 1-20 release branch
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#1196 emissary patch for namespace
  projects/emissary-ingress/emissary/helm/patches/0003-apiext-move.patch
Labels: approved, lgtm, size/L

#1197 fix for helm push a 2nd tag
  Common.mk
  build/lib/helm_push.sh
Labels: lgtm, size/S

#1195 Add readme for image-builder
  projects/aws/image-builder/README.md
Labels: approved, lgtm, size/L

#1199 fix for helm push script
  Common.mk
  build/lib/helm_push.sh
Labels: size/XS

#1201 fix for semvar2 helm req
  Common.mk
  build/lib/helm_push.sh
Labels: lgtm, size/S

#1203 bumping packages tag
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1205 fix for helm/push for harbor
  Common.mk
  build/lib/helm_push.sh
Labels: approved, lgtm, size/XS

#1210 Using latest CAPC (v0.4.7-rc3) release to fix several bugs
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1212 Fixes pause image baked into kind image
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/images/node/Dockerfile
Labels: approved, lgtm, size/XS

#1217 Update Packages Tag v0.2.1
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1215 Bumps cilium to 1.10.14
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#1224 Add HELM_SOURCE_IMAGE_REPO
  Common.mk
Labels: approved, lgtm, size/XS

#1225 Fix Ubuntu Raw builds on CI
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#1229 Add skip-checks argument to sparse-checkout for individual file support
  Common.mk
Labels: do-not-merge/hold, size/XS

#1235 Update package version v0.2.2
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1237 [Image Builder] Avoid cloning repo on CI
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/builder/builder.go
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/M

#1226 Bump vsphere-csi-driver to v2.4.2
  UPSTREAM_PROJECTS.yaml
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/image-builder/README.md
  projects/brancz/kube-rbac-proxy/README.md
  projects/envoyproxy/envoy/README.md
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/vsphere-csi-driver/ATTRIBUTION.txt
  projects/kubernetes-sigs/vsphere-csi-driver/CHECKSUMS
  projects/kubernetes-sigs/vsphere-csi-driver/GIT_TAG
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/README.md
  projects/kubernetes-sigs/vsphere-csi-driver/docker/linux/csi-syncer/Dockerfile
  projects/rancher/local-path-provisioner/README.md
Labels: approved, lgtm, size/L

#1240 [ImageBuilder] Set codebuild env vars appropriately
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/S

#1222 Add ADOT package
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/.gitignore
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/Help.mk
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/helm/patches/0001-image-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0002-namespace-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/sedfile.template
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/XL

#1242 Use latest tag instead of git branch
  Common.mk
  build/lib/eksa_releases.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M

#1245 Fix packages readme
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/XS

#1246 Fix raw ubuntu builds - Set directory path properly
  projects/aws/image-builder/.gitignore
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/S
