Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-11, with the labels that each got.

#1518 Update staging_buildspec project name handling
  build/lib/generate_staging_buildspec.sh
Labels: approved, lgtm, size/XS

#1456 Switch EKS-A Admin image to AL2 from Ubuntu
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
  projects/aws/eks-a-admin-image/build/get_latest_eksa_version_by_date.sh
  projects/aws/eks-a-admin-image/build/get_prod_admin_ami_path.sh
  projects/aws/eks-a-admin-image/build/validate-release-manifest-version.sh
  projects/aws/eks-a-admin-image/common.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-ci.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
  projects/aws/eks-a-admin-image/provisioners/al2/cleanup.sh
  projects/aws/eks-a-admin-image/provisioners/al2/install_deps.sh
  projects/aws/eks-a-admin-image/provisioners/al2/upgrade_linux.sh
  projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh
  projects/aws/eks-a-admin-image/provisioners/install_eksa.sh
  projects/aws/eks-a-admin-image/provisioners/setup_docker.sh
  projects/aws/eks-a-admin-image/provisioners/ubuntu/cleanup.sh
  projects/aws/eks-a-admin-image/provisioners/ubuntu/install_deps.sh
  projects/aws/eks-a-admin-image/provisioners/ubuntu/upgrade_linux.sh
Labels: approved, lgtm, size/L

#1519 Use proper Make target for EKS-A admin image build
  projects/aws/eks-a-admin-image/Makefile
Labels: approved, lgtm, size/XS

#1520 Prune all unused images, not just dangling ones
  projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh
Labels: approved, lgtm, size/S

#1513 upgrade nutanix provider codebase to latest version
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
Labels: approved, lgtm, size/S, ok-to-test

#1512 Add project prometheus node_exporter
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/node_exporter/.gitignore
  projects/prometheus/node_exporter/ATTRIBUTION.txt
  projects/prometheus/node_exporter/CHECKSUMS
  projects/prometheus/node_exporter/GIT_TAG
  projects/prometheus/node_exporter/Help.mk
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/node_exporter/build/sed_replace.sh
  projects/prometheus/node_exporter/docker/linux/Dockerfile
  projects/prometheus/node_exporter/patches/0001-update-go-mod.patch
Labels: approved, lgtm, size/XXL

#1505 Add Prometheus project
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/.gitignore
  projects/prometheus/prometheus/ATTRIBUTION.txt
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/GIT_TAG
  projects/prometheus/prometheus/Help.mk
  projects/prometheus/prometheus/Makefile
  projects/prometheus/prometheus/README.md
  projects/prometheus/prometheus/build/compress_assets.sh
  projects/prometheus/prometheus/build/cp_npm_licenses.sh
  projects/prometheus/prometheus/build/fix_go_licenses.sh
  projects/prometheus/prometheus/docker/linux/Dockerfile
Labels: approved, lgtm, size/XXL

#1531 Remove gwesterfieldjr from OWNERs
  OWNERS
Labels: approved, lgtm, size/XS

#1533 Update base image tag in tag file(s)
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_CSI_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GLIBC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_IPTABLES_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
Labels: approved, lgtm, size/S

#1537 Updates source-controller arm checksum and removes debug info
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/Makefile
Labels: approved, lgtm, size/XS

#1534 New release of controller with tags instead of digest
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/helm/sedfile.template
Labels: approved, lgtm, size/S

#1535 Add patch for CAPI CRS Reconcile mode
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0021-Implement-Reconcile-mode-for-ClusterResourceSet.patch
Labels: approved, lgtm, size/XXL

#1541 Update make add-generated-help-block and attribution-files logic
  Makefile
Labels: approved, lgtm, size/XS

#1528 Support build-your-own Ubuntu AMI through image-builder CLI
  projects/aws/image-builder/.gitignore
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils_test.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
  projects/aws/image-builder/go.mod
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/export-ami-to-s3.sh
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/packer/ami/ami.json
Labels: approved, lgtm, size/L

#1540 Fixes git fetch rate limit and build multiple binaries
  Common.mk
  build/lib/simple_create_binaries.sh
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#1542 Remove Trivy project from staging buildspec
  projects/aquasecurity/trivy/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#1546 Adds support to running just arm binary validation for source-controller
  Common.mk
  build/lib/validate_checksums.sh
Labels: approved, lgtm, size/S

#1529 Update for Vlan support in Tinkerbell
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Update-tinkerbell-tink-version.patch
  projects/tinkerbell/hook/ATTRIBUTION.txt
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/HOOK_BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/HOOK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/Help.mk
  projects/tinkerbell/hook/LINUX_KERNEL_VERSION
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/hook/docker/linux/hook-bootkit/Dockerfile
  projects/tinkerbell/hook/docker/linux/hook-docker/Dockerfile
  projects/tinkerbell/hook/patches/0001-Don-t-build-container-images.patch
  projects/tinkerbell/hook/patches/0001-Download-registry-cert-only-if-tinkerbell_tls-is-tru.patch
  projects/tinkerbell/hook/patches/0002-Implement-retry-for-tink-worker-docker-image-pull-to.patch
  projects/tinkerbell/hook/patches/0003-Added-support-for-allowing-image-pull-from-local-reg.patch
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0005-Create-VLAN-tagged-interface-if-vlan_id-exists-in-pr.patch
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/hardware-crd.yaml
Labels: approved, lgtm, size/XXL

#1550 Fix project path for clean and checksums
  Makefile
Labels: approved, lgtm, size/S

#1552 Fixes attribution job by cleanup disk space
  Makefile
Labels: approved, lgtm, size/XS

#1551 Splits attribution periodic
  Makefile
Labels: approved, lgtm, size/S

#1558 Update add-new-project for pkgs
  docs/development/add-new-project.md
Labels: approved, lgtm, size/XS

#1549 Bump metallb to 0.13.7 and add bgp password secret support
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/Makefile
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
  projects/metallb/metallb/helm/schema.json
Labels: approved, lgtm, size/L

#1559 Update Boots GIT_TAG:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/README.md
Labels: approved, lgtm, size/S

#1561 Fix Boots namespace issue
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/README.md
Labels: approved, lgtm, size/S

#1563 Add additional properties to hello schema
  projects/aws-containers/hello-eks-anywhere/helm/schema.json
Labels: approved, lgtm, size/XS

#1560 Updated EKS-D to latest for all versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1564 Create checksums for cloudstack builds
  build/lib/create_release_checksums.sh
Labels: approved, lgtm, size/XS

#1568 Update to packages v0.2.17
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1569 Check in share AMI configuration to the repo
  projects/kubernetes-sigs/image-builder/.gitignore
  projects/kubernetes-sigs/image-builder/packer/ami/share-ami.json
Labels: approved, lgtm, size/XS

#1567 Add Prometheus helm chart
  projects/prometheus/prometheus/HELM_GIT_TAG
  projects/prometheus/prometheus/Help.mk
  projects/prometheus/prometheus/Makefile
  projects/prometheus/prometheus/helm/patches/0001-chart-patch.diff
  projects/prometheus/prometheus/helm/patches/0002-image-patch.diff
  projects/prometheus/prometheus/helm/patches/0003-namespace-patch.diff
  projects/prometheus/prometheus/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#1571 Update to packages v0.2.18
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1572 Bumping CAPC to v0.4.9-rc1 to fix VM deletion bug
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1575 Create CNI temp directory in non-root user's home directory
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/XS

#1574 Add json validation for prometheus helm chart
  projects/prometheus/prometheus/helm/patches/0004-values-patch.diff
  projects/prometheus/prometheus/helm/patches/0005-json-schema-patch.diff
  projects/prometheus/prometheus/helm/schema.json
Labels: approved, lgtm, size/XXL

#1581 Update packages to v0.2.19
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1578 Set default input values for AMI build configuration
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/M

#1583 Use gzip compression when downloading images from bundle
  projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh
  projects/aws/eks-a-admin-image/provisioners/test/download_eksa_artifacts.sh
Labels: approved, lgtm, size/XS

#1584 Update README for 1.24
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#1582 Update packages to v0.2.20
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1566 Switch release branched builds to batch for codebuild
  Makefile
  build/lib/generate_projects_list.sh
  build/lib/generate_staging_buildspec.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#1588 Backport EKS-A admin image improvements
  projects/aws/eks-a-admin-image/Help.mk
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
  projects/aws/eks-a-admin-image/build/get_latest_eksa_version_by_date.sh
  projects/aws/eks-a-admin-image/build/get_prod_admin_ami_path.sh
  projects/aws/eks-a-admin-image/build/validate-release-manifest-version.sh
  projects/aws/eks-a-admin-image/common.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-ci.pkr.hcl
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
  projects/aws/eks-a-admin-image/provisioners/al2/cleanup.sh
  projects/aws/eks-a-admin-image/provisioners/al2/install_deps.sh
  projects/aws/eks-a-admin-image/provisioners/al2/upgrade_linux.sh
  projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh
  projects/aws/eks-a-admin-image/provisioners/install_eksa.sh
  projects/aws/eks-a-admin-image/provisioners/setup_docker.sh
  projects/aws/eks-a-admin-image/provisioners/ubuntu/cleanup.sh
  projects/aws/eks-a-admin-image/provisioners/ubuntu/install_deps.sh
  projects/aws/eks-a-admin-image/provisioners/ubuntu/upgrade_linux.sh
Labels: approved, lgtm, size/L

#1590 Fix nil pointer error when parsing AMI config
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/S

#1589 Upgrade ADOT to v0.23.0
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/helm/patches/0001-image-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0002-namespace-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml
Labels: approved, lgtm, size/M

#1593 Update package controller to v0.2.20
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1536 Add snow bootstrap container
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/docker/linux/snow/Dockerfile
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/go.sum
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/etcdadm.go
  projects/aws/bottlerocket-bootstrap/pkg/files/system.go
  projects/aws/bottlerocket-bootstrap/pkg/files/templater.go
  projects/aws/bottlerocket-bootstrap/pkg/files/writer.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/kubeadm.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/main.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/config/net.toml
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kubernetes.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network_test.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/reboot.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/volume.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go
Labels: approved, lgtm, size/XL

#1597 Update owners
  OWNERS
Labels: approved, lgtm, size/XS

#1598 Updates kind to 0.17
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/run_target_docker.sh
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  release/staging-build.yml
Labels: approved, lgtm, size/L

#1599 Add bottlerocket custom bootstrap containers option in capi kubeadm
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-bottlerocket-custom-bootstrap-containers-config.patch
Labels: approved, lgtm, size/XL

#1600 Remove kube-vip manifest from the bootstrap scripts for Snow
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-volume.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
  projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml
Labels: approved, lgtm, size/L, needs-ok-to-test

#1603 Revert "Remove kube-vip manifest from the bootstrap scripts, eks-a wi…
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-volume.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
  projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml
Labels: approved, lgtm, size/L

#1605 Update adot image digest
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/XS

#1606 Add Bottlerocket control container image v0.6.3
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
Labels: approved, lgtm, size/XS

#1607 Support configuring bottlerocket admin container image option
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Fix-the-issue-of-passing-taints-to-kubeadm.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Implement-Reconcile-mode-for-ClusterResourceSet.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-bottlerocket-custom-bootstrap-containers-config.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Support-configuring-bottlerocket-admin-container-image.patch
Labels: approved, lgtm, size/XL

#1601 Update BR version to v1.11.0
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1609 Fix emissary crd build
  projects/emissary-ingress/emissary/Makefile
Labels: approved, lgtm, size/XS

#1612 Bump CAPAS image version to 0.1.9
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/L

#1613 Add single primary DNI and static ip support in snow BR bootstrap container
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/config/net.toml
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network_test.go
Labels: approved, lgtm, size/L

#1617 Update Prometheus helm charts
  projects/prometheus/prometheus/helm/patches/0005-json-schema-patch.diff
  projects/prometheus/prometheus/helm/patches/0006-configmap-reload-patch.diff
  projects/prometheus/prometheus/helm/patches/0007-values-patch.diff
  projects/prometheus/prometheus/helm/schema.json
Labels: approved, lgtm, size/M

#1616 Revert "Update BR version to v1.11.0 (#1601)"
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1618 Deprecate 1.20
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/image-builder/README.md
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/staging-build.yml
Labels: approved, lgtm, size/M

#1615 Change docker file to account for command
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
Labels: approved, lgtm, size/S

#1620 Bump CAPAS to v0.1.10
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/L

#1619 Update image repo and tag in Nutanix infrastructure components
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/build/create_manifests.sh
Labels: approved, lgtm, size/XS
