Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-01, with the labels that each got.

#315 Add patch to retain update permission on etcdadmcluster for KCP controller
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0039-Retain-update-permission-on-etcdadmcluster-for-KCP-controller.patch
Labels: approved, lgtm, size/M

#310 Add CAPT patch to override the default workflow template
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0003-Add-templateOverride-for-default-CAPT-template.patch
Labels: approved, lgtm, size/L

#319 Wait until tarball is available under latest before downloading
  build/lib/common.sh
  build/lib/fetch_binaries.sh
Labels: approved, lgtm, size/S

#317 bump troubleshoot version
  UPSTREAM_PROJECTS.yaml
  projects/replicatedhq/troubleshoot/ATTRIBUTION.txt
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/GIT_TAG
  projects/replicatedhq/troubleshoot/Makefile
  projects/replicatedhq/troubleshoot/README.md
  projects/replicatedhq/troubleshoot/expected_artifacts
  projects/replicatedhq/troubleshoot/patches/0001-Replace-dependencies-to-mitigate-license-issues.patch
  projects/replicatedhq/troubleshoot/patches/0001-Replace-promptui-mod-to-mitigate-LGPL-dependency.patch
Labels: approved, lgtm, size/XL

#320 Upload cert-manager.yaml artifact
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/README.md
  projects/jetstack/cert-manager/build/create_manifests.sh
  projects/jetstack/cert-manager/expected_artifacts
  projects/jetstack/cert-manager/manifests/cert-manager.yaml
Labels: approved, lgtm, size/XXL

#323 Push generated Makefile changes to appropriately named branch
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#325 Add back patch to synchronize etcd upgrade flow from branch-0.3.19
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0040-Synchronize-upgrade-flow.patch
Labels: approved, lgtm, size/L

#326 Update CAPI tag to v1.0.2
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Templating-bottlerocket-init-data-formats.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Generating-proper-vip-destnation-path-for-bottlerock.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Fix-kube-vip-config-patching-by-creating-new-Files-a.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Adding-pause-and-bottlerocket-bootstrap-Cluster-conf.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-Add-bottlerocket-API-changes-to-v1beta1-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Set-bottlerocket-bootstrap-container-and-pause-conta.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-proxy-config-fields-to-v1beta1-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Support-proxy-configuration-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-network-settings-only-when-there-is-a-proxy-defi.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Remove-userdata-logging-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Unstacked-etcd-API-and-config-changes.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Unstacked-etcd-Changes-in-CAPI-core-controllers.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Unstacked-etcd-Changes-in-KCP-controller.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Unstacked-etcd-Change-in-docker-infra-provider.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Unstacked-etcd-Ignore-nodeRef-check-for-etcd-machine.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Delete-managed-external-etcd-cluster-last.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Update-KCP-controller-to-use-renamed-etcd-endpoints-.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-external-etcd-api-changes-to-v1beta1-capi-CRDs.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Reconcile-docker-machine-address-after-clusterctl-mo.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Rename-controlplane-upgrade-annotation-variable.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-controlplane-upgrade-complete-annotation-to-sync.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Check-if-controlplane-is-paused-before-patching-it-w.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Patch-etcd-cluster-with-upgrade-complete-annotation-.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Fix-etcdMachine-to-cluster-reconciler-so-it-listens-.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Update-log-message-based-on-1.0.1-tag.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Fix-watch-on-machine-object-for-etcdMachine-to-clust.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-external-etcd-api-to-v1alpha4.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Update-semver-build-indentifier-comparison-to-support-underordablestrings.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Use-shared-semver-compare-package-for-cert-manager-upgrade-check.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Retain-update-permission-on-etcdadmcluster-for-KCP-controller.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Synchronize-upgrade-flow.patch
Labels: approved, lgtm, size/L

#328 Set bash as shell for make in common makefile
  Common.mk
Labels: approved, lgtm, size/XS

#329 Bump cilium to v1.9.11 and add cilium chart digest
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/HELM_REPO_VERSION
  projects/cilium/cilium/Makefile
  projects/cilium/cilium/README.md
  projects/cilium/cilium/build/update_digest.sh
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/M

#331 Update tags in upstream projects tracker
  UPSTREAM_PROJECTS.yaml
Labels: approved, lgtm, size/XS

#332 Add instruction to run make generate when updating Cilium
  projects/cilium/cilium/README.md
Labels: approved, lgtm, size/XS

#333 Fix Cilium release targets
  projects/cilium/cilium/Makefile
Labels: approved, lgtm, size/XS

#327 Use shasum for eks-anywhere-test helm install
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/_helpers.tpl
  projects/aws/eks-anywhere-test/eks-anywhere-test/templates/deployment.yaml
  projects/aws/eks-anywhere-test/eks-anywhere-test/values.yaml
  projects/aws/eks-anywhere-test/helm/sedfile.template
Labels: approved, lgtm, size/S

#335 Fix image-builder patch
  projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
Labels: approved, lgtm, size/XS

#336 Add status.version to list of fields to ignore for update
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Templating-bottlerocket-init-data-formats.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Generating-proper-vip-destnation-path-for-bottlerock.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Fix-kube-vip-config-patching-by-creating-new-Files-a.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Adding-pause-and-bottlerocket-bootstrap-Cluster-conf.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-Add-bottlerocket-API-changes-to-v1beta1-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Set-bottlerocket-bootstrap-container-and-pause-conta.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-proxy-config-fields-to-v1beta1-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Support-proxy-configuration-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-network-settings-only-when-there-is-a-proxy-defi.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Remove-userdata-logging-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Unstacked-etcd-API-and-config-changes.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Unstacked-etcd-Changes-in-CAPI-core-controllers.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Unstacked-etcd-Changes-in-KCP-controller.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Unstacked-etcd-Change-in-docker-infra-provider.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Unstacked-etcd-Ignore-nodeRef-check-for-etcd-machine.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Delete-managed-external-etcd-cluster-last.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Update-KCP-controller-to-use-renamed-etcd-endpoints-.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-external-etcd-api-changes-to-v1beta1-capi-CRDs.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Reconcile-docker-machine-address-after-clusterctl-mo.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Rename-controlplane-upgrade-annotation-variable.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-controlplane-upgrade-complete-annotation-to-sync.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Check-if-controlplane-is-paused-before-patching-it-w.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Patch-etcd-cluster-with-upgrade-complete-annotation-.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Fix-etcdMachine-to-cluster-reconciler-so-it-listens-.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Update-log-message-based-on-1.0.1-tag.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Fix-watch-on-machine-object-for-etcdMachine-to-clust.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-external-etcd-api-to-v1alpha4.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Update-semver-build-indentifier-comparison-to-suppor.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Use-shared-semver-compare-package-for-cert-manager-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Retain-update-permission-on-etcdadmcluster-for-KCP-c.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Synchronize-upgrade-flow.patch
  projects/kubernetes-sigs/cluster-api/patches/0041-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
Labels: approved, lgtm, size/L

#341 Bump Flux version from v0.23 to v0.25
  UPSTREAM_PROJECTS.yaml
  build/lib/install_go_versions.sh
  docs/development/building-locally.md
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/README.md
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/README.md
Labels: approved, lgtm, size/XL

#337 Patches for CAPT BMC-Hardware Power and Deprovision
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0004-Modifying-BMC-CRD-to-read-from-Secret.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0005-Adding-PBNJ-PowerAction-to-BMC-controller.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0006-Adding-PBNJ-BootDevice-to-BMC-CRD-and-client.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0007-Adding-BmcRef-to-hardware-and-PowerOn-machine.patch
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0008-Deprovision-hardware-after-hardware-release.patch
Labels: approved, lgtm, size/XL

#316 Build Redis image
  projects/redis/redis/.gitignore
  projects/redis/redis/GIT_TAG
  projects/redis/redis/Help.mk
  projects/redis/redis/Makefile
  projects/redis/redis/README.md
  projects/redis/redis/buildspec.yml
  projects/redis/redis/docker/linux/Dockerfile
Labels: approved, lgtm, size/L

#345 Update to latest eks-d versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#344 Set namespace arg to eksa-system for capi, capv and external etcd con…
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api/build/create_manifests.sh
  projects/mrajashree/etcdadm-bootstrap-provider/build/create_manifests.sh
  projects/mrajashree/etcdadm-controller/build/create_manifests.sh
Labels: approved, lgtm, size/S

#346 patch troubleshoot to avoid nil pointer when namespace does not exist
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/patches/0002-Add-nil-check-to-analyzer-processing.patch
Labels: approved, lgtm, size/M

#348 Remove micahhausler from approvers
  OWNERS
Labels: approved, lgtm, size/XS

#349 upload tink artifacts to the s3 bucket
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/expected_artifacts
Labels: approved, lgtm, size/S

#352 changed tink-cli binary name to tink
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/Help.mk
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/docker/linux/tink-cli/Dockerfile
Labels: approved, lgtm, size/S

#354 add tink-cli binary to CLI tools image
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh
Labels: approved, lgtm, size/XS

#350 Remove bnrjee from OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#353 Remove command to set unsupported namespace flag in docker provider
  projects/kubernetes-sigs/cluster-api/build/create_manifests.sh
Labels: approved, lgtm, size/XS

#355 Fix redis badges
  projects/redis/redis/README.md
Labels: approved, lgtm, size/XS

#360 Build Helm during staging build
  Makefile
Labels: approved, lgtm, size/XS

#359 Add etcdadm cipher suites flag support for bottlerocket
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/etcdadm.go
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/flags.go
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/init.go
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/join.go
  projects/mrajashree/etcdadm-bootstrap-provider/CHECKSUMS
  projects/mrajashree/etcdadm-bootstrap-provider/GIT_TAG
  projects/mrajashree/etcdadm-controller/CHECKSUMS
  projects/mrajashree/etcdadm-controller/GIT_TAG
Labels: approved, lgtm, size/M

#363 Update Bottlerocket to 1.5.2
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/XS

#364 Add node labels support for bottlerocket
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Templating-bottlerocket-init-data-formats.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Generating-proper-vip-destnation-path-for-bottlerock.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Fix-kube-vip-config-patching-by-creating-new-Files-a.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Adding-pause-and-bottlerocket-bootstrap-Cluster-conf.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-Add-bottlerocket-API-changes-to-v1beta1-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Set-bottlerocket-bootstrap-container-and-pause-conta.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-proxy-config-fields-to-v1beta1-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Support-proxy-configuration-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-network-settings-only-when-there-is-a-proxy-defi.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Remove-userdata-logging-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Unstacked-etcd-API-and-config-changes.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Unstacked-etcd-Changes-in-CAPI-core-controllers.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Unstacked-etcd-Changes-in-KCP-controller.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Unstacked-etcd-Change-in-docker-infra-provider.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Unstacked-etcd-Ignore-nodeRef-check-for-etcd-machine.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Delete-managed-external-etcd-cluster-last.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Update-KCP-controller-to-use-renamed-etcd-endpoints-.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-external-etcd-api-changes-to-v1beta1-capi-CRDs.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Reconcile-docker-machine-address-after-clusterctl-mo.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Rename-controlplane-upgrade-annotation-variable.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-controlplane-upgrade-complete-annotation-to-sync.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Check-if-controlplane-is-paused-before-patching-it-w.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Patch-etcd-cluster-with-upgrade-complete-annotation-.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Fix-etcdMachine-to-cluster-reconciler-so-it-listens-.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Update-log-message-based-on-1.0.1-tag.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Fix-watch-on-machine-object-for-etcdMachine-to-clust.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-external-etcd-api-to-v1alpha4.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Update-semver-build-indentifier-comparison-to-suppor.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Use-shared-semver-compare-package-for-cert-manager-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Retain-update-permission-on-etcdadmcluster-for-KCP-c.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Synchronize-upgrade-flow.patch
  projects/kubernetes-sigs/cluster-api/patches/0041-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0042-Add-node-labels-support-for-bottlerocket.patch
Labels: approved, lgtm, size/L

#366 Update BR version to 1.5.3
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES
Labels: approved, lgtm, size/XS

#369 Update version references for cluster-api and etcdadm
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/README.md
  projects/mrajashree/etcdadm-bootstrap-provider/README.md
  projects/mrajashree/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#338 Add logic to build Ubuntu raw image with EKS-D artifacts
  Common.mk
  Makefile
  build/lib/create_release_checksums.sh
  build/lib/eksd_releases.sh
  build/lib/validate_artifacts.sh
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/etcdadm.go
  projects/kubernetes-sigs/image-builder/.gitignore
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-raw.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-raw.yml
  projects/kubernetes-sigs/image-builder/expected_artifacts_ova
  projects/kubernetes-sigs/image-builder/expected_artifacts_raw
  projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
Labels: approved, lgtm, size/L

#371 Adding tinkerbell/boots project to build tooling
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/.gitignore
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/Help.mk
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/boots/buildspec.yml
  projects/tinkerbell/boots/docker/linux/Dockerfile
  projects/tinkerbell/boots/ipxe/ipxe.efi
  projects/tinkerbell/boots/ipxe/snp-hua.efi
  projects/tinkerbell/boots/ipxe/snp-nolacp.efi
  projects/tinkerbell/boots/ipxe/undionly.kpxe
Labels: approved, lgtm, size/XL

#358 Updating tinkerbell project GIT_TAG files to releases
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/patches/0001-Adding-build-comment-for-go1.16-go-licenses-compatab.patch
  projects/tinkerbell/tink/patches/0001-Fixing-go.mod-replace-commit.patch
Labels: approved, lgtm, size/M

#373 Run EC2 instance in Codebuild's subnet and security group
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/S

#375 Avoid creating source directories on destination during rsync copy
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#376 Ensure EC2 keys get created with unique name to avoid collisions
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/M

#280 kind: add haproxy image now that capd allows overwriting
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
  projects/aws/eks-anywhere-test/Makefile
  projects/aws/eks-anywhere-test/docker/linux/Dockerfile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/images/haproxy/Dockerfile
Labels: approved, lgtm, size/M

#378 Use absolute path for bottlerocket download directory
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#380 Put packer log in expected artifacts path
  build/lib/validate_artifacts.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#381 Adding Image repo var to buildspec to push helm to gallery on builds.
  projects/jetstack/cert-manager/buildspec.yml
  projects/redis/redis/buildspec.yml
Labels: approved, lgtm, size/XS

#382 Move raw image build packer log one level up
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#383 Make subnet array one-indexed
  projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
Labels: approved, lgtm, size/XS

#384 Add build logic for gRPC health probe project
  UPSTREAM_PROJECTS.yaml
  build/lib/generate_help_body.sh
  projects/grpc-ecosystem/grpc-health-probe/.gitignore
  projects/grpc-ecosystem/grpc-health-probe/ATTRIBUTION.txt
  projects/grpc-ecosystem/grpc-health-probe/CHECKSUMS
  projects/grpc-ecosystem/grpc-health-probe/GIT_TAG
  projects/grpc-ecosystem/grpc-health-probe/Help.mk
  projects/grpc-ecosystem/grpc-health-probe/Makefile
  projects/grpc-ecosystem/grpc-health-probe/README.md
  projects/grpc-ecosystem/grpc-health-probe/buildspec.yml
  projects/grpc-ecosystem/grpc-health-probe/expected_artifacts
Labels: approved, lgtm, size/XL
