Repository aws/eks-anywhere-build-tooling, pull requests merged in 2022-07, with the labels that each got.

#1024 Runs handle_deps as prepreq for images
  Common.mk
  build/lib/run_target_docker.sh
Labels: approved, lgtm, size/S

#1023 Remove helm from jetstack/cert-manager
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/README.md
  projects/jetstack/cert-manager/helm/patches/0001-Minor-clean-up-to-helm-chart.patch
  projects/jetstack/cert-manager/helm/patches/0002-Add-registry-to-helm-values.patch
  projects/jetstack/cert-manager/helm/patches/0003-Activate-digests-with-templates.patch
  projects/jetstack/cert-manager/helm/patches/0004-Add-registry-and-digest-for-ctl.patch
  projects/jetstack/cert-manager/helm/sedfile.template
Labels: approved, lgtm, size/L

#1026 Remove Tuftool install prerequisite for Bottlerocket downloads
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
Labels: approved, lgtm, size/S

#1031 Updated EKS-D versions for 1.19 - 1.23
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1035 Hardcode HOME env var to root directory
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
Labels: size/XS

#1036 Provide absolute path to Tuftool executable
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
Labels: size/XS

#1037 Revert changes to Imagebuilder Makefile and script
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
Labels: approved, lgtm, size/XS

#1025 Remove tink-cli from the tools image
  .gitignore
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/docker/linux/tink-cli/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#898 Update go-license installation instructions
  docs/development/attribution-files.md
Labels: approved, lgtm, size/XS

#1042 Add json schema for hello app
  projects/aws-containers/hello-eks-anywhere/helm/schema.json
Labels: approved, lgtm, size/S

#1027 Remove hardcoded region for SecretsManager
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/pkg/service/secretsmanager.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata_test.go
Labels: approved, lgtm, size/M, ok-to-test

#1043 Add trivy configs to the list
  projects/goharbor/harbor/helm/requires-config.yaml
Labels: approved, lgtm, size/XS

#1046 Bump troubleshoot to v0.37.1
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/expected_artifacts
  projects/cloudflare/cfssl/expected_artifacts
  projects/replicatedhq/troubleshoot/ATTRIBUTION.txt
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/GIT_TAG
  projects/replicatedhq/troubleshoot/README.md
  projects/replicatedhq/troubleshoot/expected_artifacts
  projects/replicatedhq/troubleshoot/patches/0001-Replace-dependencies-to-mitigate-license-issues.patch
Labels: approved, lgtm, size/M

#1044 Bump govmomi to v0.29.0
  UPSTREAM_PROJECTS.yaml
  projects/vmware/govmomi/ATTRIBUTION.txt
  projects/vmware/govmomi/CHECKSUMS
  projects/vmware/govmomi/GIT_TAG
  projects/vmware/govmomi/Makefile
  projects/vmware/govmomi/README.md
Labels: approved, lgtm, size/S

#1045 Bump kube-vip to v0.4.4
  UPSTREAM_PROJECTS.yaml
  projects/kube-vip/kube-vip/ATTRIBUTION.txt
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kube-vip/kube-vip/GIT_TAG
  projects/kube-vip/kube-vip/Makefile
  projects/kube-vip/kube-vip/README.md
Labels: approved, lgtm, size/L

#1049 Fix logic to get active interface for Packer HTTP server
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/S

#1050 Bump cert-manager to v1.8.2
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
Labels: approved, lgtm, size/XL

#1052 Remove unused project directories for cert-manager and kube-vip
  UPSTREAM_PROJECTS.yaml
  projects/jetstack/cert-manager/.gitignore
  projects/jetstack/cert-manager/ATTRIBUTION.txt
  projects/jetstack/cert-manager/CHECKSUMS
  projects/jetstack/cert-manager/GIT_TAG
  projects/jetstack/cert-manager/Help.mk
  projects/jetstack/cert-manager/Makefile
  projects/jetstack/cert-manager/README.md
  projects/jetstack/cert-manager/build/create_manifests.sh
  projects/jetstack/cert-manager/docker/linux/cert-manager-acmesolver/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-cainjector/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-controller/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-ctl/Dockerfile
  projects/jetstack/cert-manager/docker/linux/cert-manager-webhook/Dockerfile
  projects/jetstack/cert-manager/expected_artifacts
  projects/jetstack/cert-manager/manifests/cert-manager.yaml
  projects/plunder-app/kube-vip/.gitignore
  projects/plunder-app/kube-vip/ATTRIBUTION.txt
  projects/plunder-app/kube-vip/CHECKSUMS
  projects/plunder-app/kube-vip/GIT_TAG
  projects/plunder-app/kube-vip/Help.mk
  projects/plunder-app/kube-vip/Makefile
  projects/plunder-app/kube-vip/README.md
  projects/plunder-app/kube-vip/docker/linux/Dockerfile
  projects/plunder-app/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1055 Remove default bundle from PackageBundleController
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/XS

#1051 Bump cloud-provider-vsphere to latest patch versions
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-vsphere/1-20/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-20/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-20/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-21/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-21/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-21/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-22/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-22/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-22/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-23/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-23/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/README.md
Labels: approved, lgtm, size/M

#1053 Bump Flux components to latest
  UPSTREAM_PROJECTS.yaml
  projects/aws/eks-anywhere-packages/README.md
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/helm/patches/0001-Disable-image-automation.patch
  projects/fluxcd/flux2/helm/patches/0002-Allow-modification-of-image-tags.patch
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/helm-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/notification-controller/patches/0001-replace-containrrr-shoutrrr-due-to-checksum-mismatch.patch
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/patches/0001-Use-distribution-distribution-2.8.1-to-avoid-mod-che.patch
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/XXL

#1069 schema should validate any extra configurations not available to use
  projects/aws-containers/hello-eks-anywhere/helm/schema.json
Labels: approved, lgtm, size/XS

#1040 Added script to mount an additional volume for container data
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-volume.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh
  projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml
Labels: approved, lgtm, size/M, ok-to-test

#1064 Add proxy configuration to common.json
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/config/common.json.tmpl
Labels: approved, lgtm, size/S

#1070 Bump snow to 0.1.6
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/M

#1071 Use Linuxkit binary from GOPATH
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/Makefile
Labels: approved, lgtm, size/S

#1074 Clean up harbor repo for every image build
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/S

#1077 Add nmap and iputils installations to Docker file
  projects/aws/eks-anywhere/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS, ok-to-test

#1086 Add json schema to requires.yaml file
  build/lib/helm_require.sh
Labels: lgtm, size/S

#1087 Bump CAPI to v1.2.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-generated-manifest-changes-for-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-update-coredns-corefile-migration-to-support-1.8.7.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Allow-kubeadm-bootstrap-token-TTL-to-be-configurable.patch
Labels: approved, lgtm, size/XXL

#1081 Add cloud-provider-aws
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-aws/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/GIT_TAG
  projects/kubernetes/cloud-provider-aws/Help.mk
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-aws/README.md
  projects/kubernetes/cloud-provider-aws/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/XL

#1090 Update cert-manager reference
  README.md
  docs/development/add-new-project.md
Labels: approved, lgtm, size/S

#1089 Fix cloud-provider-aws extra flags
  projects/kubernetes/cloud-provider-aws/.gitignore
  projects/kubernetes/cloud-provider-aws/Makefile
Labels: approved, lgtm, size/XS

#1059 Emissary ingress Package
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_PYTHON_TAG_FILE
  UPSTREAM_PROJECTS.yaml
  build/lib/helm_pull.sh
  build/lib/helm_replace.sh
  projects/emissary-ingress/emissary/.gitignore
  projects/emissary-ingress/emissary/APPMESH_VERSION
  projects/emissary-ingress/emissary/ATTRIBUTION.txt
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GIT_TAG
  projects/emissary-ingress/emissary/Help.mk
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/README.md
  projects/emissary-ingress/emissary/docker/linux/emissary-image/Dockerfile
  projects/emissary-ingress/emissary/helm/patches/0001-helm-changes.patch
  projects/emissary-ingress/emissary/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#1094 Bump tags for etcdadm bootstrap provider and controller repos
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/Makefile
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/L

#1098 Adding emissary-schema
  projects/emissary-ingress/emissary/helm/schema.json
Labels: approved, lgtm, size/XL

#1085 Have tinkerbell follow the regular helm pattern
  projects/tinkerbell/tinkerbell-chart/Help.mk
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/M

#1095 Makefile changes for local image-builder cli
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/S

#1104 Revert "Bump tags for etcdadm bootstrap provider and controller repos"
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/Makefile
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/L

#1106 adding harbor-schema
  projects/goharbor/harbor/helm/schema.json
Labels: approved, lgtm, size/XXL

#1108 Remove old requires-config.yaml files
  projects/aws-containers/hello-eks-anywhere/helm/requires-config.yaml
  projects/aws/eks-anywhere-packages/helm/requires-config.yaml
  projects/goharbor/harbor/helm/requires-config.yaml
Labels: approved, lgtm, size/M

#1109 Updated EKS-D versions for 1.19, 1.20, and 1.21
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#1082 kind: Bumps to 0.14.0 along with local-path to 0.0.22
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/rancher/local-path-provisioner/ATTRIBUTION.txt
  projects/rancher/local-path-provisioner/CHECKSUMS
  projects/rancher/local-path-provisioner/GIT_TAG
  projects/rancher/local-path-provisioner/Makefile
Labels: approved, lgtm, size/L
