Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-08, with the labels that each got.

#2361 Embed EKS-A version in image-builder with support for overrides
  build/lib/eksa_releases.sh
  projects/aws/image-builder/.gitignore
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/L

#2365 Make EKS-A release version mutable in script
  build/lib/eksa_releases.sh
Labels: approved, lgtm, size/XS

#2358 Update capi etcd patch to avoid NodeHealthy false
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
Labels: approved, lgtm, size/L

#2367 Backport changes to embed EKS-A version in image-builder
  build/lib/eksa_releases.sh
  projects/aws/image-builder/.gitignore
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/L

#2368 Support dev release image builds from prod image-builder
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/utils.go
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M

#2374 Provide default value for EKSA_USE_DEV_RELEASE variable
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/nutanix/nutanix.json
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0015-Shrink-qemu-ubuntu-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0017-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
  projects/kubernetes-sigs/image-builder/patches/0018-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0019-Pin-packer-plugin-nutanix-to-v0.7.1.patch
Labels: approved, lgtm, size/L

#2377 Point ISO URL to Ubuntu old releases CDN
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch
Labels: approved, lgtm, size/XS

#2380 Bump up etcdadm-controller version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2382 Bump up etcdadm-controller version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2364 Bump eks d releases for EKS A
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2388 Patch writefile to error when no content specified
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0011-Ensure-content-is-specified-before-writing-file.patch
Labels: approved, lgtm, size/M

#2379 improves support for building image-builder from main and release bra…
  Common.mk
  build/lib/eksa_releases.sh
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/L

#2389 Bump up etcdadm-controller to v1.0.11
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2393 Update git tag of eks-anywhere-packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#2394 Backport script changes to support cross-version image builds
  build/lib/eksa_releases.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/S

#2399 Don't roll KCP when etcd not ready or no endpoints
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
Labels: approved, lgtm, size/XL

#2397 Add cloud provider vsphere 1.27
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-vsphere/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-27/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/GOLANG_VERSION
Labels: approved, lgtm, size/S

#2401 Latest eks-d versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2403 builds image-builder cli before running upstream
  Common.mk
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
Labels: approved, lgtm, size/M

#2404 fixes raw/cloudstack builds
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
Labels: size/S

#2405 disable cgroupns in kind/capd
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0036-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0004-Disable-cgroupns-private-to-fix-cluster-creation-on-.patch
Labels: size/M

#2406 revert runc and containerd in kind image
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
Labels: size/M

#2410 Upgrade Bottlerocket to v1.14.3
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2409 adds eks-d manifest url to br upload
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ami_bottlerocket
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ova_bottlerocket
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_raw_bottlerocket
Labels: approved, lgtm, size/XS

#2412 do not lock containerd version
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
Labels: approved, lgtm, size/S

#2421 skips image builds and packages on release branches
  Common.mk
  buildspec.yml
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/trivy/Makefile
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/metallb/metallb/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
Labels: approved, lgtm, size/M

#2422 splits harbor into batch build for images
  Common.mk
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/buildspecs/batch-build.yml
  projects/goharbor/harbor/docker/linux/combine/Dockerfile
Labels: approved, lgtm, size/M

#2426 splits harbor into batch build for images
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/buildspecs/batch-build.yml
Labels: approved, lgtm, size/S

#2423 backport image building skips
  Common.mk
  buildspec.yml
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/trivy/Makefile
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/metallb/metallb/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
Labels: approved, lgtm, size/M

#2432 Add tatlat to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#2424 add 1-28 as a supported release branch
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-28/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-28/helm/sedfile.template
  projects/kubernetes/autoscaler/1-28/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-28/CHECKSUMS
  projects/kubernetes/autoscaler/1-28/GIT_TAG
  projects/kubernetes/autoscaler/1-28/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-28/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-28/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0007-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-28/helm/schema.json
  projects/kubernetes/autoscaler/1-28/helm/sedfile.template
  projects/kubernetes/autoscaler/1-28/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-28/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-aws/1-28/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-28/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-28/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-28/GOLANG_VERSION
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/1-28/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-28/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-28/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-28/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2434 Fall back to previous release branch section for common binaries
  build/lib/eksa_releases.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M

#2438 fixes kubelet version check in kind node build
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm, size/XS

#2436 skips br builds for new kube versions
  Common.mk
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/S

#2441 Add patch for writefile action
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0012-Allow-BOOTCONFIG_CONTENTS-and-CONTENTS-to-be-checked.patch
Labels: approved, lgtm, size/M

#2442 Fix harbor api webpage access issue
  projects/goharbor/harbor/docker/linux/harbor-portal/Dockerfile
Labels: approved, lgtm, size/XS

#2443 Enable Inspector V2 scan for EKS-A Admin AMI
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
Labels: approved, lgtm, size/M

#2446 Fix loop in export AMI script
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
Labels: approved, lgtm, size/XS

#2447 Fix regex check for SSM managed instances
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
Labels: approved, lgtm, size/XS

#2453 add cxbrowne1207 to owners
  OWNERS
Labels: approved, lgtm, size/XS, ok-to-test

#2454 image-builder: update checksum for Bottlerocket's new root.json
  projects/kubernetes-sigs/image-builder/bottlerocket-root-json-checksum
Labels: approved, lgtm, size/XS, ok-to-test
