Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-07, with the labels that each got.

#2286 Bump CAPAS to 0.1.26 and fix network bugs
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
Labels: approved, lgtm, size/XS, needs-ok-to-test

#2292 Revert kind base image for AL2023
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
Labels: approved, lgtm, size/XS

#2294 brings back fix for kind tarballs due to license file overwrites
  build/lib/common.sh
  build/lib/simple_create_tarballs.sh
Labels: approved, lgtm, size/S

#2296 Fixing staging build yml
  Common.mk
  release/staging-build.yml
Labels: approved, lgtm, size/S

#2298 fixes staging buildspec generation to account of release branched deps
  build/lib/generate_staging_buildspec.sh
  release/staging-build.yml
Labels: approved, lgtm, size/S

#2300 Updated to latest EKS-D versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2290 Upgrade to Cilium v1.12.11
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2306 disables udp offload on redhat for vwmare
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0015-Shrink-qemu-ubuntu-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0017-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
  projects/kubernetes-sigs/image-builder/patches/0018-adds-disable-udp-service-for-redhat-on-vmware.patch
Labels: approved, lgtm, size/M

#2307 Fix getting git commit from bundle cmd
  build/lib/eksa_releases.sh
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/S

#2297 removes older base image tag files we do not use anymore
  EKS_DISTRO_MINIMAL_BASE_CSI_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GOLANG_COMPILER_1.17_GCC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_TAG_FILE
Labels: approved, lgtm, size/XS

#2309 Suppress shell opts restoration output
  build/lib/eksa_releases.sh
Labels: approved, lgtm, size/XS

#2310 Remove bad quotes
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/XS

#2312 Allow users to force checking out main branch
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/XS

#2308 Bump Flux CLI and controllers to latest GA releases
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/patches/0001-Replace-github.com-homeport-dyff-with-commit-to-work.patch
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/README.md
Labels: approved, lgtm, size/XXL

#2313 adds support for building with efi firmware to image-builder
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
Labels: approved, lgtm, size/L

#2311 adds support to build ubuntu ova using efi firmware
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/M

#2317 Support etcdadm pulling from EKS-D
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/patches/0004-Support-pulling-etcd-from-EKS-D.patch
Labels: approved, lgtm, size/M

#2164 Add support for mounting custom files during image builds
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/files.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/go.mod
  projects/aws/image-builder/go.sum
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/L

#2305 Bump kube-vip to v0.6.0
  UPSTREAM_PROJECTS.yaml
  projects/kube-vip/kube-vip/ATTRIBUTION.txt
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kube-vip/kube-vip/GIT_TAG
  projects/kube-vip/kube-vip/README.md
Labels: approved, lgtm, size/S

#2318 Define Packer type var files based on image build format
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/M

#2319 Provide full path to additional files config
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/XS

#2320 Add space in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#2321 Bump CAPX to v1.2.3
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/patches/0001-Add-tolerations-to-capx-controller-manager-podspec.patch
Labels: approved, lgtm, size/M

#2331 Update CAPC GIT TAG
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
Labels: approved, lgtm, size/XS

#2315 Bump CAPV to v1.7.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Add-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/L

#2332 Update etcdadm-controller and etcdadm-bootstrap-provider to latest version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2339 Revert "Update CHECKSUMS files (#2327)"
  build/lib/install_go_versions.sh
  projects/apache/cloudstack-cloudmonkey/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/image-builder/CHECKSUMS
  projects/aws/rolesanywhere-credential-helper/CHECKSUMS
  projects/brancz/kube-rbac-proxy/CHECKSUMS
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/containerd/containerd/CHECKSUMS
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/source-controller/CHECKSUMS
  projects/goharbor/harbor/CHECKSUMS
  projects/helm/helm/CHECKSUMS
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cri-tools/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes/autoscaler/1-23/CHECKSUMS
  projects/kubernetes/autoscaler/1-24/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-26/CHECKSUMS
  projects/kubernetes/autoscaler/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-27/CHECKSUMS
  projects/metallb/metallb/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/opencontainers/runc/CHECKSUMS
  projects/prometheus/prometheus/CHECKSUMS
  projects/rancher/local-path-provisioner/CHECKSUMS
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/tink/CHECKSUMS
  projects/vmware/govmomi/CHECKSUMS
Labels: approved, lgtm, size/L

#2341 Revert "Update ATTRIBUTION.txt files"
  projects/apache/cloudstack-cloudmonkey/ATTRIBUTION.txt
  projects/aquasecurity/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aws/bottlerocket-bootstrap/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/brancz/kube-rbac-proxy/ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/containerd/containerd/ATTRIBUTION.txt
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/goharbor/harbor/ATTRIBUTION.txt
  projects/helm/helm/ATTRIBUTION.txt
  projects/kube-vip/kube-vip/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cri-tools/ATTRIBUTION.txt
  projects/kubernetes-sigs/etcdadm/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-25/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-26/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-27/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-23/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-24/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-27/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-27/ATTRIBUTION.txt
  projects/opencontainers/runc/ATTRIBUTION.txt
  projects/rancher/local-path-provisioner/ATTRIBUTION.txt
  projects/replicatedhq/troubleshoot/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/hegel/ATTRIBUTION.txt
  projects/tinkerbell/rufio/ATTRIBUTION.txt
Labels: approved, lgtm, size/L

#2336 Add a CAPI patch to allow registry mirror configuration to be mutable
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
Labels: approved, lgtm, size/L

#2344 Bump CAPC to newest version
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#2343 Bump etcdadm-controller to latest version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2350 Refactor additional files mount logic
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/files.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
Labels: approved, lgtm, size/L

#2351 Remove default additional files params for AMI builds
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#2352 Fix absolute path for Snow AMI scripts
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/constants.go
Labels: approved, lgtm, size/S

#2354 Backport ami build fixes
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/files.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
Labels: approved, lgtm, size/L

#2356 fix kindnetd manifest
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/manifests/kindnetd.yaml
Labels: approved, lgtm, size/L

#2360 Backport image-builder cli fix for getting bundle
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/XS
