Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-11, with the labels that each got.

#2626 bumps ssh timeout to 40m for raw and qemu image builds
  projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch
Labels: approved, lgtm, size/XS

#2625 fixex help generation for kind project
  Makefile
  projects/aws/image-builder/Makefile
  projects/fluxcd/flux2/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes/autoscaler/Makefile
Labels: approved, lgtm, size/S

#2623 run in docker cleanup and fixes
  Common.mk
  Makefile
  build/lib/make_shell.sh
  build/lib/run_target_docker.sh
  docs/development/building-locally.md
Labels: approved, lgtm, size/M

#2627 fixes builder base image url
  build/lib/run_target_docker.sh
Labels: approved, lgtm, size/XS

#2624 Fix unschedulable Tinkerbell stack when no worker nodes
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/_scheduling.tpl
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/values.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/M

#2639 Update CAPC to 0.4.9-rc8
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#2641 [release-0.17] Update CAPC to 0.4.9-rc8
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#2637 downloads iso before calling qemu
  projects/kubernetes-sigs/image-builder/.gitignore
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/M

#2646 fixes image builder retry logic
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/S

#2650 bump eksd
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2530 Update emissary from 3.6.0 to 3.8.1
  UPSTREAM_PROJECTS.yaml
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GIT_TAG
  projects/emissary-ingress/emissary/GOLANG_VERSION
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
Labels: approved, lgtm, size/M

#2647 uses build acct instead of prow acct for metal testing
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/prow_build.sh
Labels: approved, lgtm, size/M

#2659 retry all errors for iso download before calling qemu
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2658 run emmissary as a batch build in CI like harbor
  projects/emissary-ingress/emissary/.gitignore
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/buildspecs/batch-build.yml
  projects/emissary-ingress/emissary/docker/linux/combine/Dockerfile
  projects/emissary-ingress/emissary/docker/linux/emissary/Dockerfile
Labels: approved, lgtm, size/M

#2660 fixes retry logic for iso download
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/download_iso.sh
Labels: approved, lgtm, size/M

#2662 quote iso url
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2645 adds check for qemu and updates docs a bit
  build/lib/common.sh
  build/lib/run_target_docker.sh
  docs/development/building-locally.md
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm, size/L

#2661 fixes emissary buildspec
  projects/emissary-ingress/emissary/.gitignore
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/buildspecs/batch-build.yml
Labels: approved, lgtm, size/S

#2664 Skip setting proxy on subscription module, if satellite is part of no_proxy
  projects/aws/image-builder/builder/manifests.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/builder/utils_test.go
Labels: approved, lgtm, size/M

#2668 Bump image-builder git tag
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
Labels: approved, lgtm, size/XS

#2608 refactors helm targets to avoid duplication and improve logging
  Common.mk
  build/lib/helm_build.sh
  build/lib/helm_copy.sh
  build/lib/helm_push.sh
  build/lib/helm_replace.sh
  build/lib/helm_require.sh
  build/lib/image_shasum.sh
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/eks-anywhere-packages/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/metallb/metallb/Makefile
  projects/prometheus/prometheus/Makefile
  projects/tinkerbell/tinkerbell-chart/Makefile
Labels: approved, lgtm, size/L

#2671 use tee to fix digest to tmpfile
  build/lib/common.sh
  build/lib/helm_push.sh
Labels: approved, lgtm, size/S

#2642 supports s3 path prefixes in bucket variable
  build/lib/common.sh
  build/lib/fetch_binaries.sh
Labels: approved, lgtm, size/M

#2665 Add changes for building upgrader image for in-place upgrades
  Makefile
  projects/aws/upgrader/Help.mk
  projects/aws/upgrader/Makefile
  projects/aws/upgrader/buildspecs/batch-build.yml
  projects/aws/upgrader/docker/linux/Dockerfile
  projects/aws/upgrader/upgrade.sh
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2679 Bump capi v1.5.3 and cert-manager v1.13.1
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-disable-cgroupns-private-to-fix-AL2.patch
Labels: approved, lgtm, size/XL

#2683 fixes nightly attribution for upgrader projeect
  Common.mk
Labels: approved, lgtm, size/XS

#2681 Support release-branched projects and passing project name in README version check
  Makefile
  build/lib/readme_check.sh
  projects/emissary-ingress/emissary/README.md
  projects/kubernetes/autoscaler/README.md
  projects/tinkerbell/tinkerbell-chart/README.md
Labels: approved, lgtm, size/M

#2684 Use absolute paths during README check
  Makefile
  build/lib/readme_check.sh
Labels: approved, lgtm, size/S

#2677 support building helm charts to local registry
  .gitignore
  Makefile
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  build/lib/helm_push.sh
  build/lib/helm_require.sh
  build/lib/run_target_docker.sh
  docs/development/building-locally.md
  projects/kubernetes-sigs/image-builder/.gitignore
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/organize_binaries.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/kind/patches/0004-Disable-cgroupns-private-to-fix-cluster-creation-on-.patch
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
Labels: approved, lgtm, size/L

#2686 fixup! Bump harbor version (#2670)
  projects/goharbor/harbor/helm/sedfile.template
Labels: approved, lgtm, size/XS

#2682 standardize batch builds for archd images
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_NSENTER_TAG_FILE
  Makefile
  build/lib/docker/linux/combine/Dockerfile
  build/lib/generate_staging_buildspec.sh
  buildspecs/combine-images.yml
  projects/aws/upgrader/Makefile
  projects/aws/upgrader/buildspecs/batch-build.yml
  projects/aws/upgrader/docker/linux/Dockerfile
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/buildspecs/batch-build.yml
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/buildspecs/batch-build.yml
  projects/goharbor/harbor/docker/linux/combine/Dockerfile
  projects/kubernetes-sigs/metrics-server/Makefile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2676 Add Ref to EKS-D Metrics Server ECR Gallery
  projects/kubernetes-sigs/metrics-server/README.md
Labels: approved, lgtm, size/XS

#2688 refactor ansible retry and timeout after 1h
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/M

#2689 fix stray quote in build-image
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#2690 properly quote stuff
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#2614 Enable verbose logging for image-builder Ansible tasks
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/manifests.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/root.go
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M

#2691 Bump CAPV to v1.7.4
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Add-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/L
