Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-05, with the labels that each got.

#2134 Handle released image-builder building from main
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/XS

#2135 Add tolerations to cap-controller-manager deploy
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Add-tolerations-to-capc-controller-manager-podspec.patch
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/patches/0001-Add-tolerations-to-capx-controller-manager-podspec.patch
Labels: approved, lgtm, size/M

#1881 Update GIT_TAG for hook to the latest one which contains proxy support
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/README.md
Labels: approved, lgtm, size/S

#2139 Update replicatedhq/troubleshoot to v0.62.1
  UPSTREAM_PROJECTS.yaml
  projects/replicatedhq/troubleshoot/ATTRIBUTION.txt
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/GIT_TAG
  projects/replicatedhq/troubleshoot/README.md
  projects/replicatedhq/troubleshoot/patches/0001-Replace-dependency-to-mitigate-license-issues-and-fi.patch
Labels: approved, lgtm, size/XL

#2063 Update cluster-api to v1.4.2
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/cert-manager/cert-manager/patches/0001-Bump-keystore-go-to-v4.4.1.patch
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Implement-Reconcile-mode-for-ClusterResourceSet.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
Labels: approved, lgtm, size/XXL

#2152 Patches maxconn on haproxy config in capd
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
Labels: approved, lgtm, size/L

#2154 Upload SHA-256 checksum of EKS-A admin image for validation
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
Labels: approved, lgtm, size/S

#2157 Fix variable declaration order in export script
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
Labels: approved, lgtm, size/XS

#2158 Ensure source AMI architecture is AMD64
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
Labels: approved, lgtm, size/XS

#2159 Backport EKS-A admin image enhancements
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
Labels: approved, lgtm, size/S

#2162 Update BR release version and admin container
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2160 Updated EKS-D to latest releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2163 Updated EKS-D to latest releases (#2160)
  EKSD_LATEST_RELEASES
Labels: approved, size/S

#2161 Remove 1.22 as a supported release branch
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/image-builder/README.md
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2143 Update flux and all controllers to the GA RC1
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/run_target_docker.sh
  build/lib/update_checksum_docker.sh
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/README.md
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/buildspecs/batch-build.yml
  projects/fluxcd/source-controller/buildspecs/images.yml
  projects/fluxcd/source-controller/docker/build/Dockerfile
  projects/fluxcd/source-controller/docker/linux/Dockerfile
  projects/fluxcd/source-controller/expected_artifacts
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2166 Updates runc to 1.1.7
  UPSTREAM_PROJECTS.yaml
  projects/opencontainers/runc/ATTRIBUTION.txt
  projects/opencontainers/runc/CHECKSUMS
  projects/opencontainers/runc/GIT_TAG
  projects/opencontainers/runc/README.md
Labels: approved, lgtm, size/S

#2167 Updates containerd to 1.6.21
  UPSTREAM_PROJECTS.yaml
  projects/containerd/containerd/ATTRIBUTION.txt
  projects/containerd/containerd/CHECKSUMS
  projects/containerd/containerd/GIT_TAG
  projects/containerd/containerd/README.md
Labels: approved, lgtm, size/M

#2172 Update etcdadm-controller to v1.0.6-rc3
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2173 Update badge versions for projects
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/cilium/cilium/README.md
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/etcdadm/README.md
Labels: approved, lgtm, size/S

#2175 Update badges for projects
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/brancz/kube-rbac-proxy/README.md
  projects/cilium/cilium/README.md
  projects/fluxcd/flux2/README.md
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/README.md
  projects/helm/helm/README.md
  projects/kubernetes-sigs/cri-tools/README.md
  projects/kubernetes-sigs/etcdadm/README.md
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes/cloud-provider-aws/README.md
  projects/rancher/local-path-provisioner/README.md
  projects/vmware/govmomi/README.md
Labels: approved, lgtm, size/M

#2171 Update expected artifacts for cloudstack and raw
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_cloudstack
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_raw
Labels: approved, lgtm, size/XS

#2180 copy cloudstack artifacts from metal EC2 instance to codebuild job
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2181 Ensure artifacts path exists before moving files to it
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2182 Use release branch in artifacts path construction
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2183 Fix image format for cloudstack builds
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2184 Ensure IMAGE_OS and IMAGE_FORMAT env vars are set in KVM builder instance
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2185 Use MAC addr in Bottlerocket net conf
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0009-Use-MAC-address-in-Bottlerocket-network-config.patch
Labels: approved, lgtm, size/M

#2188 Update cilium to v1.12.10
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2189 Fix 1-27 Cluster Autoscaler Reconciling Error
  projects/kubernetes/autoscaler/1-27/helm/patches/0007-Authorize-MachinePool-Operations.patch
Labels: approved, lgtm, size/M

#2191 Bump up etcdadm-controller version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2192 Updating emissary 3.5.1 to 3.6.0
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_TAG_FILE
  UPSTREAM_PROJECTS.yaml
  projects/emissary-ingress/emissary/APPMESH_VERSION
  projects/emissary-ingress/emissary/ATTRIBUTION.txt
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GIT_TAG
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/docker/linux/emissary-image/Dockerfile
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
Labels: approved, lgtm, size/L

#2193 Revert "Update cilium to v1.12.10"
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2195 Add support for configuring custom cert bundles in BR
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR.patch
Labels: approved, lgtm, size/XL

#2197 Patch CAPI to include --filter-cluster flag for clusterctl
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
Labels: approved, lgtm, size/L

#2199 Add 1.27 image builder status
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#2200 Upgrade CAPC v0.4.9-rc4 -> v0.4.9-rc5
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Add-tolerations-to-capc-controller-manager-podspec.patch
Labels: approved, lgtm, size/M, blocker

#2201 Fix typos
  Makefile
Labels: approved, lgtm, size/XS

#2206 [CAPI] Move objects with force move label
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
Labels: approved, lgtm, size/L
