Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-10, with the labels that each got.

#2521 bump git tag of eks-anywhere-packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#2524 Update to latest Rufio:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
Labels: approved, lgtm, size/S

#2526 Bump eks-anywhere-packages
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#2527 Add CAPI labels to machine crd:
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/bmc.tinkerbell.org_machines.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/XS

#2528 Add a readme for the tinkerbell stack chart.
  projects/tinkerbell/tinkerbell-chart/README.md
Labels: approved, lgtm, size/S

#2533 fixes cilium and image-builder builds
  projects/cilium/cilium/build/create_manifests.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/ansible.cfg
Labels: approved, lgtm, size/S

#2539 replaces base_directory with constant relative path
  Makefile
  projects/apache/cloudstack-cloudmonkey/Makefile
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/trivy/Makefile
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-controller/Makefile
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/brancz/kube-rbac-proxy/Makefile
  projects/cilium/cilium/Makefile
  projects/containerd/containerd/Makefile
  projects/distribution/distribution/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/envoyproxy/envoy/Makefile
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/goharbor/harbor/Makefile
  projects/helm/helm/Makefile
  projects/kube-vip/kube-vip/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/metallb/metallb/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/opencontainers/runc/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
  projects/rancher/local-path-provisioner/Makefile
  projects/redis/redis/Makefile
  projects/replicatedhq/troubleshoot/Makefile
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/torvalds/linux/Makefile
  projects/vmware/govmomi/Makefile
Labels: approved, lgtm, size/L

#2536 improves local check by turning into a prereq
  Common.mk
  Makefile
Labels: approved, lgtm, size/M

#2532 adds ensure-dep to makefiles
  Common.mk
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-controller/Makefile
  projects/cilium/cilium/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/rufio/Makefile
Labels: approved, lgtm, size/L

#2535 improves mac gnu variant detection
  Common.mk
  build/lib/common.sh
  build/lib/create_release_checksums.sh
  build/lib/generate_help_body.sh
  build/lib/helm_pull.sh
  build/lib/helm_push.sh
  build/lib/helm_replace.sh
  build/lib/readme_check.sh
  build/lib/update_checksums.sh
  build/lib/validate_artifacts.sh
  build/lib/version.sh
Labels: approved, lgtm, size/L

#2542 removes release_branch from harbor docker files
  projects/goharbor/harbor/docker/linux/harbor-registry/Dockerfile
  projects/goharbor/harbor/docker/linux/harbor-registryctl/Dockerfile
  projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile
Labels: approved, lgtm, size/XS

#2540 sets a static build user for prometheus tag
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/Makefile
Labels: approved, lgtm, size/S

#2537 adds deferred variable cache to common.mk
  Common.mk
  Makefile
  projects/apache/cloudstack-cloudmonkey/Makefile
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/trivy/Makefile
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-controller/Makefile
  projects/aws/image-builder/Makefile
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/brancz/kube-rbac-proxy/Makefile
  projects/cert-manager/cert-manager/Makefile
  projects/cilium/cilium/Makefile
  projects/containerd/containerd/Makefile
  projects/distribution/distribution/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/envoyproxy/envoy/Makefile
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/helm-controller/Makefile
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/notification-controller/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/goharbor/harbor/Makefile
  projects/helm/helm/Makefile
  projects/kube-vip/kube-vip/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/metallb/metallb/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/opencontainers/runc/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
  projects/rancher/local-path-provisioner/Makefile
  projects/redis/redis/Makefile
  projects/replicatedhq/troubleshoot/Makefile
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/torvalds/linux/Makefile
  projects/vmware/govmomi/Makefile
Labels: approved, lgtm, size/L

#2545 skips buildkit check in codebuild
  Common.mk
Labels: approved, size/XS

#2538 adds shell trace to common.mk
  Common.mk
  Makefile
  build/lib/make_shell_trace.sh
Labels: approved, lgtm, size/M

#2547 Upgrade Cilium to v1.12.14
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2531 [Image Builder] Add download manifest command for airgapped builds
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/manifests.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/download.go
  projects/aws/image-builder/cmd/downloadmanifests.go
Labels: approved, lgtm, size/L

#2551 Update go mods on image-builder
  projects/aws/image-builder/go.mod
  projects/aws/image-builder/go.sum
Labels: approved, lgtm, size/L

#2546 refactors logging to use annonation style
  Common.mk
  build/lib/common.sh
  build/lib/create_attribution.sh
  build/lib/make_shell.sh
  build/lib/make_shell_trace.sh
  projects/containerd/containerd/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
Labels: approved, lgtm, size/L

#2552 Update bottlerocket bootstrap go mod
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/go.sum
Labels: approved, lgtm, size/XL

#2556 fixes image-builder home directory permissions
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
Labels: approved, lgtm, size/XS

#2553 Deprecate 1.23
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/image-builder/README.md
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2564 remove workaround for old ansible version
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#2565 Fix output image glob pattern for CloudStack image builds
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/XS

#2566 bump eksd
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2567 Revert changes to CloudStack output glob
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/S

#2570 Fix readonly variable for bundles url override
  build/lib/eksa_releases.sh
Labels: approved, lgtm, size/XS

#2571 Update Rufio:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
Labels: approved, lgtm, size/S

#2558 Add RHEL support for Nutanix to image-builder
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0015-adds-support-for-raw-ubuntu-22.04-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0016-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
  projects/kubernetes-sigs/image-builder/patches/0017-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0018-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch
  projects/kubernetes-sigs/image-builder/patches/0019-Add-proxy-register-with-satellite-and-pull-packages-.patch
  projects/kubernetes-sigs/image-builder/patches/0020-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch
  projects/kubernetes-sigs/image-builder/patches/0021-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0022-TEMP-skip-python-3.9-check-if-ansible-already-instal.patch
  projects/kubernetes-sigs/image-builder/patches/0023-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0024-Fix-redhat-9-cloud-init-feature-flags-bug.patch
  projects/kubernetes-sigs/image-builder/patches/0025-Fix-ensure-iptables-present-for-rhel.patch
Labels: approved, lgtm, size/L, ok-to-test

#2573 Bump Cloud Provider Vsphere
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-vsphere/1-28/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-28/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-28/GIT_TAG
Labels: approved, lgtm, size/M

#2578 Bump CRI Tools to v1.28.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cri-tools/ATTRIBUTION.txt
  projects/kubernetes-sigs/cri-tools/CHECKSUMS
  projects/kubernetes-sigs/cri-tools/GIT_TAG
  projects/kubernetes-sigs/cri-tools/README.md
Labels: approved, lgtm, size/L

#2574 build bootconfig for both amd and arm using batch build
  Makefile
  projects/torvalds/linux/Makefile
  projects/torvalds/linux/buildspecs/batch-build.yml
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/M

#2579 fixes bootconfig expected artifacts
  projects/torvalds/linux/Makefile
  projects/torvalds/linux/expected_artifacts
Labels: approved, lgtm, size/XS

#2580 minor image builder improvements
  Common.mk
  build/lib/common.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M

#2581 builds arm images for tink actions
  projects/tinkerbell/hub/Makefile
Labels: approved, lgtm, size/XS

#2582 Add default buildspec definition to batch buildspecs
  Makefile
  build/lib/generate_staging_buildspec.sh
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/containerd/containerd/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  projects/opencontainers/runc/buildspecs/batch-build.yml
  projects/torvalds/linux/buildspecs/batch-build.yml
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2577 Fix interface determination in Tinkerbell writefile action
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0013-Fix-net-interface-lookup.patch
Labels: approved, lgtm, size/L

#2586 Add kube version and os version info in the output file
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/XS

#2572 Support for Air-gapped Image building
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/manifests.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/L

#2588 Update Cilium to v1.12.15
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2590 Prune OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#2591 Validate airgapped configs only if running in airgapped mode
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/M

#2585 adds support for buildx if buildctl is missing
  Common.mk
  build/lib/buildkit.sh
Labels: approved, lgtm, size/M

#2596 Bump CAPC
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/M

#2599 fix depend-on for hub on bootconfig
  projects/tinkerbell/hub/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#2601 Add validations for staging buildspec
  Makefile
  build/lib/validate_release_buildspecs.sh
Labels: approved, lgtm, size/M

#2603 Fix config file path for Nutanix image builds
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
Labels: approved, lgtm, size/XS

#2602 Add 1-28 build status
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#2609 Update CAPAS to v0.1.27
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/README.md
Labels: approved, lgtm, size/XS

#2611 Bump etcdadm controllers to v1.0.15 and v1.0.10
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/GOLANG_VERSION
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/GOLANG_VERSION
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/M

#2519 transparently use docker targets when building
  Common.mk
  Makefile
  build/lib/buildkit.sh
  build/lib/common.sh
  build/lib/docker/linux/cgo/Dockerfile
  build/lib/generate_help_body.sh
  build/lib/make_shell.sh
  build/lib/prepare_build_container_user.sh
  build/lib/run_target_docker.sh
  docs/development/building-locally.md
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes/autoscaler/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/prometheus/prometheus/Makefile
  projects/prometheus/prometheus/build/cp_npm_licenses.sh
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/build/create_manifests.sh
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/torvalds/linux/Makefile
Labels: approved, lgtm, size/XL

#2617 Make Python site-packages folder readable to non-root users
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
Labels: approved, lgtm, size/XS

#2615 support pushing/pulling from private s3
  Common.mk
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  build/lib/upload_artifacts.sh
  projects/kubernetes-sigs/kind/build/base-image-build-args.sh
Labels: approved, lgtm, size/M

#2618 Bump eks-anywhere-packages version
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/S

#2417 adds retries and timeout to packer image-builder
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0015-adds-support-for-raw-ubuntu-22.04-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0016-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
  projects/kubernetes-sigs/image-builder/patches/0017-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0018-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch
  projects/kubernetes-sigs/image-builder/patches/0019-Add-proxy-register-with-satellite-and-pull-packages-.patch
  projects/kubernetes-sigs/image-builder/patches/0020-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch
  projects/kubernetes-sigs/image-builder/patches/0021-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0022-TEMP-skip-python-3.9-check-if-ansible-already-instal.patch
  projects/kubernetes-sigs/image-builder/patches/0023-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0024-Fix-redhat-9-cloud-init-feature-flags-bug.patch
  projects/kubernetes-sigs/image-builder/patches/0025-Fix-ensure-iptables-present-for-rhel.patch
  projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch
Labels: approved, lgtm, size/L

#2621 bumps ssh timeout for ova to 40 mins instead of 20
  projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch
Labels: approved, lgtm, size/S
