Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-06, with the labels that each got.

#2209 Retrieve default network interface name using mac address via IMDSv2 …
  projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
Labels: approved, lgtm, size/S, needs-ok-to-test, ok-to-test

#2208 Update EKSD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2216 Add patch for BR support in new CAPV version
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Add-capv-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0002-set-user-agent-for-vsphere-api-calls.patch
Labels: approved, lgtm, size/M

#2210 bumps flux to ga rc.5
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/patches/0001-Replace-github.com-homeport-dyff-with-commit-to-work.patch
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/README.md
Labels: approved, lgtm, size/M

#2225 adds support for grealpath on mac
  build/lib/create_release_checksums.sh
  build/lib/validate_artifacts.sh
Labels: approved, lgtm, size/S

#2228 Updating cloud-provider version
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-aws/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/GIT_TAG
  projects/kubernetes/cloud-provider-aws/README.md
Labels: approved, lgtm, size/S

#2156 Make image-builder check out a specific commit when running builds
  build/lib/eksa_releases.sh
  build/lib/eksd_releases.sh
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/go.mod
  projects/aws/image-builder/go.sum
Labels: approved, lgtm, size/L

#2232 Update cloud-provider-aws to use k8 specific build
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-aws/1-23/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-23/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-24/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-26/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-27/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-27/GIT_TAG
  projects/kubernetes/cloud-provider-aws/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/Help.mk
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-aws/README.md
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2227 removes vsphere csi drvier
  README.md
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/vsphere-csi-driver/.gitignore
  projects/kubernetes-sigs/vsphere-csi-driver/ATTRIBUTION.txt
  projects/kubernetes-sigs/vsphere-csi-driver/CHECKSUMS
  projects/kubernetes-sigs/vsphere-csi-driver/GIT_TAG
  projects/kubernetes-sigs/vsphere-csi-driver/Help.mk
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/kubernetes-sigs/vsphere-csi-driver/README.md
  projects/kubernetes-sigs/vsphere-csi-driver/docker/linux/csi-driver/Dockerfile
  projects/kubernetes-sigs/vsphere-csi-driver/docker/linux/csi-syncer/Dockerfile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2233 Updating dependency versions
  UPSTREAM_PROJECTS.yaml
  projects/apache/cloudstack-cloudmonkey/ATTRIBUTION.txt
  projects/apache/cloudstack-cloudmonkey/CHECKSUMS
  projects/apache/cloudstack-cloudmonkey/GIT_TAG
  projects/apache/cloudstack-cloudmonkey/Makefile
  projects/apache/cloudstack-cloudmonkey/README.md
  projects/tinkerbell/hook/Makefile
Labels: approved, lgtm, size/M

#2235 Updating tinkerbell/hub
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hub/CEXEC_ATTRIBUTION.txt
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/GIT_TAG
  projects/tinkerbell/hub/IMAGE2DISK_ATTRIBUTION.txt
  projects/tinkerbell/hub/KEXEC_ATTRIBUTION.txt
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/hub/OCI2DISK_ATTRIBUTION.txt
  projects/tinkerbell/hub/README.md
  projects/tinkerbell/hub/WRITEFILE_ATTRIBUTION.txt
Labels: approved, lgtm, size/M

#2236 Split eks-anywhere-packages to have K8 version specific builds
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#2238 Update fetch_binaries for eksd
  build/lib/fetch_binaries.sh
Labels: approved, lgtm, size/XS

#2239 Update eks-anywhere-packages IMAGE_TAG and HELM_TAG to include release branch
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/XS

#2241 Make eks-anywhere-packages k8 version agnostic
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2226 cleans up go version for go-licenses flow
  build/lib/common.sh
  build/lib/install_go_versions.sh
Labels: approved, lgtm, size/S

#2246 removes projects we arent building from buildspecs
  projects/kubernetes-sigs/vsphere-csi-driver/Makefile
  projects/tinkerbell/hub/Makefile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/M

#2249 Update eks-anywhere-packages GIT_TAG
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/S

#2251 Bump up etcdadm-controller to add concurrency
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2252 Checksums files update main 3f6dda3163faa55f42d1826f44bbc0ae88c9a316
  build/lib/install_go_versions.sh
  projects/apache/cloudstack-cloudmonkey/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/image-builder/CHECKSUMS
  projects/brancz/kube-rbac-proxy/CHECKSUMS
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/containerd/containerd/CHECKSUMS
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/source-controller/CHECKSUMS
  projects/goharbor/harbor/CHECKSUMS
  projects/helm/helm/CHECKSUMS
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cri-tools/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-26/CHECKSUMS
  projects/kubernetes/autoscaler/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-27/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/opencontainers/runc/CHECKSUMS
  projects/rancher/local-path-provisioner/CHECKSUMS
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/rufio/CHECKSUMS
Labels: size/L

#2256 Fix metadata service queries treating 404s as OK
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0010-Handle-non-200-status-codes-from-metadata-service.patch
Labels: approved, lgtm, size/M

#2242 bumps eks-d releases
  EKSD_LATEST_RELEASES
Labels: approved, do-not-merge/hold, size/S

#2258 Add notifier action
  .github/workflows/baseimage-pr-notifier.yaml
Labels: approved, lgtm, size/S

#2260 Fix Kubernetes version for EKS-D v1.24 latest release
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#2263 Backport EKS-D kube version updates
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#2265 Fixing config issue emissary helm chart
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
Labels: approved, lgtm, size/L

#2266 adds validation for eks-d releases file
  Makefile
  build/lib/validate_eksd_releases.sh
Labels: approved, lgtm, size/M

#2264 Bump image-builder to v0.1.16
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0016-Ensure-the-correct-Packer-binary-is-used-for-image-b.patch
Labels: approved, lgtm, size/L, needs-ok-to-test

#2274 Support installing extra Debian packages and RPMs during image builds
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/types.go
Labels: approved, lgtm, size/S

#2273 Bump cluster-api, cert-manager and kind to latest versions.
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/simple_create_tarballs.sh
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
Labels: approved, lgtm, size/XL

#2277 Revert "Bump cluster-api, cert-manager and kind to latest versions. (…
  UPSTREAM_PROJECTS.yaml
  build/lib/common.sh
  build/lib/simple_create_tarballs.sh
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
Labels: approved, lgtm, size/XL

#2219 adds support for ubuntu 2204 in image-builder
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
  projects/kubernetes-sigs/image-builder/.gitignore
  projects/kubernetes-sigs/image-builder/Help.mk
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/build_qemu_rhel_local.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_cloudstack
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_raw
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0015-Shrink-qemu-ubuntu-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0017-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
Labels: approved, lgtm, size/XXL

#2281 [PR BOT] Update base image in tag file(s) (#2268)
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_CSI_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_TAG_FILE
Labels: approved, lgtm, size/S

#2282 fixes cloudstack output folder for image-builder
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2283 fixes ami image build upload
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS
