Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-02, with the labels that each got.

#1803 Add imdsv2 Flags for Bare Metal Image Build
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#1806 Patch image-builder to add IMDS configuration support for Packer builds
  projects/kubernetes-sigs/image-builder/patches/0012-Add-instance-metadata-options-to-Packer-config.patch
Labels: approved, lgtm, size/M

#1809 Pin kustomize version to v4.5.7
  Common.mk
Labels: approved, lgtm, size/XS

#1811 Bumping packages to v0.2.29
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1671 Update Tinkerbell stack images to latest release versions
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Update-tinkerbell-tink-version.patch
  projects/tinkerbell/hegel/ATTRIBUTION.txt
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/README.md
  projects/tinkerbell/rufio/patches/0001-Temp-fix-for-ipmitool-status-message.patch
  projects/tinkerbell/tink/ATTRIBUTION.txt
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/README.md
Labels: approved, lgtm, size/XXL

#1707 Update Tinkerbell chart with new image configuration
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/bmc.tinkerbell.org_jobs.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/bmc.tinkerbell.org_machines.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/bmc.tinkerbell.org_tasks.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/cluster_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/cluster_role_binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/deprecated-baseboardmanagement-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/leader_election_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/leader_election_role_binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/manager_configmap.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/secrets-viewer-role-binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/secrets-viewer-role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/service_account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/cluster_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/cluster_role_binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/leader_election_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/leader_election_rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/service_account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/tinkerbell.org_hardware.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/tinkerbell.org_templates.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/tinkerbell.org_workflows.yaml
  projects/tinkerbell/tinkerbell-chart/chart/values.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/L

#1812 Tag EC2 instances and key-pairs with CI job ID
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#1805 Add support for configuring NTP servers on bottlerocket through CAPI
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
Labels: approved, lgtm, size/L

#1824 Cherry-pick base image updates
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_CSI_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GOLANG_COMPILER_1.17_GCC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_TAG_FILE
Labels: approved, lgtm, size/S

#1826 Bumps to latest eks-d releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1814 Updated EKS-D to 1.25-eks-5
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#1827 bump eks-d releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1830 Patch boots deployment strategy to 'Recreate'
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/XS

#1823 Add 1-26 as a supported release branch
  Common.mk
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-26/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-26/helm/sedfile.template
  projects/kubernetes/cloud-provider-vsphere/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-26/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-26/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#1825 Add cache cleaning target
  Common.mk
  projects/emissary-ingress/emissary/Makefile
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/S

#1835 bumping packages to 0.2.30
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1840 Make owners file asciibetical
  OWNERS
Labels: approved, lgtm, size/XS

#1834 Add bhavitha to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1837 Patch image-builder to rename Snow node AMI
  projects/kubernetes-sigs/image-builder/patches/0012-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
Labels: approved, lgtm, size/S

#1846 Update prometheus to v2.41.0
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/GIT_TAG
  projects/prometheus/prometheus/Makefile
  projects/prometheus/prometheus/README.md
Labels: approved, lgtm, size/S

#1819 Update image builder README to include 1.25
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#1847 Cleanup repo only in non-Codebuild environments
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
Labels: approved, lgtm, size/XS

#1856 Add --tls=false to Tinkerbell chart
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/deployment.yaml
Labels: approved, lgtm, size/XS

#1857 Adding 1-25 BR to release-0.14 branch
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#1858 Set hostname for BR nodes
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0027-set-hostname-for-BR-nodes.patch
Labels: approved, lgtm, size/L

#1859 Add sudo to Kind base image
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
Labels: approved, lgtm, size/S

#1860 Enforce IMDSv2 in EKS-A Admin image builder AMI
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
Labels: approved, lgtm, size/XS

#1863 Add verify script to verify the tinkerbell chart
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/tinkerbell/tinkerbell-chart/scripts/verify.sh
Labels: approved, lgtm, size/M

#1870 Add per-call timeout for WaitFor200 check
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/utils/waiters.go
Labels: approved, lgtm, size/S, ok-to-test

#1877 Fix binary format on arm
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/docker/linux/Dockerfile
Labels: approved, lgtm, size/XS

#1879 Update bottlerocket-bootstrap Dependencies
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/go.sum
Labels: approved, lgtm, size/M

#1883 Bump packages to Go 1.19
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/S

#1876 Update to newest release of eksd
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1889 Manual cherrypick update of eksd (#1876)
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1891 Update Nutanix CAPX Provider to v1.1.3
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/L, ok-to-test
