Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-12, with the labels that each got.

#2700 Build aws/image-builder with Go 1.21
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/GOLANG_VERSION
Labels: approved, lgtm, size/S

#2701 Update build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#2699 Fix upgrade script to delete coredns config for all the CPs
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/M

#2704 fixes building kind in codebuild
  build/lib/common.sh
Labels: approved, lgtm, size/XS

#2705 fix raw rhel builds
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/patches/0027-disable-gpg-for-extra-rpms.patch
Labels: approved, lgtm, size/S

#2707 updates to latest eksd (#2706)
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2373 Add project version tracker CLI tool
  .gitignore
  tools/version-tracker/.gitignore
  tools/version-tracker/Makefile
  tools/version-tracker/README.md
  tools/version-tracker/SKIPPED_PROJECTS
  tools/version-tracker/cmd/display.go
  tools/version-tracker/cmd/listprojects.go
  tools/version-tracker/cmd/root.go
  tools/version-tracker/cmd/upgrade.go
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/main.go
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/types/types.go
  tools/version-tracker/pkg/util/command/command.go
  tools/version-tracker/pkg/util/file/file.go
  tools/version-tracker/pkg/util/logger/logger.go
  tools/version-tracker/pkg/util/slices/slices.go
  tools/version-tracker/pkg/util/tar/tar.go
  tools/version-tracker/pkg/util/version/version.go
Labels: approved, lgtm, size/XXL

#2709 add rayzhng to owners
  OWNERS
Labels: approved, lgtm, size/XS

#2675 upgrade cilium to 1.13.9
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2711 Add project version upgrade batch buildspec
  Common.mk
  Makefile
  buildspecs/upgrade-buildspec.yml
  projects/aws-containers/hello-eks-anywhere/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/eks-anywhere/Makefile
  projects/aws/image-builder/Makefile
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/aws/upgrader/Makefile
  projects/cilium/cilium/Makefile
  projects/distribution/distribution/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/envoyproxy/envoy/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/metallb/metallb/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
  projects/redis/redis/Makefile
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tinkerbell-chart/Makefile
  projects/torvalds/linux/Makefile
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#2712 Configure author for Git commit step
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/git/git.go
Labels: approved, lgtm, size/M

#2730 Updating to latest tag for etcdadm controller
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2732 Run upgrade CLI in verbose mode in CodeBuild
  buildspecs/upgrade-buildspec.yml
  tools/version-tracker/Makefile
Labels: size/XS

#2729 Bump capi to v1.6.0 and cert-manager to v1.13.2
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-disable-cgroupns-private-to-fix-AL2.patch
Labels: approved, lgtm, size/XXL

#2736 Skip leftover packages in upgrade job, handle up-to-date remote when pushing
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/trivy/Makefile
  projects/aws/eks-anywhere-packages/Makefile
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/M

#2737 Bump Flux notification-controller and source-controller to latest release
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/notification-controller/ATTRIBUTION.txt
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/notification-controller/patches/0001-Replace-unknown-go-crypto-revision-with-correct-pseu.patch
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/patches/0001-Replace-unknown-go-crypto-and-go-fuzz-headers-revisi.patch
Labels: approved, lgtm, size/XXL

#2750 Include packages projects in upgrader list
  projects/aquasecurity/harbor-scanner-trivy/Makefile
  projects/aquasecurity/trivy/Makefile
  projects/aws-observability/aws-otel-collector/Makefile
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/distribution/distribution/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/metallb/metallb/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L

#2702 cleans up helm chart building and pushing
  build/lib/buildkit.sh
  build/lib/helm_push.sh
  build/lib/helm_require.sh
  build/lib/image_shasum.sh
Labels: approved, lgtm, size/L

#2766 Fix logic to get latest GitHub release for a project
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L

#2769 fixes skopeo for helm chart tagging
  build/lib/setup.sh
  config/policy.json
Labels: approved, lgtm, size/S

#2771 Merge checksums when building for different architectures separately
  buildspecs/upgrade-buildspec.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XS

#2768 updates to latest eksd
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2773 adds platform warning when building images
  build/lib/buildkit.sh
  build/lib/common.sh
Labels: approved, lgtm, size/M

#2780 Fix image tag for bottlerocket control container
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
Labels: approved, lgtm, size/XS

#2782 Add me as owner
  OWNERS
Labels: approved, lgtm, size/XS

#2781 update permissions for the upgrader script to run in container
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/XS

#2783 [release-0.18] bump eksd
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2770 Image-builder: Update kernel and keep only 1 kernel on redhat machines
  projects/kubernetes-sigs/image-builder/patches/0028-Remove-old-kernels.patch
Labels: approved, lgtm, size/M

#2784 Use EKS-D v1.29 prod release assets
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#2787 Ignore nvram when downloading from vSphere content libraries
  projects/kubernetes-sigs/image-builder/patches/0029--Export-ova-file-independently-to-ignore-nvram-file-t.patch
Labels: approved, lgtm, size/S

#2788 Bump fluxcd/flux2, fluxcd/helm-controller and fluxcd/kustomize-controller to latest release
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/patches/0001-Replace-unknown-go-crypto-revision-with-correct-pseu.patch
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/Makefile
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/source-controller/README.md
Labels: approved, lgtm, size/XXL, area/dependencies

#2793 Check for release branch in combine-images buildspec
  buildspecs/combine-images.yml
Labels: approved, lgtm, size/XS

#2797 Download and include the nvram in OVAs:
  projects/kubernetes-sigs/image-builder/patches/0030-Download-and-include-the-nvram.patch
Labels: approved, lgtm, size/S
