Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-01, with the labels that each got.

#1698 Bump CAPAS to 0.1.15
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1692 update EKS-D to latest releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1699 Add rcrozean to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#1700 Upgrade snow provider to v0.1.16
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1702 Add metrics-server 1-25
  projects/kubernetes-sigs/metrics-server/1-25/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-25/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#1704 Bump CAPAS to 0.1.17
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/M

#1708 Make bottlerocket admin, control, custom bootstrap containers mutable…
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Fix-the-issue-of-passing-taints-to-kubeadm.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Implement-Reconcile-mode-for-ClusterResourceSet.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-bottlerocket-custom-bootstrap-containers-config.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Support-configuring-bottlerocket-admin-container-image.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Make-bottlerocket-admin-control-bootstrap-containers-mutable.patch
Labels: approved, lgtm, size/L

#1706 Add Autoscaler 1-25
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/autoscaler/1-25/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/GIT_TAG
  projects/kubernetes/autoscaler/1-25/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-25/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-25/LICENSES
  projects/kubernetes/autoscaler/1-25/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-25/helm/schema.json
  projects/kubernetes/autoscaler/1-25/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#1710 add zafs23 in OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1705 Adds rerun to cgo docker build
  Common.mk
  build/lib/common.sh
Labels: approved, lgtm, size/M

#1712 Bump up binfmt image to latest
  build/lib/setup.sh
Labels: approved, lgtm, size/XS

#1694 Adds slash hold to add label instead of API labels arg
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/XS

#1713 Bump CAPAS version to 0.1.18
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1716 Mark etcd machine status running after etcd ready label exists
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Fix-the-issue-of-passing-taints-to-kubeadm.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Implement-Reconcile-mode-for-ClusterResourceSet.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-bottlerocket-custom-bootstrap-containers-config.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Support-configuring-bottlerocket-admin-container-image.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Make-bottlerocket-admin-control-bootstrap-containers-mutable.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Mark-etcd-machine-status-to-running-after-etcd-ready-label.patch
Labels: approved, lgtm, size/L

#1717 Bump CAPAS to 0.1.19
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1720 Bump etcd controller version
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#1719 Bumps CAPC to new commit with bug fix
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1725 cherry pick CAPC bumps
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1724 Patch cloud-init on RHEL to wait for network manager online systemd service
  projects/kubernetes-sigs/image-builder/patches/0011-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
Labels: approved, lgtm, size/M

#1727 Bump CAPAS to 0.1.20
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1728 Revert "Bumps CAPC to new commit with bug fix (#1719)"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1730 Revert "cherry pick CAPC bumps"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1735 Bumping packages to 0.2.23
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1736 Update EKS-D versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1732 Bumps CAPC to v0.4.9-rc4
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1737 Bumps CAPC to v0.4.9-rc4
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#1718 Fixes licenses issues that were hidden by bug in go-licenses
  Common.mk
  build/lib/common.sh
  build/lib/gather_licenses.sh
  build/lib/install_go_versions.sh
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/prometheus/node_exporter/ATTRIBUTION.txt
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/node_exporter/build/sed_replace.sh
  projects/prometheus/prometheus/ATTRIBUTION.txt
  projects/prometheus/prometheus/Makefile
  projects/prometheus/prometheus/build/fix_go_licenses.sh
Labels: lgtm, do-not-merge/hold, size/L

#1739 Update node_exporter to v1.5.0
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/node_exporter/ATTRIBUTION.txt
  projects/prometheus/node_exporter/CHECKSUMS
  projects/prometheus/node_exporter/GIT_TAG
  projects/prometheus/node_exporter/patches/0001-update-go-mod.patch
Labels: approved, lgtm, size/M

#1742 bumping packages to 0.2.24
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1747 add support for authenticated registry pulls for BR
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0026-add-support-for-registry-credentials.patch
Labels: approved, lgtm, size/L

#1749 Revert "[release-0.14] add support for authenticated registry pulls for BR"
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0026-add-support-for-registry-credentials.patch
Labels: approved, lgtm, size/L

#1750 Bump CAPAS to 0.1.21
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1753 Update eks-anywhere-packages GIT_TAG
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1755 Breaks part source controller into batch build
  Common.mk
  Makefile
  build/lib/common.sh
  build/lib/generate_staging_buildspec.sh
  build/lib/upload_artifacts.sh
  build/lib/validate_artifacts.sh
  projects/cilium/cilium/build/upload_artifacts.sh
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/build/upload_artifacts.sh
  projects/fluxcd/source-controller/buildspecs/batch-build.yml
  projects/fluxcd/source-controller/buildspecs/binaries.yml
  projects/fluxcd/source-controller/buildspecs/images.yml
  projects/fluxcd/source-controller/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/L

#1740 Update Prometheus to v2.41.0
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/ATTRIBUTION.txt
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/GIT_TAG
  projects/prometheus/prometheus/README.md
Labels: approved, lgtm, size/XXL

#1752 Update CAPX to v1.1.1
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
Labels: approved, lgtm, size/S, ok-to-test

#1758 Sets compute type for arm code build instances
  UPSTREAM_PROJECTS.yaml
  build/lib/generate_staging_buildspec.sh
  projects/fluxcd/source-controller/buildspecs/batch-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#1691 Patch locale warning so it only shows when relevant
  Common.mk
  Makefile
Labels: approved, lgtm, do-not-merge/hold, size/S

#1756 Patch for 1.21 autoscaler for cve-2021-3538
  projects/kubernetes/autoscaler/1-21/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-21/CHECKSUMS
  projects/kubernetes/autoscaler/1-21/patches/0003-Removing-azure-provider-from-1.21-for-cve-2021-3538.patch
Labels: approved, lgtm, size/XXL

#1770 Update how to deal with CRDs for packages
  docs/development/packages/update-helm-charts.md
Labels: approved, lgtm, size/XS

#1763 Add subnet ID field to AMI build config
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/S

#1772 Upgrade instance type to t2
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#1769 Fix for setup-packer-configs-ova error
  build/lib/eksa_releases.sh
Labels: approved, lgtm, size/XS, ok-to-test, do-not-merge/invalid-commit-message

#1762 Update for enabling tagged VLAN support in Tinkerbell stack.
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/deployment.yaml
Labels: approved, lgtm, size/M

#1780 Vlan support
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/README.md
Labels: approved, lgtm, size/S

#1783 Add GO_LDFLAGS for prometheus
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/Makefile
Labels: approved, lgtm, size/S

#1785 Update the tags to match the tinkerbell helm chart versions
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/XS

#1784 Revert to previous version:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/HOOK_BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/HOOK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/README.md
Labels: approved, lgtm, size/S

#1788 Update Tinkerbell Hook:
  UPSTREAM_PROJECTS.yaml
  build/lib/generate_projects_list.sh
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/HOOK_BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/HOOK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/README.md
Labels: approved, lgtm, size/S

#1761 Add build logic for Bottlerocket AWS variants
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ami_bottlerocket
  release/staging-build.yml
Labels: approved, lgtm, size/L

#1789 Fix bad deployment env name/value pair
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/deployment.yaml
Labels: approved, lgtm, size/XS

#1790 Update missing tinkerbell chart version reference.
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/XS

#1791 update vlan interface logic
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0007-Update-vlan-checking.patch
Labels: approved, lgtm, size/M

#1795 Fix netplan VLAN file creation
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/patches/0008-Fix-netplan-vlan-file.patch
Labels: approved, lgtm, size/M

#1796 Update ADOT to v0.25.0
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/helm/patches/0001-image-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0002-namespace-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/L

#1793 Bump EKSD releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#1797 Update ADOT json validation schema
  projects/aws-observability/aws-otel-collector/helm/schema.json
Labels: approved, lgtm, size/XXL

#1798 Update BR release version and admin container
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#1801 Manual cherry pick of autoscaler cve fixes for release 0.14
  projects/kubernetes/autoscaler/1-21/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-21/CHECKSUMS
  projects/kubernetes/autoscaler/1-21/patches/0002-Fix-CVE-2021-3538-for-version-1.21.patch
  projects/kubernetes/autoscaler/1-21/patches/0003-Removing-azure-provider-from-1.21-for-cve-2021-3538.patch
  projects/kubernetes/autoscaler/1-22/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-22/CHECKSUMS
  projects/kubernetes/autoscaler/1-22/patches/0001-Fix-CVE-2021-3538-for-version-1.22.patch
  projects/kubernetes/autoscaler/1-23/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-23/CHECKSUMS
  projects/kubernetes/autoscaler/1-23/patches/0001-Fix-CVE-2021-3538-for-version-1.23.patch
  projects/kubernetes/autoscaler/1-24/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-24/CHECKSUMS
  projects/kubernetes/autoscaler/1-24/patches/0003-Fix-CVE-2021-3538-for-version-1.24.patch
  projects/kubernetes/autoscaler/1-25/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/patches/0001-Fix-CVE-2021-3538-for-version-1.25.patch
Labels: approved, lgtm, size/XXL

#1800 add support for authenticated registry pulls for BR (#1747)
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0026-add-support-for-registry-credentials.patch
Labels: approved, lgtm, size/L
