Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-04, with the labels that each got.

#2069 Update cilium to v1.11.15
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#2073 Add 1.26 image builder status
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#2076 fix trivy cve
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/L

#2077 fix harbor-trivy cve
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/XXL

#2007 Switches to al2023 for the kind image to fix cgroups v2
  Common.mk
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
Labels: approved, lgtm, size/M

#2086 Adds builds for containerd and runc
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/containerd/containerd/.gitignore
  projects/containerd/containerd/ATTRIBUTION.txt
  projects/containerd/containerd/CHECKSUMS
  projects/containerd/containerd/GIT_TAG
  projects/containerd/containerd/Help.mk
  projects/containerd/containerd/Makefile
  projects/containerd/containerd/README.md
  projects/containerd/containerd/buildspecs/batch-build.yml
  projects/containerd/containerd/expected_artifacts
  projects/opencontainers/runc/.gitignore
  projects/opencontainers/runc/ATTRIBUTION.txt
  projects/opencontainers/runc/CHECKSUMS
  projects/opencontainers/runc/GIT_TAG
  projects/opencontainers/runc/Help.mk
  projects/opencontainers/runc/Makefile
  projects/opencontainers/runc/README.md
  projects/opencontainers/runc/buildspecs/batch-build.yml
  projects/opencontainers/runc/expected_artifacts
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2091 Bumping cloud-provider-aws to version 1.27
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-aws/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/GIT_TAG
  projects/kubernetes/cloud-provider-aws/expected_artifacts
Labels: approved, lgtm, size/M

#2094 Do not delete on upload for runc/containerd
  projects/containerd/containerd/Makefile
  projects/opencontainers/runc/Makefile
Labels: approved, lgtm, size/XS

#2095 includes runc in containerd tarball to match upstream
  Makefile
  build/lib/generate_staging_buildspec.sh
  projects/containerd/containerd/Makefile
  projects/containerd/containerd/build/create_tarballs.sh
  release/staging-build.yml
Labels: approved, lgtm, size/M

#2088 Updated to the latest versions for EKS-D
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2085 Remove Unused Autoscaler Cloud Providers
  projects/kubernetes/autoscaler/1-22/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-22/CHECKSUMS
  projects/kubernetes/autoscaler/1-22/patches/0002-Fix-CVE-2022-1996-for-1.22.patch
  projects/kubernetes/autoscaler/1-22/patches/0003-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-22/patches/0004-Remove-Deps-for-Other-Cloud-Providers.patch
  projects/kubernetes/autoscaler/1-23/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-23/CHECKSUMS
  projects/kubernetes/autoscaler/1-23/patches/0003-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-23/patches/0004-Remove-Deps-for-Other-Cloud-Providers.patch
  projects/kubernetes/autoscaler/1-24/CHECKSUMS
  projects/kubernetes/autoscaler/1-24/patches/0004-Fix-CVE-2022-1996-for-1.24.patch
  projects/kubernetes/autoscaler/1-24/patches/0005-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-24/patches/0006-Remove-Deps-for-Other-Cloud-Providers.patch
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/patches/0002-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-25/patches/0003-Remove-Deps-for-Other-Cloud-Providers.patch
  projects/kubernetes/autoscaler/1-26/CHECKSUMS
  projects/kubernetes/autoscaler/1-26/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-26/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/XXL

#2087 Updates kind to 0.18.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/rancher/local-path-provisioner/ATTRIBUTION.txt
  projects/rancher/local-path-provisioner/CHECKSUMS
  projects/rancher/local-path-provisioner/GIT_TAG
  projects/rancher/local-path-provisioner/Makefile
Labels: approved, lgtm, size/L

#2105 Revert "Updates kind to 0.18.0"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/rancher/local-path-provisioner/ATTRIBUTION.txt
  projects/rancher/local-path-provisioner/CHECKSUMS
  projects/rancher/local-path-provisioner/GIT_TAG
  projects/rancher/local-path-provisioner/Makefile
Labels: approved, lgtm, size/L

#2081 Bump versions for kube-rbac-proxy, helm, cri-tools, and govmomi
  UPSTREAM_PROJECTS.yaml
  projects/brancz/kube-rbac-proxy/ATTRIBUTION.txt
  projects/brancz/kube-rbac-proxy/CHECKSUMS
  projects/brancz/kube-rbac-proxy/GIT_TAG
  projects/helm/helm/ATTRIBUTION.txt
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/GIT_TAG
  projects/helm/helm/Makefile
  projects/kubernetes-sigs/cri-tools/ATTRIBUTION.txt
  projects/kubernetes-sigs/cri-tools/CHECKSUMS
  projects/kubernetes-sigs/cri-tools/GIT_TAG
  projects/vmware/govmomi/ATTRIBUTION.txt
  projects/vmware/govmomi/CHECKSUMS
  projects/vmware/govmomi/GIT_TAG
Labels: approved, lgtm, size/L

#2107 Patch haproxy dynmanic config via kind cli as well
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
Labels: approved, lgtm, size/M

#2093 Update Nutanix Cluster API Provider to v1.2.1
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/S, ok-to-test

#2108 Bump image-builder to v0.1.14
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0015-bump-containerd-to-1.6.19.patch
  projects/kubernetes-sigs/image-builder/patches/0016-Ensure-the-correct-Packer-binary-is-used-for-image-b.patch
  projects/kubernetes-sigs/image-builder/patches/0017-Bump-Goss-to-v3.1.4.patch
Labels: approved, lgtm, size/L

#2114 Bump kube-vip to v0.5.12
  UPSTREAM_PROJECTS.yaml
  projects/kube-vip/kube-vip/ATTRIBUTION.txt
  projects/kube-vip/kube-vip/CHECKSUMS
  projects/kube-vip/kube-vip/GIT_TAG
  projects/kube-vip/kube-vip/Makefile
  projects/kube-vip/kube-vip/README.md
  projects/kube-vip/kube-vip/patches/0001-use-hostname-instead-of-kubernetes-to-contact-apiser.patch
Labels: approved, lgtm, size/L

#2115 Add containerd.service to containerd tarball
  projects/containerd/containerd/build/create_tarballs.sh
Labels: approved, lgtm, size/XS

#2109 add 1-27 as supported release branch
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-27/helm/sedfile.template
  projects/kubernetes/autoscaler/1-21/GIT_TAG
  projects/kubernetes/autoscaler/1-22/GIT_TAG
  projects/kubernetes/autoscaler/1-23/GIT_TAG
  projects/kubernetes/autoscaler/1-24/GIT_TAG
  projects/kubernetes/autoscaler/1-25/GIT_TAG
  projects/kubernetes/autoscaler/1-26/GIT_TAG
  projects/kubernetes/autoscaler/1-27/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-27/CHECKSUMS
  projects/kubernetes/autoscaler/1-27/GIT_TAG
  projects/kubernetes/autoscaler/1-27/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-27/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-27/LICENSES
  projects/kubernetes/autoscaler/1-27/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-27/helm/schema.json
  projects/kubernetes/autoscaler/1-27/helm/sedfile.template
  projects/kubernetes/autoscaler/1-27/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-27/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-vsphere/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-23/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-27/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2116 Adding a patch to limit rufio bmclib drivers
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/patches/0001-Adding-Using-to-select-bmc-lib-drivers-for-client.patch
Labels: approved, lgtm, size/M

#2118 Revert "add 1-27 as supported release branch"
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-27/helm/sedfile.template
  projects/kubernetes/autoscaler/1-21/GIT_TAG
  projects/kubernetes/autoscaler/1-22/GIT_TAG
  projects/kubernetes/autoscaler/1-23/GIT_TAG
  projects/kubernetes/autoscaler/1-24/GIT_TAG
  projects/kubernetes/autoscaler/1-25/GIT_TAG
  projects/kubernetes/autoscaler/1-26/GIT_TAG
  projects/kubernetes/autoscaler/1-27/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-27/CHECKSUMS
  projects/kubernetes/autoscaler/1-27/GIT_TAG
  projects/kubernetes/autoscaler/1-27/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-27/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-27/LICENSES
  projects/kubernetes/autoscaler/1-27/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-27/helm/schema.json
  projects/kubernetes/autoscaler/1-27/helm/sedfile.template
  projects/kubernetes/autoscaler/1-27/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-27/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-vsphere/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-23/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-27/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2119 Removes kubeadm config version during kind build
  projects/kubernetes-sigs/kind/images/base/kubeadm.config.tmpl
Labels: approved, lgtm, size/XS

#2124 Uses eks-a build of containerd during image building
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/config/kubernetes.json.tmpl
  projects/kubernetes-sigs/image-builder/patches/0015-bump-containerd-to-1.6.19.patch
Labels: approved, lgtm, size/M

#2127 Fixes containerd tarball folder structure to match upstream
  projects/containerd/containerd/build/create_tarballs.sh
Labels: approved, lgtm, size/XS

#2128 Upgrade Prometheus to v2.43.0
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/GIT_TAG
  projects/prometheus/prometheus/README.md
Labels: approved, lgtm, size/S

#2123 Add 1-27 as supported release branch
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-27/helm/sedfile.template
  projects/kubernetes/autoscaler/1-21/GIT_TAG
  projects/kubernetes/autoscaler/1-21/LICENSES
  projects/kubernetes/autoscaler/1-22/GIT_TAG
  projects/kubernetes/autoscaler/1-22/LICENSES
  projects/kubernetes/autoscaler/1-23/GIT_TAG
  projects/kubernetes/autoscaler/1-23/LICENSES
  projects/kubernetes/autoscaler/1-24/GIT_TAG
  projects/kubernetes/autoscaler/1-24/LICENSES
  projects/kubernetes/autoscaler/1-25/GIT_TAG
  projects/kubernetes/autoscaler/1-25/LICENSES
  projects/kubernetes/autoscaler/1-26/GIT_TAG
  projects/kubernetes/autoscaler/1-26/LICENSES
  projects/kubernetes/autoscaler/1-27/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-27/CHECKSUMS
  projects/kubernetes/autoscaler/1-27/GIT_TAG
  projects/kubernetes/autoscaler/1-27/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-27/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-27/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-27/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-27/helm/schema.json
  projects/kubernetes/autoscaler/1-27/helm/sedfile.template
  projects/kubernetes/autoscaler/1-27/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-27/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-vsphere/1-23/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-23/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-27/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-27/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-27/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#2132 Revert "Revert "Uses eks-a build of containerd during image building""
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/packer/config/kubernetes.json.tmpl
  projects/kubernetes-sigs/image-builder/patches/0015-bump-containerd-to-1.6.19.patch
Labels: approved, lgtm, size/M

#2129 Updated EKS-D
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2133 Updated EKS-D (#2129)
  EKSD_LATEST_RELEASES
Labels: size/S
