Repository aws/eks-anywhere-build-tooling, pull requests merged in 2023-03, with the labels that each got.

#1893 Migrate space cleanup from eks-d
  Common.mk
  Makefile
  build/lib/update_go_versions.sh
  build/update-attribution-files/make_attribution.sh
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/M

#1886 Migrate space cleanup from eks-d
  Common.mk
  Makefile
  build/lib/update_go_versions.sh
  build/update-attribution-files/make_attribution.sh
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/M

#1897 Adds retry around kustomize install
  Common.mk
Labels: approved, lgtm, size/XS

#1887 Add more validation to ebs-init
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
Labels: approved, lgtm, size/M, ok-to-test

#1892 Adds makefile logging from eks-d around key targets
  Common.mk
  build/lib/common.sh
  build/lib/go_mod_download.sh
  build/lib/simple_create_binaries.sh
  build/lib/simple_create_tarballs.sh
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/L

#1907 Bump CAPAS to 0.1.24
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1909 Bump CAPAS to 0.1.24
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
Labels: approved, lgtm, size/XS

#1911 Removes source-controller periodic workaround
  projects/fluxcd/source-controller/Makefile
Labels: approved, lgtm, size/XS

#1906 Update cluster-api to v1.3.4
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Implement-Reconcile-mode-for-ClusterResourceSet.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-set-hostname-for-BR-nodes.patch
Labels: approved, lgtm, size/L

#1853 Update harbor-scanner-trivy to v0.30.7
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/Makefile
Labels: approved, lgtm, size/S

#1926 update harbor-scanner-trivy README
  projects/aquasecurity/harbor-scanner-trivy/README.md
Labels: approved, lgtm, size/XS

#1852 Update trivy to v0.37.3
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/Makefile
  projects/aquasecurity/trivy/README.md
  projects/aquasecurity/trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/XXL

#1923 Add cloud-provider-vsphere v1.26.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-vsphere/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-26/GIT_TAG
Labels: approved, lgtm, size/L

#1931 Patch image-builder to fix Goss validations for all EKS-A infra provider image builds
  Common.mk
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
Labels: approved, lgtm, size/L

#1929 Build packages crds and migrations charts
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/README.md
  projects/aws/eks-anywhere-packages/helm/sedfile.template
Labels: approved, lgtm, size/M

#1922 Adding rolesanywhere-credential-helper project
  UPSTREAM_PROJECTS.yaml
  projects/aws/rolesanywhere-credential-helper/.gitignore
  projects/aws/rolesanywhere-credential-helper/ATTRIBUTION.txt
  projects/aws/rolesanywhere-credential-helper/CHECKSUMS
  projects/aws/rolesanywhere-credential-helper/GIT_TAG
  projects/aws/rolesanywhere-credential-helper/Help.mk
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/aws/rolesanywhere-credential-helper/README.md
  projects/aws/rolesanywhere-credential-helper/expected_artifacts
Labels: approved, lgtm, size/L

#1934 Fix dependencies on new charts
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/S

#1936 Bump Git tags for kube-rbac-proxy, cri-tools, troubleshoot and govmomi
  UPSTREAM_PROJECTS.yaml
  projects/brancz/kube-rbac-proxy/ATTRIBUTION.txt
  projects/brancz/kube-rbac-proxy/CHECKSUMS
  projects/brancz/kube-rbac-proxy/GIT_TAG
  projects/brancz/kube-rbac-proxy/Makefile
  projects/brancz/kube-rbac-proxy/README.md
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cri-tools/ATTRIBUTION.txt
  projects/kubernetes-sigs/cri-tools/CHECKSUMS
  projects/kubernetes-sigs/cri-tools/GIT_TAG
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/cri-tools/README.md
  projects/kubernetes-sigs/cri-tools/patches/0001-Replace-broken-Go-module-for-Distribution-registry.patch
  projects/replicatedhq/troubleshoot/ATTRIBUTION.txt
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/replicatedhq/troubleshoot/GIT_TAG
  projects/replicatedhq/troubleshoot/Makefile
  projects/replicatedhq/troubleshoot/README.md
  projects/replicatedhq/troubleshoot/patches/0001-Replace-dependencies-to-mitigate-license-issues.patch
  projects/replicatedhq/troubleshoot/patches/0001-Replace-dependency-to-mitigate-license-issues-and-fi.patch
  projects/replicatedhq/troubleshoot/patches/log-issues.patch
  projects/vmware/govmomi/ATTRIBUTION.txt
  projects/vmware/govmomi/CHECKSUMS
  projects/vmware/govmomi/GIT_TAG
  projects/vmware/govmomi/README.md
Labels: approved, lgtm, size/XXL

#1935 Update bottlerocket-bootstrap to go 1.20
  build/lib/common.sh
  build/lib/install_go_versions.sh
  projects/aws/bottlerocket-bootstrap/ATTRIBUTION.txt
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/go.sum
Labels: approved, lgtm, size/L

#1884 Update x/text package
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/go.mod
  projects/aws/image-builder/go.sum
Labels: approved, lgtm, size/S

#1940 Update cluster-api to v1.3.5
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
Labels: approved, lgtm, size/S

#1941 add jsonschema for eksa-packages
  projects/aws/eks-anywhere-packages/helm/schema.json
Labels: approved, lgtm, size/M

#1944 Bump package controller to 0.3.1
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1945 Add bottlerocket k8s settings support
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-bottlerocket-k8s-settings-support.patch
Labels: approved, lgtm, size/XXL

#1946 Revert "Bump capi etcdadm providers versions"
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/Makefile
Labels: approved, lgtm, size/L

#1948 Bump to v0.3.2
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Makefile
Labels: approved, lgtm, size/S

#1950 Bump packages to 0.3.3
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#1953 Adds more logging and cleanup logs in prow
  Common.mk
  Makefile
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  build/update-attribution-files/create_pr.sh
  build/update-attribution-files/make_attribution.sh
Labels: approved, lgtm, size/M

#1904 Use codebuild batch build for checksum updates
  Common.mk
  Makefile
  build/lib/common.sh
  build/lib/generate_staging_buildspec.sh
  build/lib/setup.sh
  build/lib/update_go_versions.sh
  build/update-attribution-files/create_pr.sh
  checksums-buildspec.yml
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/cilium/cilium/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  release/checksums-build.yml
Labels: approved, lgtm, size/XL

#1949 Small changes to kind to support iptables-nft
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/create-kind-cluster.sh
  projects/kubernetes-sigs/kind/images/kindnetd/Dockerfile
Labels: approved, lgtm, size/XS

#1958 Remove containerd ubuntu patch
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
Labels: approved, lgtm, size/L

#1962 Re-add patch to use tar.gz extension for CNI plugins tarball
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
Labels: approved, lgtm, size/M

#1963 security patch for harbor
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/patches/0003-security-patch.patch
Labels: approved, lgtm, size/XL

#1965 security patch for harbor trivy
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/XL

#1967 Fixes github login for prow periodic jobs
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/S

#1959 Backport build improves to release-0.14
  Common.mk
  Makefile
  build/lib/common.sh
  build/lib/fetch_binaries.sh
  build/lib/generate_staging_buildspec.sh
  build/lib/go_mod_download.sh
  build/lib/setup.sh
  build/lib/simple_create_binaries.sh
  build/lib/simple_create_tarballs.sh
  build/lib/update_go_versions.sh
  build/update-attribution-files/create_pr.sh
  build/update-attribution-files/make_attribution.sh
  checksums-buildspec.yml
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/cilium/cilium/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes/autoscaler/Makefile
  release/checksums-build.yml
Labels: approved, lgtm, size/XL

#1974 update sedfile for harbor helm chart
  projects/goharbor/harbor/helm/sedfile.template
Labels: approved, lgtm, size/XS

#1969 Update EKSD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: lgtm, do-not-merge/hold, size/S

#1977 Update EKSD_LATEST_RELEASES (#1969)
  EKSD_LATEST_RELEASES
Labels: size/XS

#1990 Bump capi etcdadm providers versions
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/ATTRIBUTION.txt
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/Makefile
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/Makefile
  release/checksums-build.yml
Labels: approved, lgtm, size/L

#1984 Adds seperate build to checksums batch for pr
  Common.mk
  Makefile
  build/lib/generate_staging_buildspec.sh
  build/lib/install_go_versions.sh
  build/update-attribution-files/create_pr.sh
  buildspecs/checksums-buildspec.yml
  buildspecs/checksums-pr-buildspec.yml
  projects/fluxcd/source-controller/Makefile
  release/checksums-build.yml
Labels: approved, lgtm, size/XL

#1991 Adds seperate build to checksums batch for pr (#1984)
  Common.mk
  Makefile
  build/lib/generate_staging_buildspec.sh
  build/update-attribution-files/create_pr.sh
  buildspecs/checksums-buildspec.yml
  buildspecs/checksums-pr-buildspec.yml
  projects/fluxcd/source-controller/Makefile
  release/checksums-build.yml
Labels: approved, lgtm, size/XL

#1998 Revert "Update EKSD_LATEST_RELEASES (#1969)"
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#1997 Adding credential-provider-package image/helm build
  build/lib/helm_require.sh
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/Help.mk
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  projects/aws/eks-anywhere-packages/helm/credential-provider-package.schema.json
  release/staging-build.yml
Labels: approved, lgtm, size/XL

#1996 Support non-gp3 volumes in AMI image builds
  build/lib/common.sh
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/S

#2000 Get raw string from jq
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/XS

#2004 Bump CAPAS to 0.1.25
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
Labels: approved, lgtm, size/L

#2005 bumping packages to v0.3.6 and adding tag to credential-provider-package
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/helm/sedfile.template
Labels: approved, lgtm, size/S

#1972 Adds guard around image builds for newer kube versions
  Common.mk
  build/lib/common.sh
  build/lib/create_release_checksums.sh
  build/lib/upload_artifacts.sh
  build/lib/validate_artifacts.sh
  projects/kubernetes-sigs/image-builder/.gitignore
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
Labels: approved, lgtm, size/L

#2010 Restores br artifacts upload flow for image-builder
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
Labels: approved, lgtm, size/S

#2009 Latest eks-d releases
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2012 Revert "bumping packages to v0.3.6 and adding tag to credential-provider-package
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/helm/sedfile.template
Labels: approved, lgtm, size/S

#2018 Bumping packages to v0.3.7
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#2020 bump packages v0.3.8 with annotation changes
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GIT_TAG
Labels: approved, lgtm, size/S

#2019 Deprecate 1.21
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/image-builder/README.md
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/M

#2013 Use arm instances, mostly small for batch codebuild builds
  Common.mk
  build/lib/generate_staging_buildspec.sh
  build/lib/setup.sh
  buildspecs/binaries.yml
  buildspecs/images.yml
  projects/aquasecurity/trivy/Makefile
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/cert-manager/cert-manager/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/fluxcd/source-controller/buildspecs/batch-build.yml
  projects/goharbor/harbor/Makefile
  projects/kubernetes-sigs/cluster-api/Makefile
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/binaries.yml
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  projects/prometheus/prometheus/Makefile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/L

#2021 Update Rufio dependency:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
Labels: approved, lgtm, size/L

#2024 Bumps packages container size for batch builds
  projects/aws/eks-anywhere-packages/Makefile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#2026 Use 1.26 for generated help.mk files
  Makefile
  projects/aws/bottlerocket-bootstrap/Help.mk
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/fluxcd/source-controller/Makefile
  projects/kubernetes-sigs/image-builder/Help.mk
  projects/kubernetes-sigs/kind/Help.mk
  projects/kubernetes/autoscaler/Help.mk
  projects/kubernetes/cloud-provider-vsphere/Help.mk
  projects/metallb/metallb/Makefile
  projects/prometheus/node_exporter/Makefile
  projects/prometheus/prometheus/Makefile
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/rufio/Makefile
Labels: approved, lgtm, size/M

#2027 Bumps containerd for image builds
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0015-bump-containerd-to-1.6.19.patch
Labels: approved, lgtm, size/M

#1989 Skip show-join-command in kubeadm call
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
Labels: approved, lgtm, size/M

#2025 Update emissary 3.5.1
  UPSTREAM_PROJECTS.yaml
  projects/emissary-ingress/emissary/APPMESH_VERSION
  projects/emissary-ingress/emissary/ATTRIBUTION.txt
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GIT_TAG
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
  projects/emissary-ingress/emissary/patches/0001-remove_go_version_lock.patch
Labels: approved, lgtm, size/XXL

#2028 Update BR Images to v1.13.0
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2029 Fix setting annotations in capi cluster controller
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Implement-Reconcile-mode-for-ClusterResourceSet.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-bottlerocket-k8s-settings-support.patch
Labels: approved, lgtm, size/L

#2031 Add BR 1.26
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#2011 Configure kubelet serving cert and key
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils_test.go
Labels: approved, lgtm, size/L, ok-to-test

#2032 Add bottlerocket kernel.sysctl settings support
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0029-add-br-kernel-sysctl-settings.patch
Labels: approved, lgtm, size/L

#2034 Changes bootconfig build to use linux/amd vs arm codebuild instances
  projects/torvalds/linux/Makefile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#2008 Bump etcdadm version to latest
  UPSTREAM_PROJECTS.yaml
  build/lib/version.sh
  projects/kubernetes-sigs/etcdadm/ATTRIBUTION.txt
  projects/kubernetes-sigs/etcdadm/CHECKSUMS
  projects/kubernetes-sigs/etcdadm/GIT_TAG
  projects/kubernetes-sigs/etcdadm/Makefile
  projects/kubernetes-sigs/etcdadm/patches/0001-Add-support-for-cipher-suites.patch
  projects/kubernetes-sigs/etcdadm/patches/0001-Initial-support-for-running-etcd-under-kubelet.patch
  projects/kubernetes-sigs/etcdadm/patches/0002-Allow-using-multiple-endpoints-for-etcd-client.patch
  projects/kubernetes-sigs/etcdadm/patches/0002-Updated-init-and-join-commands-to-be-able-to-use-kub.patch
  projects/kubernetes-sigs/etcdadm/patches/0003-Fixed-linting.patch
  projects/kubernetes-sigs/etcdadm/patches/0003-Increase-wait-backoff-retries-during-join.patch
  projects/kubernetes-sigs/etcdadm/patches/0004-Add-retry-on-listing-members-in-join-command.patch
  projects/kubernetes-sigs/etcdadm/patches/0004-Added-phases-for-init-command.patch
  projects/kubernetes-sigs/etcdadm/patches/0005-Added-phases-for-join-command.patch
  projects/kubernetes-sigs/etcdadm/patches/0006-Added-membership-phase-as-a-prerequisite-to-configur.patch
  projects/kubernetes-sigs/etcdadm/patches/0007-Added-test-for-init-and-join-with-phases.patch
  projects/kubernetes-sigs/etcdadm/patches/0008-Added-flags-for-etcd-data-dir-and-kubelet-podspec-di.patch
  projects/kubernetes-sigs/etcdadm/patches/0009-Fixed-linting.patch
  projects/kubernetes-sigs/etcdadm/patches/0010-Support-linux-other-arch.patch
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0015-bump-containerd-to-1.6.19.patch
  projects/kubernetes-sigs/image-builder/patches/0016-Ensure-the-correct-Packer-binary-is-used-for-image-b.patch
Labels: approved, lgtm, size/XXL

#1822 Fix CVE-2022-1996 for Cluster Autoscaler 1-23
  projects/kubernetes/autoscaler/1-23/CHECKSUMS
  projects/kubernetes/autoscaler/1-23/patches/0002-Fix-CVE-2022-1996-for-1.23.patch
Labels: approved, lgtm, size/M

#2042 Small improvement to bootconfig build to ensure arch is expected
  projects/torvalds/linux/Makefile
Labels: approved, lgtm, size/XS

#2041 Fix Leaky capv vSphere Sessions
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0004-Fix-vCenter-session-leaks.patch
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0005-Fixup-Fix-vCenter-session-leaks.patch
Labels: approved, lgtm, size/L

#2046 Use correct pod spec directory flag
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/flags.go
Labels: approved, lgtm, size/XS

#2048 Add support for configuring boot settings for BR
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-bootstrap-provider/CHECKSUMS
  projects/aws/etcdadm-bootstrap-provider/GIT_TAG
  projects/aws/etcdadm-bootstrap-provider/README.md
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0030-add-boot-kernel-settings-for-BR.patch
Labels: approved, lgtm, size/XL

#2053 Upgrade Bottlerocket to 1.13.1
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2065 Updated EKS-D for all versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S
