Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-09, with the labels that each got.

#3703 Upgrade ADOT to v0.40.1
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#3683 Update documentation for curated packages
  docs/development/packages/update-helm-charts.md
  projects/goharbor/harbor/README.md
  projects/metallb/metallb/README.md
  projects/prometheus/node_exporter/README.md
  projects/prometheus/prometheus/README.md
Labels: approved, lgtm, size/L

#3709 Include branch name other than main in the PR title
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/S

#3714 Fix prometheus/prometheus version in the README
  projects/prometheus/prometheus/README.md
Labels: approved, lgtm, size/XS

#3706 Add 1-31 release branch support
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-31/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-31/helm/sedfile.template
  projects/kubernetes/autoscaler/1-31/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-31/CHECKSUMS
  projects/kubernetes/autoscaler/1-31/GIT_TAG
  projects/kubernetes/autoscaler/1-31/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-31/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-31/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-31/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-31/helm/patches/0003-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-31/helm/schema.json
  projects/kubernetes/autoscaler/1-31/helm/sedfile.template
  projects/kubernetes/autoscaler/1-31/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-31/patches/0002-Remove-additional-GCE-Dependencies.patch
  projects/kubernetes/autoscaler/1-31/patches/0003-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-aws/1-31/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-31/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-31/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-31/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-31/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-31/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-31/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-31/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#3724 Upgrade only the patch versions for cilium on release branch
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
Labels: approved, lgtm, size/M

#3671 Upgrade Prometheus to v2.54.0
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/ATTRIBUTION.txt
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/GIT_TAG
  projects/prometheus/prometheus/HELM_GIT_TAG
  projects/prometheus/prometheus/README.md
  projects/prometheus/prometheus/helm/patches/0001-Remove-prometheus-chart-dependencies.patch
  projects/prometheus/prometheus/helm/patches/0002-Add-node-exporter-component.patch
Labels: approved, lgtm, size/L, curated-packages

#3728 Allow upgrader to open pull requests even in case of failures
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L

#3741 Update patch and CHECKSUMS for CAPC v0.5.0
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch
Labels: approved, lgtm, size/M

#3742 Bump etcdadm-controller to version 1.0.23
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#3751 Use only major and minor versions for Go version semver
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/S

#3753 Backport Go version detection improvements to release-0.19
  tools/version-tracker/pkg/constants/constants.go
Labels: size/M

#3752 Backport Go version detection improvements to release-0.20
  tools/version-tracker/pkg/constants/constants.go
Labels: size/M

#3745 Deprecate 1.25 and 1.26 from supported release branches
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/image-builder/README.md
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/downloadartifacts.go
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/autoscaler/1-25/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/GIT_TAG
  projects/kubernetes/autoscaler/1-25/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-25/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-25/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-25/helm/schema.json
  projects/kubernetes/autoscaler/1-25/helm/sedfile.template
  projects/kubernetes/autoscaler/1-25/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-25/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/1-26/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-26/CHECKSUMS
  projects/kubernetes/autoscaler/1-26/GIT_TAG
  projects/kubernetes/autoscaler/1-26/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-26/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-26/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-26/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-26/helm/schema.json
  projects/kubernetes/autoscaler/1-26/helm/sedfile.template
  projects/kubernetes/autoscaler/1-26/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-26/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-aws/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-25/GOLANG_VERSION
  projects/kubernetes/cloud-provider-aws/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-26/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-26/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-25/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-26/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-26/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#3762 Update bottlerocket release version and host containers
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#3763 Revert "[release-0.19] Bump kubernetes-sigs/cluster-api to latest release (#3418)"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/GOLANG_VERSION
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Use-controller-runtime-patch-for-restmapper-cache.patch
  projects/kubernetes-sigs/cluster-api/patches/0041-enable-kubeadm-feature-flags-mutation.patch
Labels: approved, lgtm, size/XL

#3771 Update Ubuntu 22.04 ISO for image builds
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
Labels: approved, lgtm, size/L

#3760 [release-0.20] RHEL 9 EFI support and improvements
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-RHEL-9-EFI-support-and-improvements.patch
Labels: approved, lgtm, size/M

#3774 Add Shizhao to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3783 Add patches to fix Ubuntu 22.04 OVA and RHEL 8/9 QEMU/raw builds
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
Labels: approved, lgtm, size/L

#3791 Backport image-builder bumps to release-0.20 branch
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/build/update_required_deps.sh
  projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-RHEL-9-EFI-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
Labels: approved, lgtm, size/XL

#3792 Backport image-builder bumps to release-0.19 branch
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/build/update_required_deps.sh
  projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
Labels: approved, lgtm, size/XL

#3790 Bump cert manager to v1.15.3
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_STARTUPAPICHECK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/GOLANG_VERSION
  projects/cert-manager/cert-manager/Help.mk
  projects/cert-manager/cert-manager/Makefile
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/docker/linux/cert-manager-ctl/Dockerfile
  projects/cert-manager/cert-manager/docker/linux/cert-manager-startupapicheck/Dockerfile
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0004-Update-cert-manager-namespace-config.patch
  projects/cert-manager/cert-manager/helm/schema.json
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
Labels: approved, lgtm, size/XXL

#3808 Fix typo in EKS-A latest version function name
  projects/aws/image-builder/Makefile
Labels: size/XS

#3816 Revert removal of ecr_credential_provider Ansible arg
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
Labels: approved, lgtm, size/XS

#3817 [release-0.20] Bump kubernetes-sigs/image-builder to v0.1.36
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
Labels: approved, lgtm, size/L

#3822 Add Go version configuration for Linuxkit project
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#3819 fixes support for efi on rhel 9 raw builds
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/utils_test.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
Labels: approved, lgtm, size/L

#3805 Bump capi to v1.8.3
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/GOLANG_VERSION
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Update-coredns-corefile-migration-to-support-1.11.3.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Add-changes-to-support-kubeadm-v1beta4-types.patch
Labels: approved, lgtm, size/XXL
