Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-08, with the labels that each got.

#3482 Add dhcp relay images to tinkerbell tink repo
  projects/tinkerbell/tink/Help.mk
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/docker/linux/tink-relay-init/Dockerfile
  projects/tinkerbell/tink/docker/linux/tink-relay/Dockerfile
  projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/M

#3542 Update etcdadm-controller to latest tag
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#3552 Retrieve Go version for local-path-provisioner project from Dockerfile
  tools/version-tracker/pkg/constants/constants.go
Labels: size/XS

#3559 Revert tink-server Dockerfile to use clean_install
  projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
Labels: approved, lgtm, size/XS

#3563 Add Go version source file for cloud-provider-nutanix
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#3568 Add buildspec file for tink project
  projects/tinkerbell/tink/buildspecs/batch-build.yml
Labels: approved, lgtm, size/S

#3567 Build tink project as batchbuild
  Makefile
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/buildspecs/batch-build.yml
  projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#3571 Set IMAGE_BUILD_ARGS in tinkerbell tink Makefile
  projects/tinkerbell/tink/Makefile
Labels: approved, lgtm, size/XS

#3579 Revert "[PR BOT] Update prometheus/prometheus/ATTRIBUTION.txt (#3576)"
  projects/prometheus/prometheus/ATTRIBUTION.txt
Labels: approved, lgtm, size/M

#3585 Fix tink builds for release-0.19 branch
  Makefile
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/buildspecs/batch-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3588 Remove ATTRIBUTION_FILE from hub Dockerfiles
  projects/tinkerbell/hub/docker/linux/cexec/Dockerfile
  projects/tinkerbell/hub/docker/linux/image2disk/Dockerfile
  projects/tinkerbell/hub/docker/linux/kexec/Dockerfile
  projects/tinkerbell/hub/docker/linux/oci2disk/Dockerfile
  projects/tinkerbell/hub/docker/linux/writefile/Dockerfile
Labels: approved, lgtm, size/S

#3593 Add force flag to kubeadm upgrade command
  projects/aws/upgrader/CHECKSUMS
  projects/aws/upgrader/upgrade/kubeadm.go
  projects/aws/upgrader/upgrade/kubeadm_test.go
Labels: approved, lgtm, size/S

#3596 Removing RTOS ubuntu
  projects/canonical/ubuntu/Help.mk
  projects/canonical/ubuntu/Makefile
  projects/canonical/ubuntu/RTOS_IMAGE_DATE
  projects/canonical/ubuntu/build/download_rtos_image.sh
  projects/canonical/ubuntu/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/L

#3597 Add patch to revert using CD for preseed and cloud-init boot files
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Revert-fix-Update-preseed-and-cloud-init-to-use-CD-f.patch
Labels: approved, lgtm, size/L

#3602 [Backport] Removing RTOS ubuntu
  projects/canonical/ubuntu/Help.mk
  projects/canonical/ubuntu/Makefile
  projects/canonical/ubuntu/RTOS_IMAGE_DATE
  projects/canonical/ubuntu/build/download_rtos_image.sh
  projects/canonical/ubuntu/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/L

#3595 Image-builder patch: remove swap partition from RHEL 9 EFI
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Revert-fix-Update-preseed-and-cloud-init-to-use-CD-f.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-swap-partition-in-rhel9-efi.patch
Labels: approved, lgtm, size/M, ok-to-test

#3604 Revert "Bump kubernetes-sigs/image-builder and Bottlerocket versions
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/REQUIRED_DEPENDENCY_VERSIONS.yaml
  projects/kubernetes-sigs/image-builder/build/update_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Image-builder-patch-remove-swap-partition-from-RHEL-.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Revert-fix-Update-preseed-and-cloud-init-to-use-CD-f.patch
Labels: approved, lgtm, size/L

#3605 Revert "[release-0.20] Bump kubernetes-sigs/image-builder
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/REQUIRED_DEPENDENCY_VERSIONS.yaml
  projects/kubernetes-sigs/image-builder/build/update_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Revert-fix-Update-preseed-and-cloud-init-to-use-CD-f.patch
Labels: approved, lgtm, size/L

#3608 Revert "Bump kubernetes-sigs/cri-tools to latest release"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cri-tools/ATTRIBUTION.txt
  projects/kubernetes-sigs/cri-tools/CHECKSUMS
  projects/kubernetes-sigs/cri-tools/GIT_TAG
  projects/kubernetes-sigs/cri-tools/README.md
Labels: approved, lgtm, size/L

#3611 Update image builder readme to remove ref to 1-25 k8s
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#3610 Add force flag to kubeadm upgrade command
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/XS

#3607 Make source images for Nutanix Red Hat builds private
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/download_iso.sh
Labels: approved, lgtm, size/M

#3621 Update BottleRocket Host Container file path to match upstream
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#3613 Remove legacy upgrader script which is no longer used
  projects/aws/upgrader/docker/linux/Dockerfile
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/L

#3622 Add Go version source of truth for tinkerbell hook project
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#3625 Add fallback Go version truth files for all projects
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/M

#3635 [release-0.19] Update base image in tag file(s) (#3623)
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GLIBC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_IPTABLES_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NONROOT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NSENTER_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_TAG_FILE
Labels: approved, lgtm, size/S

#3636 [release-20] Update base image in tag file(s)
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GLIBC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_IPTABLES_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NONROOT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NSENTER_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_TAG_FILE
Labels: approved, lgtm, size/S

#3641 [release-0.19] Downgrade bottlerocket version for 1.29 k8s
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#3626 Update schema.json for MetalLB to align with upstream repository
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
  projects/metallb/metallb/helm/schema.json
Labels: approved, lgtm, size/XL

#3642 Bump eks-anywhere-packages to v0.4.4
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/GOLANG_VERSION
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/M

#3643 Include branch name other than main in the PR title
  build/update-attribution-files/create_pr.sh
Labels: approved, lgtm, size/S

#3653 Bump kubernetes-sigs/cluster-api-provider-vsphere to latest release
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
Labels: approved, lgtm, size/L

#3657 Upgrade trivy and harbor-scanner-trivy for harbor v2.11.0
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/README.md
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/GOLANG_VERSION
  projects/aquasecurity/trivy/README.md
  projects/aquasecurity/trivy/patches/0001-Replace-mitchellh-os-ext-with-kardianos-os-ext-modul.patch
Labels: approved, lgtm, size/L

#3667 [Patch] Remove unwanted partitions from RHEL 9
  projects/kubernetes-sigs/image-builder/patches/0009-Image-builder-patch-remove-unwanted-partitions-from-RHEL-9.patch
Labels: approved, lgtm, size/S

#3665 Update metallb to pull minimal base image
  projects/metallb/metallb/Makefile
Labels: approved, lgtm, size/XS, curated-packages

#3677 image-builder: update checksum for Bottlerocket's new root.json
  projects/kubernetes-sigs/image-builder/bottlerocket-root-json-checksum
Labels: approved, lgtm, size/XS, ok-to-test

#3684 RHEL 9 EFI support and improvements
  projects/kubernetes-sigs/image-builder/patches/0009-Image-builder-patch-remove-unwanted-partitions-from-RHEL-9.patch
  projects/kubernetes-sigs/image-builder/patches/0009-RHEL-9-EFI-support-and-improvements.patch
Labels: approved, size/M

#3685 use batch for hook build to match main
  Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/buildspecs/batch-build.yml
Labels: approved, lgtm, size/M

#3471 adds support for building hook kernel
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/validate_artifacts.sh
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/GOLANG_VERSION
  projects/tinkerbell/hook/HOOK_BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/HOOK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/LINUX_KERNEL_VERSION
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/hook/buildspecs/batch-build.yml
  projects/tinkerbell/hook/config-patches/0001-cisco-ucs
  projects/tinkerbell/hook/docker/linux/hook-containerd/Dockerfile
  projects/tinkerbell/hook/docker/linux/hook-docker/Dockerfile
  projects/tinkerbell/hook/docker/linux/hook-embedded/Dockerfile
  projects/tinkerbell/hook/docker/linux/hook-runc/Dockerfile
  projects/tinkerbell/hook/docker/linux/kernel/Dockerfile
  projects/tinkerbell/hook/patches/0001-Don-t-build-container-images.patch
  projects/tinkerbell/hook/patches/0025-patches-build.sh-flow-for-linuxkit.patch
  projects/tinkerbell/hook/patches/0026-builds-kernel-from-al2.patch
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XL

#3687 fixes hook in codebuild
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
  projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
Labels: approved, lgtm, size/XS

#3688 fixes dind overlayfs in codebuild
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/docker/linux/hook-docker/Dockerfile
  projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
  projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
  projects/tinkerbell/hook/patches/0003-use-tmpfs-for-var-lib-docker.patch
Labels: approved, lgtm, size/M

#3678 Bump nutanix-cloud-native/cluster-api-provider-nutanix to v1.4.0 release
  Common.mk
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/.gitignore
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/L

#3692 Bump tink worker
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/tink/ATTRIBUTION.txt
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/GOLANG_VERSION
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/patches/0001-Remove-.ONESHELL-from-Makefile.patch
  projects/tinkerbell/tink/patches/0001-Remove-oneshell-from-Makefile.patch
  projects/tinkerbell/tink/patches/0002-Fix-Makefile-goal.patch
Labels: approved, lgtm, size/L

#3696 adds linuxkit build
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/linuxkit/linuxkit/.gitignore
  projects/linuxkit/linuxkit/ATTRIBUTION.txt
  projects/linuxkit/linuxkit/CHECKSUMS
  projects/linuxkit/linuxkit/GIT_TAG
  projects/linuxkit/linuxkit/GOLANG_VERSION
  projects/linuxkit/linuxkit/Help.mk
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/README.md
  projects/linuxkit/linuxkit/buildspecs/batch-build.yml
  projects/linuxkit/linuxkit/expected_artifacts
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#3698 fixes linuxkit build spec
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/buildspecs/batch-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#3699 fix dhcpd image component
  projects/linuxkit/linuxkit/Makefile
Labels: approved, lgtm, size/XS

#3700 fixes combine for linuxkit by checking the repo
  buildspecs/combine-images.yml
Labels: approved, lgtm, size/XS

#3701 fixes linuxkit artifacts upload
  projects/linuxkit/linuxkit/Makefile
Labels: approved, lgtm, size/XS

#3697 add placeholder to avoid codebuild failures
  UPSTREAM_PROJECTS.yaml
  projects/linuxkit/linuxkit/GIT_TAG
  projects/linuxkit/linuxkit/Help.mk
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/buildspecs/batch-build.yml
Labels: approved, lgtm, size/L
