Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-10, with the labels that each got.

#3823 fix yq usage to support fake yq
  projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
Labels: approved, lgtm, size/XS

#3826 [release-0.20] Remove flux helm chart
  projects/fluxcd/flux2/.gitignore
  projects/fluxcd/flux2/HELM_GIT_TAG
  projects/fluxcd/flux2/Help.mk
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/helm/patches/0001-Disable-image-automation.patch
  projects/fluxcd/flux2/helm/patches/0002-Allow-modification-of-image-tags.patch
  projects/fluxcd/flux2/helm/sedfile.template
Labels: approved, lgtm, size/L

#3825 Bump fluxcd/flux2 to v2.4.0
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/flux2/.gitignore
  projects/fluxcd/flux2/ATTRIBUTION.txt
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/GOLANG_VERSION
  projects/fluxcd/flux2/HELM_GIT_TAG
  projects/fluxcd/flux2/Help.mk
  projects/fluxcd/flux2/Makefile
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/helm/patches/0001-Disable-image-automation.patch
  projects/fluxcd/flux2/helm/patches/0002-Allow-modification-of-image-tags.patch
  projects/fluxcd/flux2/helm/sedfile.template
  projects/fluxcd/flux2/patches/0001-Update-go.mod-image-automation-controller-module-to-.patch
Labels: approved, lgtm, size/XL

#3833 Add Packer GitHub API token env var for CloudStack and Raw image builds
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#3530 adds ipxedust build
  Common.mk
  Makefile
  UPSTREAM_PROJECTS.yaml
  build/lib/prepare_build_container_user.sh
  build/lib/validate_artifacts.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/tinkerbell/ipxedust/.gitignore
  projects/tinkerbell/ipxedust/ATTRIBUTION.txt
  projects/tinkerbell/ipxedust/GIT_TAG
  projects/tinkerbell/ipxedust/Help.mk
  projects/tinkerbell/ipxedust/Makefile
  projects/tinkerbell/ipxedust/README.md
  projects/tinkerbell/ipxedust/buildspecs/batch-build.yml
  projects/tinkerbell/ipxedust/buildspecs/combine-artifacts.yml
  projects/tinkerbell/ipxedust/expected_artifacts
  projects/tinkerbell/ipxedust/expected_artifacts_src
  projects/tinkerbell/ipxedust/patches/0001-do-not-use-nix-shell-for-building.patch
  release/staging-build.yml
Labels: approved, lgtm, size/XL

#3835 fixes batch builds for ipxedust
  Makefile
  projects/tinkerbell/ipxedust/Makefile
  projects/tinkerbell/ipxedust/buildspecs/batch-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/S

#3836 removes src handling for ipxedust
  Makefile
  projects/tinkerbell/ipxedust/Makefile
  projects/tinkerbell/ipxedust/buildspecs/batch-build.yml
  projects/tinkerbell/ipxedust/buildspecs/combine-artifacts.yml
  projects/tinkerbell/ipxedust/expected_artifacts_src
  release/staging-build.yml
Labels: approved, lgtm, size/M

#3837 [release-0.19] Bump kubernetes-sigs/image-builder to v0.1.36
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
Labels: approved, lgtm, size/L

#3834 boots uses eksa ipxedust
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/Help.mk
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/boots/docker/linux/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/S

#3840 Retry image builds in case of Ansible SSH timeout
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#3842 adds moby_config to linuxkit images
  projects/linuxkit/linuxkit/CHECKSUMS
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/patches/0001-add-moby-config-to-dockerfiles-for-packages-used-by-.patch
Labels: approved, lgtm, size/L

#3844 fixes combine-image phase for linuxkit
  projects/linuxkit/linuxkit/Makefile
Labels: approved, lgtm, size/XS

#3843 add support to pull image cache from other repo
  Common.mk
Labels: approved, lgtm, size/XS

#3847 changes hook to pull eksa linuxkit images
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
  release/staging-build.yml
Labels: approved, lgtm, size/M

#3849 fixes snow image cache build
  projects/aws/cluster-api-provider-aws-snow/Makefile
Labels: approved, lgtm, size/XS

#3850 Add patch to revert optionally sourcing /etc/default/kubelet in kubelet service
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/L

#3851 [release-0.20] Add patch to revert optionally sourcing /etc/default/kubelet in kubelet service
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/M

#3852 [release-0.19] Add patch to revert optionally sourcing /etc/default/kubelet in kubelet service
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/M

#3857 Update CHECKSUMS for tinkerbell boots
  projects/tinkerbell/boots/CHECKSUMS
Labels: approved, lgtm, size/XS

#3853 Update badge URL for 1.31 image-builder jobs
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#3858 Skip checksums validation for Boots project
  projects/tinkerbell/boots/Makefile
Labels: approved, lgtm, size/XS

#3860 adds comment to hook build
  projects/tinkerbell/hook/Makefile
Labels: approved, lgtm, size/S

#3861 Update cert-manager manifest when bumping Git tag
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: size/M

#3864 Update cert-manager manifest when bumping Git tag
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: size/M

#3865 Update cert-manager manifest when bumping Git tag
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: size/M

#3859 adds source epoch to ipxe build for reproducibility
  projects/isc-projects/dhcp/CHECKSUMS
  projects/isc-projects/dhcp/Makefile
  projects/tinkerbell/ipxedust/CHECKSUMS
  projects/tinkerbell/ipxedust/Makefile
  projects/torvalds/linux/.gitignore
  projects/torvalds/linux/CHECKSUMS
  projects/torvalds/linux/Makefile
  release/checksums-build.yml
Labels: approved, lgtm, size/L

#3866 adds builds for golang based linuxkit images
  Common.mk
  build/lib/simple_create_binaries.sh
  projects/linuxkit/linuxkit/CHECKSUMS
  projects/linuxkit/linuxkit/INIT_ATTRIBUTION.txt
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/RC.INIT_ATTRIBUTION.txt
  projects/linuxkit/linuxkit/RNGD_ATTRIBUTION.txt
  projects/linuxkit/linuxkit/SERVICE_ATTRIBUTION.txt
  projects/linuxkit/linuxkit/SYSCTL_ATTRIBUTION.txt
  projects/linuxkit/linuxkit/SYSFS_ATTRIBUTION.txt
  projects/linuxkit/linuxkit/docker/linux/rngd/Dockerfile
  projects/linuxkit/linuxkit/docker/linux/sysctl/Dockerfile
  projects/linuxkit/linuxkit/docker/linux/sysfs/Dockerfile
  projects/linuxkit/linuxkit/patches/0001-add-moby-config-to-dockerfiles-for-packages-used-by-.patch
  projects/linuxkit/linuxkit/patches/0002-init-dockerfile-to-use-eks-a-built-bins.patch
  projects/linuxkit/linuxkit/patches/0003-pass-cpu-host-when-running-qemu-to-support-testing-a.patch
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
  projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
  projects/tinkerbell/hook/patches/0003-use-tmpfs-for-var-lib-docker.patch
  projects/tinkerbell/hook/patches/0004-support-overriding-linuxkit-version-to-use-eksa-buil.patch
Labels: approved, lgtm, size/XXL

#3882 fixes combine images for linuxkit
  projects/linuxkit/linuxkit/Makefile
Labels: approved, lgtm, size/S

#3895 Remove distribution from staging buildspec
  projects/distribution/distribution/Makefile
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#3899 Use Dockerfile to retrieve Rufio Go version
  tools/version-tracker/pkg/constants/constants.go
Labels: size/XS

#3904 Bump kubernetes-sigs/image-builder to v0.1.38
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/M

#3905 [release-0.19] Bump kubernetes-sigs/image-builder to v0.1.38
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/M

#3906 [release-0.20] Bump kubernetes-sigs/image-builder to v0.1.38
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/M

#3908 forces combine-images flow to build both platforms
  buildspecs/combine-images.yml
Labels: approved, lgtm, size/XS

#3916 Fix typo in password env var in autoinstall script
  projects/kubernetes-sigs/image-builder/patches/0014-Set-SSH-password-dynamically-during-auto-install.patch
Labels: approved, lgtm, size/M

#3920 Bump metrics server helm chart to latest version 3.12.2
  projects/kubernetes-sigs/metrics-server/1-25/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-25/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-28/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-29/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-30/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-31/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/README.md
Labels: approved, lgtm, size/XXL

#3932 Upgrade trivy and harbor-scanner-trivy for harbor v2.11.1
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/GOLANG_VERSION
  projects/aquasecurity/harbor-scanner-trivy/README.md
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/README.md
  projects/aquasecurity/trivy/patches/0001-Replace-dependency-to-mitigate-license-issues.patch
  projects/aquasecurity/trivy/patches/0001-Replace-mitchellh-os-ext-with-kardianos-os-ext-modul.patch
Labels: approved, lgtm, size/XXL

#3943 Include files not in index in patch application failure comment
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/S

#3909 Handle kubeadm join and etcd join logic when 'ControlPlaneKubeletLocalMode' is enabled
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/waiters.go
Labels: approved, lgtm, size/M

#3948 Update ADOT image digest when bumping Git tag
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/S

#3952 Fix remove-addon-resizer patch for metrics-server
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0002-Remove-Addon-Resizer.patch
Labels: approved, lgtm, size/L

#3953 Revert "Bump tinkerbell/hegel to latest release (#3939)"
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hegel/ATTRIBUTION.txt
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/GOLANG_VERSION
  projects/tinkerbell/hegel/README.md
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#3960 add kernel to hook combine-images list
  projects/tinkerbell/hook/Makefile
Labels: approved, lgtm, size/M

#3964 Update patches and CHECKSUMS for CAPC v0.5.0
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0002-Add-latest-CAPC-minor-release-v0.5.0-to-metadata.yam.patch
Labels: approved, lgtm, size/M

#3976 Retry Nutanix image builds in case of internal server errors
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS
