Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-07, with the labels that each got.

#3407 Update Ubuntu RTOS image version to latest
  projects/canonical/ubuntu/RTOS_IMAGE_DATE
Labels: approved, lgtm, size/XS

#3291 backports latest base image tags
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GLIBC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_IPTABLES_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NONROOT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NSENTER_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_TAG_FILE
Labels: approved, lgtm, size/S

#3411 remove uneccessary builds from staging and checksums
  projects/envoyproxy/envoy/Makefile
  projects/redis/redis/Makefile
  projects/tinkerbell/charts/Makefile
  projects/tinkerbell/tinkerbell-crds/Makefile
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/M

#3410 skip patching KubeVip manifest if its not present in bottlerocket-boo…
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
Labels: approved, lgtm, size/S, ok-to-test

#3455 Backport latest base image tags
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GLIBC_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_HAPROXY_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_IPTABLES_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NGINX_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_NSENTER_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
Labels: approved, lgtm, size/S

#3459 Bump ADOT to v0.40.0
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/helm/patches/0001-Update-image-repo.patch
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#3474 [release-0.19] Update kubernetes/cloud-provider-aws GIT_TAG to correct k8s minor versions
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-aws/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-26/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-29/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-29/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-29/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-29/GOLANG_VERSION
  projects/kubernetes/cloud-provider-aws/README.md
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#3473 Update project bumps PR title for release branches
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: approved, lgtm, size/S

#3472 [release-0.19] Add lb_class_only env var to kube-vip ds
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/README.md
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/S

#3483 Include branch name for kubernetes-sigs/image-builder project
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#3501 Include branch name for bottlerocket releases
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#3506 Skip project upgrade for packages on release branches
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/S

#3505 Revert "[release-0.20] Bump metallb/metallb to latest release"
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/ATTRIBUTION.txt
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/GOLANG_VERSION
  projects/metallb/metallb/README.md
Labels: approved, lgtm, size/M

#3510 Update RHEL8 ISO to 8.10, simplify RHEL config generation
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
Labels: approved, lgtm, size/M

#3509 add dhcp project to build tooling
  Makefile
  UPSTREAM_PROJECTS.yaml
  projects/isc-projects/dhcp/.gitignore
  projects/isc-projects/dhcp/ATTRIBUTION.txt
  projects/isc-projects/dhcp/GIT_TAG
  projects/isc-projects/dhcp/Help.mk
  projects/isc-projects/dhcp/Makefile
  projects/isc-projects/dhcp/README.md
  projects/isc-projects/dhcp/buildspecs/batch-build.yml
  projects/isc-projects/dhcp/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/XL

#3531 Fix typo in dhcp expected artifacts
  projects/isc-projects/dhcp/expected_artifacts
Labels: approved, lgtm, size/XS

#3532 Increase disk size of the snow admin machine
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
Labels: approved, lgtm, size/XS
