Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-04, with the labels that each got.

#3044 Add CI changes for Raw Redhat 9 Builds
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#3046 Add patch for insecure proxy support for helm
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/patches/0001-bug-add-proxy-support-for-oci-getter.patch
  projects/helm/helm/patches/0002-Set-proxy-in-registry-client.patch
Labels: approved, lgtm, size/M

#3053 Bump go version for eks-anywhere-packages to 1.20
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/GOLANG_VERSION
Labels: approved, lgtm, size/S

#3057 Bump aws/eks-anywhere-packages to latest upstream release
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/XL

#3060 Fix attribution and checksum generation for successful patch application
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: size/M

#3065 Bump kubernetes/cloud-provider-vsphere 1-25 and 1-26 release branches to latest release
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-vsphere/1-25/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-25/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-25/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-26/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-26/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-26/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/README.md
Labels: approved, lgtm, size/XL

#3070 add sp1999 to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3074 add note to building locally about skopeo
  docs/development/building-locally.md
Labels: approved, lgtm, size/S

#3072 Bump Bottlerocket versions to latest release
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#3075 Fix Bottlerocket host container metadata files
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/types/types.go
Labels: approved, lgtm, size/S

#3033 Convert Upgrader Script to Go binary
  projects/aws/upgrader/ATTRIBUTION.txt
  projects/aws/upgrader/CHECKSUMS
  projects/aws/upgrader/GOLANG_VERSION
  projects/aws/upgrader/Help.mk
  projects/aws/upgrader/LICENSE
  projects/aws/upgrader/Makefile
  projects/aws/upgrader/cmd/root.go
  projects/aws/upgrader/cmd/status.go
  projects/aws/upgrader/cmd/upgrade.go
  projects/aws/upgrader/cmd/upgradecniplugins.go
  projects/aws/upgrader/cmd/upgradecontainerd.go
  projects/aws/upgrader/cmd/upgradekubeletkubectl.go
  projects/aws/upgrader/cmd/upgradenode.go
  projects/aws/upgrader/docker/linux/Dockerfile
  projects/aws/upgrader/go.mod
  projects/aws/upgrader/go.sum
  projects/aws/upgrader/main.go
  projects/aws/upgrader/upgrade/cniplugins.go
  projects/aws/upgrader/upgrade/cniplugins_test.go
  projects/aws/upgrader/upgrade/containerd.go
  projects/aws/upgrader/upgrade/containerd_test.go
  projects/aws/upgrader/upgrade/kubeadm.go
  projects/aws/upgrader/upgrade/kubeadm_test.go
  projects/aws/upgrader/upgrade/kubelet_kubectl.go
  projects/aws/upgrader/upgrade/kubelet_kubectl_test.go
  projects/aws/upgrader/upgrade/mocks/syscalls.go
  projects/aws/upgrader/upgrade/mocks/syscalls_mock.go
  projects/aws/upgrader/upgrade/status.go
  projects/aws/upgrader/upgrade/syscalls.go
  projects/aws/upgrader/upgrade/upgrader.go
  projects/aws/upgrader/upgrade/upgrader_test.go
  release/checksums-build.yml
Labels: approved, lgtm, size/XXL

#3071 Add 1-30 release branch support
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-30/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-30/helm/sedfile.template
  projects/kubernetes/autoscaler/1-30/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-30/CHECKSUMS
  projects/kubernetes/autoscaler/1-30/GIT_TAG
  projects/kubernetes/autoscaler/1-30/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-30/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-30/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-30/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-30/helm/patches/0003-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-30/helm/schema.json
  projects/kubernetes/autoscaler/1-30/helm/sedfile.template
  projects/kubernetes/autoscaler/1-30/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-30/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-aws/1-30/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-30/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-30/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-30/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-30/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-30/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-30/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-30/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XXL

#3063 Bump cert-manager to 1.14.2
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/GOLANG_VERSION
  projects/cert-manager/cert-manager/Makefile
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0004-Update-cert-manager-namespace-config.patch
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
Labels: approved, lgtm, size/XXL, area/dependencies

#3066 Support upgrading release-branched projects
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/util/slices/slices.go
Labels: approved, lgtm, size/L

#3078 Bump hegel version to v0.12.0
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hegel/ATTRIBUTION.txt
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/GOLANG_VERSION
  projects/tinkerbell/hegel/Makefile
  projects/tinkerbell/hegel/README.md
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#3079 Bump rufio to v0.3.3
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/GOLANG_VERSION
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/README.md
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#3088 bump CAPI to v1.6.4
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
Labels: approved, lgtm, size/M

#3087 Bump tink to v0.10.0
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/tink/ATTRIBUTION.txt
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/GOLANG_VERSION
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/patches/0001-Remove-.ONESHELL-from-Makefile.patch
  projects/tinkerbell/tink/patches/0001-Remove-.ONESHELL-from-rules.mk.patch
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/README.md
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XL

#3089 Filter out pre-release tags in upgrader flow
  tools/version-tracker/pkg/github/github.go
Labels: size/S

#3080 Bump capv version to 1.9.3
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-vsphere/GOLANG_VERSION
  projects/kubernetes-sigs/cluster-api-provider-vsphere/README.md
  projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0001-Add-capv-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/XL, area/dependencies

#3034 Add download/push scripts for Ubuntu RTOS EKS-A image
  projects/canonical/ubuntu/Help.mk
  projects/canonical/ubuntu/Makefile
  projects/canonical/ubuntu/RTOS_IMAGE_DATE
  projects/canonical/ubuntu/build/download_rtos_image.sh
  projects/canonical/ubuntu/expected_artifacts
  release/staging-build.yml
Labels: approved, lgtm, size/L

#3104 Bump etcd to 1.0.21
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/ATTRIBUTION.txt
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#3106 Bump aws eksa packages to latest
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/S

#3114 Add patch to update Ubuntu 22.04 ISO URLs to latest stable release
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Revert-updates-to-Ubuntu-2004-ISO-URLs.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Update-Ubuntu-22.04-ISO-URLs-to-use-stable-URLs.patch
Labels: approved, lgtm, size/L

#3112 Bump Eks-d release to latest on main
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#3109 Improve build fail remediation logic to factor in newer docker versions
  build/lib/buildkit.sh
Labels: approved, lgtm, size/XS

#3115 Add patch to update Ubuntu 22.04 ISO URLs to latest stable release
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Adds-support-for-cloudstack-rhel-9.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Update-Ubuntu-22.04-ISO-URLs-to-use-stable-URLs.patch
Labels: approved, lgtm, size/L

#3116 Handle cases where GitHub release does not exist for tag
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/S

#3127 Fix Go mod location for cluster-autoscaler
  tools/version-tracker/pkg/constants/constants.go
Labels: size/XS

#3128 Backport eks anywhere packages project changes
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/GOLANG_VERSION
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/XL

#3132 Bump packages to latest version 0.4.3
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/M
