Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-11, with the labels that each got.

#4014 Skip CAPI upgrade on release branches
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#4023 Add identifying label to PRs upgrading curated packages
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, do-not-merge/hold, size/S

#4026 Fix labels assignment on pull requests
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: size/XS

#4041 Add patch to use docker_tag file to fetch Kubernetes source version
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/kind/patches/0004-Disable-cgroupns-private-to-fix-cluster-creation-on-.patch
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
  projects/kubernetes-sigs/kind/patches/0006-Use-docker_tag-file-to-fetch-Kubernetes-source-versi.patch
Labels: approved, lgtm, size/M

#4046 Update kindnetd and storage helper images for Kind node image build
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
Labels: approved, lgtm, size/S

#4018 Migrate harbor-scanner-trivy project from aquasecurity to goharbor
  UPSTREAM_PROJECTS.yaml
  projects/goharbor/harbor-scanner-trivy/.gitignore
  projects/goharbor/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/goharbor/harbor-scanner-trivy/CHECKSUMS
  projects/goharbor/harbor-scanner-trivy/GIT_TAG
  projects/goharbor/harbor-scanner-trivy/GOLANG_VERSION
  projects/goharbor/harbor-scanner-trivy/Help.mk
  projects/goharbor/harbor-scanner-trivy/Makefile
  projects/goharbor/harbor-scanner-trivy/README.md
  projects/goharbor/harbor-scanner-trivy/expected_artifacts
  projects/goharbor/harbor/Help.mk
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile
  release/checksums-build.yml
  tools/version-tracker/README.md
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/M

#4043 Fix checksums for replicatedhq/troubleshoot
  projects/replicatedhq/troubleshoot/CHECKSUMS
Labels: approved, size/XS

#4053 Fix checksums for kube-vip/kube-vip
  projects/kube-vip/kube-vip/CHECKSUMS
Labels: approved, lgtm, size/XS

#4064 Update kind manifest image tags during upgrade flow
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/update_manifest_images.sh
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#4072 Install emulator only for architecture not matching with host
  build/lib/setup.sh
Labels: approved, lgtm, size/S

#4075 Fix if condition in setup script
  build/lib/setup.sh
Labels: size/XS

#4078 Fix condition for current architecture in setup script
  build/lib/setup.sh
Labels: size/XS
