Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-06, with the labels that each got.

#3237 Bump nutanix-cloud-native/cluster-api-provider-nutanix to latest release
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GOLANG_VERSION
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/L, area/dependencies

#3235 Bump containerd to latest version
  UPSTREAM_PROJECTS.yaml
  projects/containerd/containerd/ATTRIBUTION.txt
  projects/containerd/containerd/CHECKSUMS
  projects/containerd/containerd/GIT_TAG
  projects/containerd/containerd/README.md
Labels: approved, lgtm, size/L

#3234 Make image-builder upgrade flow non-release-branched
  build/lib/generate_staging_buildspec.sh
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3239 harbor no longer needs to skip go mod download
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/Makefile
Labels: approved, lgtm, size/S

#3238 Bump latest version to 1-26 on EKD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#3243 Bump CAPT to v0.5.3
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3245 Cherry-pick: Bump nutanix-cloud-native/cluster-api-provider-nutanix to latest release
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GOLANG_VERSION
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/L, ok-to-test

#3244 Use latest release branch by default if not defined, fall back to Github file for Go versions
  Makefile
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L

#3249 Avoid printing directory name for Make command
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#3246 Bump image-builder and EKS Distro releases to latest
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/Help.mk
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/REQUIRED_DEPENDENCY_VERSIONS.yaml
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Adds-support-for-cloudstack-rhel-9.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Update-Ubuntu-22.04-ISO-URLs-to-use-stable-URLs.patch
Labels: approved, lgtm, size/XL

#3242 Update kubernetes sigs kind
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/GOLANG_VERSION
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/Makefile
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/download-images.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/run.sh
  projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/hack/print-workspace-status.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/kind/patches/0004-Disable-cgroupns-private-to-fix-cluster-creation-on-.patch
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
  projects/kubernetes-sigs/kind/patches/0006-Add-a-new-builder-for-tarballs-and-released-artifact.patch
Labels: approved, lgtm, size/XL

#3255 Revert "Bump CAPT to v0.5.3"
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3270 Add buildspec for Nutanix image builds
  projects/kubernetes-sigs/image-builder/buildspecs/nutanix.yml
Labels: approved, lgtm, size/S

#3273 Use go.mod file to retrieve cert-manager Go version
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#3267 Fix kubeadm upgrade flow for k8s version 1.30 and above
  projects/aws/upgrader/ATTRIBUTION.txt
  projects/aws/upgrader/CHECKSUMS
  projects/aws/upgrader/go.mod
  projects/aws/upgrader/go.sum
  projects/aws/upgrader/upgrade/kubeadm.go
  projects/aws/upgrader/upgrade/kubeadm_test.go
  projects/aws/upgrader/upgrade/kubeadm_types.go
  projects/aws/upgrader/upgrade/kubelet_kubectl_test.go
  projects/aws/upgrader/upgrade/status.go
Labels: approved, lgtm, size/XL

#3276 Remove jiayiwang7 and taneyland from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3268 Update metallb to v0.14.5
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/ATTRIBUTION.txt
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/GOLANG_VERSION
  projects/metallb/metallb/README.md
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: lgtm, size/XL

#3258 Bump containerd to latest
  UPSTREAM_PROJECTS.yaml
  projects/containerd/containerd/ATTRIBUTION.txt
  projects/containerd/containerd/CHECKSUMS
  projects/containerd/containerd/GIT_TAG
  projects/containerd/containerd/README.md
Labels: approved, lgtm, size/M

#3283 Update helm build to build dependencies only if required
  Common.mk
  build/lib/helm_build.sh
  projects/tinkerbell/charts/Makefile
Labels: approved, lgtm, size/S

#3229 Update ADOT to v0.39.0
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/helm/patches/0001-Update-image-repo.patch
  projects/aws-observability/aws-otel-collector/helm/patches/0002-Add-namespace-to-charts.patch
  projects/aws-observability/aws-otel-collector/helm/patches/0003-Update-default-values.patch
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/L

#3282 adds ova validation to check kubelet version
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/make_fake_image.sh
  projects/kubernetes-sigs/image-builder/build/validate_ova_kubelet.sh
Labels: approved, lgtm, size/L

#3266 Add Bottlerocket kubernetes settings for kubelet configuration
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
Labels: approved, lgtm, size/XXL

#3232 Update metrics-server helm chart to 3.12.1
  projects/kubernetes-sigs/metrics-server/1-25/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-26/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-28/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-29/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-30/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/README.md
Labels: approved, lgtm, size/L

#3285 Deprecate branch 1-25 from supported release branches
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#3293 [release-0.19] Bump EKS Distro releases to latest
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#3284 Bump BR and image-builder to latest version
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
Labels: approved, lgtm, size/M

#3318 Update helm scripts to work with different folder structures
  Common.mk
  build/lib/helm_build.sh
  build/lib/helm_push.sh
  build/lib/helm_replace.sh
  projects/tinkerbell/charts/Makefile
Labels: approved, lgtm, size/M

#3317 use supported release branches for upstream generation
  UPSTREAM_PROJECTS.yaml
  build/lib/generate_projects_list.sh
Labels: approved, lgtm, size/S

#3319 fixes release branch check for older kube versions
  Common.mk
Labels: approved, lgtm, size/XS

#3320 Exclude GitHub Helm chart release tags
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/XS

#3316 Bump CAPT to v0.5.3
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Allow-inUse-and-provisioned-to-be-used-to-check-hard copy.patch
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3272 Bump smee to v0.11.0
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/GOLANG_VERSION
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/boots/docker/linux/Dockerfile
Labels: approved, lgtm, size/XL

#3321 Bump tinkerbell charts to latest release
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/charts/GIT_TAG
  projects/tinkerbell/charts/README.md
  projects/tinkerbell/charts/helm/patches/0001-Use-smee-default-values-for-flags-when-running-in-ho.patch
  projects/tinkerbell/charts/helm/sedfile.template
  projects/tinkerbell/rufio/docker/linux/Dockerfile
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3322 Patch for updated manifests post CAPI bump v1.7.2
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
Labels: approved, lgtm, size/XL

#3330 Fix helm chart namespace issue for prometheus package upgrade
  projects/prometheus/prometheus/helm/patches/0001-Remove-prometheus-chart-dependencies.patch
  projects/prometheus/prometheus/helm/patches/0002-Add-node-exporter-component.patch
  projects/prometheus/prometheus/helm/patches/0003-Update-image-repo.patch
  projects/prometheus/prometheus/helm/patches/0004-Add-namespace-to-charts.patch
  projects/prometheus/prometheus/helm/patches/0005-Update-pod-update-strategy-due-to-configmap-changes.patch
  projects/prometheus/prometheus/helm/patches/0006-Update-values.yaml-and-add-values.schema.json.patch
Labels: approved, lgtm, size/S

#3331 Add jhaanvi5 to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3332 Fix nginx image and nginx.conf files
  projects/tinkerbell/charts/helm/patches/0001-Load-stream-model-for-nginx-and-update-http2-command.patch
  projects/tinkerbell/charts/helm/patches/0002-Use-smee-default-values-for-flags-when-running-in-ho.patch
  projects/tinkerbell/tink/docker/linux/nginx/Dockerfile
Labels: approved, lgtm, size/M

#3333 Update ecr-credential-provider binary
  projects/aws/eks-anywhere-packages/Help.mk
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  release/staging-build.yml
Labels: approved, lgtm, size/S

#3338 Cleanup legacy tinkerbell chart
  projects/tinkerbell/tinkerbell-chart/GIT_TAG
  projects/tinkerbell/tinkerbell-chart/README.md
  projects/tinkerbell/tinkerbell-chart/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/boots/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/config-map.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/envoy/service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/hegel/service.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/daemonset.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/kube-vip/rbac.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/cluster_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/cluster_role_binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/deprecated-baseboardmanagement-crd.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/leader_election_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/leader_election_role_binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/manager_configmap.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/rufio/service_account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/cluster_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/cluster_role_binding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/leader_election_role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/leader_election_rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-controller/service_account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/deployment.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/role.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/rolebinding.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/service-account.yaml
  projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/service.yaml
  projects/tinkerbell/tinkerbell-chart/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#3275 Allow project upgrades on release branch
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L

#3354 Switch to t3.micro instances for raw image build presubmits
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#3271 use kube-server.tgz directly for kind node image
  build/lib/fetch_binaries.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
Labels: approved, lgtm, size/M

#3323 Updated trivy to v0.50.1 and harbor-scanner-trivy to v0.30.23
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/aquasecurity/harbor-scanner-trivy/CHECKSUMS
  projects/aquasecurity/harbor-scanner-trivy/GIT_TAG
  projects/aquasecurity/harbor-scanner-trivy/GOLANG_VERSION
  projects/aquasecurity/harbor-scanner-trivy/README.md
  projects/aquasecurity/harbor-scanner-trivy/patches/0001-security-patch.patch
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/GOLANG_VERSION
  projects/aquasecurity/trivy/Makefile
  projects/aquasecurity/trivy/README.md
  projects/aquasecurity/trivy/patches/0001-Replace-mitchellh-os-ext-with-kardianos-os-ext-modul.patch
  projects/aquasecurity/trivy/patches/0001-security-patch.patch
Labels: approved, lgtm, size/XXL

#3364 Update Ubuntu RTOS image version
  projects/canonical/ubuntu/Makefile
  projects/canonical/ubuntu/RTOS_IMAGE_DATE
  projects/canonical/ubuntu/build/download_rtos_image.sh
Labels: approved, lgtm, size/S

#3383 Backport upgrader changes to release-0.19 branch
  Common.mk
  Makefile
  build/lib/generate_staging_buildspec.sh
  build/lib/helm_replace.sh
  build/lib/helm_require.sh
  buildspecs/upgrade-eks-distro-buildspec.yml
  projects/aws/image-builder/builder/artifacts.go
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/utils.go
  projects/aws/image-builder/builder/utils_test.go
  projects/aws/image-builder/cmd/downloadartifacts.go
  projects/aws/rolesanywhere-credential-helper/Makefile
  projects/cilium/cilium/Makefile
  projects/kubernetes/autoscaler/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/prometheus/prometheus/Makefile
  tools/version-tracker/Makefile
  tools/version-tracker/SKIPPED_PROJECTS
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/types/types.go
  tools/version-tracker/pkg/util/file/file.go
  tools/version-tracker/pkg/util/slices/slices.go
  tools/version-tracker/pkg/util/tar/tar.go
  tools/version-tracker/pkg/util/version/version.go
Labels: lgtm, size/XXL

#3403 only search for nongolang licenses in root
  build/lib/common.sh
  projects/torvalds/linux/Makefile
Labels: approved, lgtm, size/XS
