Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-05, with the labels that each got.

#3110 Allow running EKS-A admin image build on Darwin, update Ubuntu ISO URL
  projects/aws/eks-a-admin-image/Makefile
  projects/aws/eks-a-admin-image/build/get_latest_eksa_version_by_date.sh
  projects/aws/eks-a-admin-image/ova/linux/ubuntu/vsphere.ubuntu.pkrvars.hcl
  projects/aws/eks-a-admin-image/provisioners/install_golang.sh
Labels: size/S

#3135 [PR BOT] Update base image in tag file(s)
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
Labels: approved, size/XS

#3136 Allow upgrading projects tracked with commits
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/github/github.go
Labels: size/M

#3139 Update external etcd patch to use the right address type
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
Labels: approved, lgtm, size/M

#3140 Fix pre-release detection logic when fetching latest GitHub revision
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: size/M

#3142 Fix cert-manager GitHub release tarball name
  tools/version-tracker/pkg/constants/constants.go
Labels: size/XS

#3147 Use prod metrics-server image instead of dev
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
Labels: approved, lgtm, size/XS

#3146 Bump eks-d releases to latest
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#3150 Handle patches application for release-branched projects
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: size/S

#3151 Add log showing packer http server ip change
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/XS

#3156 Add retry when there ssh connection timeout during image building
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#3134 Add br ova support for release branch 130
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#3164 Allow projects to selectively upgrade to pre-release tags
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: size/XS

#3166 Remove dependencies for EKS Distro version upgrade step
  Makefile
  build/lib/generate_staging_buildspec.sh
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#3107 Bump tinkerbell/actions to latest commit
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/hub/ATTRIBUTION.txt
  projects/tinkerbell/hub/CEXEC_ATTRIBUTION.txt
  projects/tinkerbell/hub/CHECKSUMS
  projects/tinkerbell/hub/GIT_TAG
  projects/tinkerbell/hub/GOLANG_VERSION
  projects/tinkerbell/hub/Help.mk
  projects/tinkerbell/hub/IMAGE2DISK_ATTRIBUTION.txt
  projects/tinkerbell/hub/KEXEC_ATTRIBUTION.txt
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/hub/README.md
  projects/tinkerbell/hub/WRITEFILE_ATTRIBUTION.txt
  projects/tinkerbell/hub/docker/linux/cexec/Dockerfile
  projects/tinkerbell/hub/docker/linux/image2disk/Dockerfile
  projects/tinkerbell/hub/docker/linux/kexec/Dockerfile
  projects/tinkerbell/hub/docker/linux/oci2disk/Dockerfile
  projects/tinkerbell/hub/docker/linux/writefile/Dockerfile
  projects/tinkerbell/hub/patches/0001-Add-Bootconfig-support-to-WriteFile-action.patch
  projects/tinkerbell/hub/patches/0001-Add-Bootconfig-support-to-WriteFile.patch
  projects/tinkerbell/hub/patches/0002-Get-user-data-from-Hegel-and-write-to-disk.patch
  projects/tinkerbell/hub/patches/0003-Write-DHCP-offer-to-static-Netplan-file.patch
  projects/tinkerbell/hub/patches/0004-Create-VLAN-tagged-interface-if-vlan_id-exists-in-pr.patch
  projects/tinkerbell/hub/patches/0004-Modify-write-file-to-read-multiple-HEGEL_URLS.patch
  projects/tinkerbell/hub/patches/0005-Add-static-IP-configuration-for-Bottlerocket.patch
  projects/tinkerbell/hub/patches/0005-Create-VLAN-tagged-interface-if-vlan_id-exists-in-pr.patch
  projects/tinkerbell/hub/patches/0006-Fix-net-interface-lookup.patch
  projects/tinkerbell/hub/patches/0007-Update-vlan-checking.patch
  projects/tinkerbell/hub/patches/0008-Fix-netplan-vlan-file.patch
  projects/tinkerbell/hub/patches/0009-Use-MAC-address-in-Bottlerocket-network-config.patch
  projects/tinkerbell/hub/patches/0010-Handle-non-200-status-codes-from-metadata-service.patch
  projects/tinkerbell/hub/patches/0011-Ensure-content-is-specified-before-writing-file.patch
  projects/tinkerbell/hub/patches/0012-Allow-BOOTCONFIG_CONTENTS-and-CONTENTS-to-be-checked.patch
Labels: approved, lgtm, size/XXL

#3174 Refactor latest release logic for EKS Distro upgrades
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: size/L

#3178 Add patch to revert deprecation of disk size capacityInKB field
  projects/vmware/govmomi/CHECKSUMS
  projects/vmware/govmomi/patches/0001-Revert-zero-value-change-for-capacityInKB.patch
Labels: approved, lgtm, size/S

#3179 [release-0.19] Bump EKS Distro releases to latest (#3167)
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#3180 Build Nutanix images in CI
  build/lib/create_release_checksums.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/buildspecs/nutanix.yml
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_nutanix
Labels: approved, do-not-merge/hold, size/L

#3188 Remove chrisdoherty4 and jonathanmeier5 from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3191 Add patch to force-delete Nutanix builder VMs
  projects/kubernetes-sigs/image-builder/patches/0001-Force-delete-Nutanix-builder-VMs-on-failure.patch
Labels: approved, lgtm, size/S

#3194 Bump fluxcd/source-controller to latest release
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/source-controller/ATTRIBUTION.txt
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/GOLANG_VERSION
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/patches/0001-Replace-timestamp-authority-and-go-fuzz-headers-revi.patch
Labels: approved, lgtm, size/XL

#3209 Revert "Bump nutanix-cloud-native/cluster-api-provider-nutanix to lat…
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GOLANG_VERSION
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
Labels: approved, lgtm, size/L

#3210 Update instance to t3.micro
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#3211 Add retries in case of Nutanix image size mismatch
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#3216 Temporary change for nutanix image-builder test
  projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0009-point-to-abhnvp-github.patch
Labels: size/S

#3217 Revert "Temporary change for nutanix image-builder test"
  projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0009-point-to-abhnvp-github.patch
Labels: approved, lgtm, size/S

#3218 Remove Nutanix images from expected artifacts list
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_nutanix
Labels: approved, lgtm, size/S

#3220 Fix the issue of patch repo in upgrade cmd
  Common.mk
  tools/version-tracker/pkg/util/version/version.go
Labels: approved, lgtm, size/XS

#3204 Bump autoscaler for branch 1-26,1-27,1-29 and 1-30 to latest release
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/autoscaler/1-26/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-26/CHECKSUMS
  projects/kubernetes/autoscaler/1-26/GIT_TAG
  projects/kubernetes/autoscaler/1-26/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-26/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-26/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/1-27/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-27/CHECKSUMS
  projects/kubernetes/autoscaler/1-27/GIT_TAG
  projects/kubernetes/autoscaler/1-27/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-27/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-27/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/1-29/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-29/CHECKSUMS
  projects/kubernetes/autoscaler/1-29/GIT_TAG
  projects/kubernetes/autoscaler/1-29/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-29/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-29/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-29/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/1-30/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-30/CHECKSUMS
  projects/kubernetes/autoscaler/1-30/GIT_TAG
  projects/kubernetes/autoscaler/1-30/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-30/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-30/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-30/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-30/patches/0002-Remove-additional-GCE-Dependencies.patch
  projects/kubernetes/autoscaler/1-30/patches/0003-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/XXL

#3221 Bump bottlerocket-bootstrap to Go 1.22, rename Go modules for consistency
  projects/aws/bottlerocket-bootstrap/ATTRIBUTION.txt
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/GOLANG_VERSION
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/go.mod
  projects/aws/bottlerocket-bootstrap/go.sum
  projects/aws/bottlerocket-bootstrap/main.go
  projects/aws/bottlerocket-bootstrap/pkg/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/etcdadm.go
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/init.go
  projects/aws/bottlerocket-bootstrap/pkg/etcdadm/join.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/apiclient_test.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/filesystem_test.go
  projects/aws/bottlerocket-bootstrap/pkg/executables/mocks/executables_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/kubeadm.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils_test.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/waiters.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/worker_join.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/main.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/bootstrap.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kernel.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/kubernetes.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/mocks/apiclient_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/mocks/filesystem_mock.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/network_test.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/reboot.go
  projects/aws/bottlerocket-bootstrap/pkg/providers/snow/system/volume.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go
  projects/aws/bottlerocket-bootstrap/pkg/utils/userdata_test.go
  projects/aws/upgrader/.gitignore
  projects/aws/upgrader/ATTRIBUTION.txt
  projects/aws/upgrader/CHECKSUMS
  projects/aws/upgrader/Makefile
  projects/aws/upgrader/cmd/status.go
  projects/aws/upgrader/cmd/upgradecniplugins.go
  projects/aws/upgrader/cmd/upgradecontainerd.go
  projects/aws/upgrader/cmd/upgradekubeletkubectl.go
  projects/aws/upgrader/cmd/upgradenode.go
  projects/aws/upgrader/go.mod
  projects/aws/upgrader/hack/tools/.gitignore
  projects/aws/upgrader/main.go
  projects/aws/upgrader/upgrade/kubeadm_test.go
  projects/aws/upgrader/upgrade/mocks/syscalls_mock.go
  projects/aws/upgrader/upgrade/upgrader_test.go
Labels: approved, lgtm, size/L

#3173 Add patch for failure domain reassignment for CAPC
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch
Labels: approved, lgtm, size/XXL
