Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-03, with the labels that each got.

#2962 Add back IMAGE_OS_VERSION in Cloudstack buildspec
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
Labels: size/XS

#2965 Revert CAPI to v1.6.1 and cert-manager to v1.13.2
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/GOLANG_VERSION
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0004-Update-cert-manager-namespace-config.patch
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/GOLANG_VERSION
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0040-Use-controller-runtime-patch-for-restmapper-cache.patch
Labels: approved, lgtm, size/XXL

#2973 Automate Cilium and EKS Distro releases upgrade
  Makefile
  buildspecs/upgrade-eks-distro-buildspec.yml
  projects/cilium/cilium/Makefile
  tools/version-tracker/SKIPPED_PROJECTS
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/types/types.go
Labels: approved, lgtm, size/XL

#2974 Bump EKS-D to latest version
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2978 Extract only the Go binary from GitHub release tarball
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/util/tar/tar.go
Labels: approved, lgtm, size/M

#2982 Update image-builder buildspec to use colo vsphere
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
Labels: approved, lgtm, size/S

#2983 Allow different tags for required images in Helm charts
  Common.mk
  build/lib/helm_replace.sh
  build/lib/helm_require.sh
  projects/prometheus/prometheus/Makefile
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
Labels: approved, lgtm, size/L

#2987 Remove rolesanywhere-credential-helper project from upgrade buildspec
  projects/aws/rolesanywhere-credential-helper/Makefile
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/S

#2988 Remove patch for building OVAs using content library
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/types.go
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Adds-support-for-cloudstack-rhel-9.patch
Labels: approved, lgtm, size/L

#2993 Always delete the Packer builder VM at the end of the build
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
Labels: approved, lgtm, size/S

#2970 Adding patch for BR multiple reg mirrors
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0039-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0041-Use-controller-runtime-patch-for-restmapper-cache.patch
  projects/kubernetes-sigs/cluster-api/patches/0042-enable-kubeadm-feature-flags-mutation.patch
Labels: approved, lgtm, size/XL

#3001 Fix kubeversion formatting in EKSD_LATEST_RELEASES
  EKSD_LATEST_RELEASES
Labels: size/S

#2992 Attempt to apply patches and generate checksums/attribution if successful
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L

#3002 Remove newlines from kubeVersion field
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/S

#3003 Update CAPT to v0.5.2
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/GOLANG_VERSION
  projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/build/create_manifests.sh
Labels: approved, lgtm, size/L

#3004 Backporting EKS-D release versions for release v0.19.1
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#3009 Fix checksums and attribution generation during upgrade
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/M

#3015 Update CAPC to 0.4.10-rc1
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#3018 Revert "[release-0.19] Update CAPC to 0.4.10-rc1"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#3022 Place RHEL kickstart files for raw builds in `http` directory
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Revert-updates-to-Ubuntu-2004-ISO-URLs.patch
Labels: approved, lgtm, size/M

#3023 Update ISO URL for Ubuntu 22.04 raw builds
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
Labels: size/S

#3026 Update CAPC to 0.4.10-rc1 (#3015)
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
Labels: approved, lgtm, size/S

#3028 Bump EKS-D releases to latest
  EKSD_LATEST_RELEASES
Labels: size/S

#3032 Image builder CLI changes to support rhel-9 raw image building
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/M

#3038 Fix condition for patches warning comment on upgrade PRs
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
Labels: size/M
