Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-02, with the labels that each got.

#2871 Bump prometheus/node_exporter to latest release
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/node_exporter/ATTRIBUTION.txt
  projects/prometheus/node_exporter/CHECKSUMS
  projects/prometheus/node_exporter/GIT_TAG
  projects/prometheus/node_exporter/GOLANG_VERSION
  projects/prometheus/node_exporter/README.md
  projects/prometheus/node_exporter/patches/0001-update-go-mod.patch
Labels: approved, lgtm, size/L

#2873 Bump prometheus/prometheus to latest release
  UPSTREAM_PROJECTS.yaml
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/GIT_TAG
  projects/prometheus/prometheus/GOLANG_VERSION
  projects/prometheus/prometheus/README.md
Labels: approved, lgtm, size/S

#2874 Bump cloud-provider-vsphere tag for Kubernetes v1.29
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/cloud-provider-vsphere/1-29/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-29/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-29/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/README.md
Labels: approved, lgtm, size/S

#2872 Backport updates for Bottlerocket, containerd and runc
  UPSTREAM_PROJECTS.yaml
  projects/containerd/containerd/ATTRIBUTION.txt
  projects/containerd/containerd/CHECKSUMS
  projects/containerd/containerd/GIT_TAG
  projects/containerd/containerd/GOLANG_VERSION
  projects/containerd/containerd/README.md
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/opencontainers/runc/ATTRIBUTION.txt
  projects/opencontainers/runc/CHECKSUMS
  projects/opencontainers/runc/GIT_TAG
  projects/opencontainers/runc/README.md
Labels: approved, lgtm, size/L

#2880 Fix metallb helm chart
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/M

#2879 Bump Bottlerocket release version to latest
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#2881 Bump Bottlerocket release version to latest
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2883 Revert Bottlerocket release update for 1.24 OVA and raw images
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#2893 Patch capi to fix stale cache for all v1alpha4
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0038-Restart-controller-if-RESTMapping-outdated-cache-is-.patch
Labels: approved, lgtm, size/M

#2894 Revert emissary version bump
  UPSTREAM_PROJECTS.yaml
  projects/emissary-ingress/emissary/APPMESH_VERSION
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GIT_TAG
  projects/emissary-ingress/emissary/GOLANG_VERSION
  projects/emissary-ingress/emissary/README.md
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
Labels: approved, lgtm, size/M

#2895 Fix MD controller reconcilation with in-place
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0040-Fix-MD-controller-reconcilation-with-in-place.patch
Labels: approved, lgtm, size/XL

#2900 Use python 3.11 for building emissary
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/docker/linux/emissary/Dockerfile
Labels: approved, lgtm, size/XS

#2901 Revert "Revert emissary version bump"
  UPSTREAM_PROJECTS.yaml
  projects/emissary-ingress/emissary/APPMESH_VERSION
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GIT_TAG
  projects/emissary-ingress/emissary/GOLANG_VERSION
  projects/emissary-ingress/emissary/README.md
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
Labels: approved, lgtm, size/M

#2903 Update Flux CLI and controller projects to latest
  UPSTREAM_PROJECTS.yaml
  projects/fluxcd/flux2/CHECKSUMS
  projects/fluxcd/flux2/GIT_TAG
  projects/fluxcd/flux2/README.md
  projects/fluxcd/flux2/patches/0001-Replace-unknown-go-crypto-revision-with-correct-pseu.patch
  projects/fluxcd/helm-controller/ATTRIBUTION.txt
  projects/fluxcd/helm-controller/CHECKSUMS
  projects/fluxcd/helm-controller/GIT_TAG
  projects/fluxcd/helm-controller/GOLANG_VERSION
  projects/fluxcd/helm-controller/README.md
  projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
  projects/fluxcd/kustomize-controller/CHECKSUMS
  projects/fluxcd/kustomize-controller/GIT_TAG
  projects/fluxcd/kustomize-controller/GOLANG_VERSION
  projects/fluxcd/kustomize-controller/README.md
  projects/fluxcd/notification-controller/CHECKSUMS
  projects/fluxcd/notification-controller/GIT_TAG
  projects/fluxcd/notification-controller/README.md
  projects/fluxcd/notification-controller/patches/0001-Replace-unknown-go-crypto-revision-with-correct-pseu.patch
  projects/fluxcd/source-controller/CHECKSUMS
  projects/fluxcd/source-controller/GIT_TAG
  projects/fluxcd/source-controller/README.md
  projects/fluxcd/source-controller/patches/0001-Replace-timestamp-authority-and-go-fuzz-headers-revi.patch
  projects/fluxcd/source-controller/patches/0001-Replace-unknown-go-crypto-and-go-fuzz-headers-revisi.patch
Labels: approved, size/XL

#2891 Handle KubeletCredentialProviders extraargs for in-place upgrades
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/M

#2911 Bump EKS-D to latest version
  EKSD_LATEST_RELEASES
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2917 Fix image-builder builds in dev release mode
  build/lib/eksa_releases.sh
  projects/aws/image-builder/Makefile
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/utils.go
Labels: approved, lgtm, size/S

#2918 Add 1-29 release branch Bottlerocket artifacts
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
  projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
Labels: approved, lgtm, size/S

#2916 Swap capi CRD race condition patch for CR bump
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Add-bottlerocket-control-image-on-nodes-joining-a-ne.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Restart-controller-if-RESTMapping-outdated-cache-is-.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Bump-controller-runtime-to-v0.16.4.patch
Labels: approved, lgtm, size/XL

#2921 Ensure proper values are passed to release branch support check
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
Labels: approved, lgtm, size/XS

#2923 Go back to capi patch for CRD race condition
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0040-Bump-controller-runtime-to-v0.16.4.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Restart-controller-if-RESTMapping-outdated-cache-is-.patch
Labels: approved, lgtm, size/L

#2924 Print patched kube-vip manifest to stdout
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
Labels: approved, lgtm, size/XS

#2925 Use generic parser for kubeadm version check
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
Labels: approved, lgtm, size/XS

#2929 Swap capi race condition patch for new CR version
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0040-Restart-controller-if-RESTMapping-outdated-cache-is-.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Use-controller-runtime-patch-for-restmapper-cache.patch
Labels: approved, lgtm, size/L

#2926 Handle kube-vip manifest update in the upgrader script
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/S

#2930 Use production release of Kubernetes v1.29 Bottlerocket OVA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#2931 Enforce legacy iptables, fix Kind dependency image tags
  build/lib/setup.sh
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
Labels: approved, lgtm, size/S

#2934 Fix upgrader script to check if kubelet config exists before updating it
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/S

#2936 Remove IMAGE_OS_VERSION command-line Make variable
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
Labels: approved, lgtm, size/XS

#2939 Allow overriding Make variables related to image OS and OS version
  projects/kubernetes-sigs/image-builder/Makefile
Labels: approved, lgtm, size/XS

#2944 Fix upgrader script
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/XS

#2868 Add Instructions for Validating Helm Chart
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/S

#2955 Revert CAPI to v1.6.1 and cert-manager to v1.13.2
  UPSTREAM_PROJECTS.yaml
  projects/cert-manager/cert-manager/CERT_MANAGER_ACMESOLVER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CAINJECTOR_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CONTROLLER_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_CTL_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CERT_MANAGER_WEBHOOK_ATTRIBUTION.txt
  projects/cert-manager/cert-manager/CHECKSUMS
  projects/cert-manager/cert-manager/GIT_TAG
  projects/cert-manager/cert-manager/GOLANG_VERSION
  projects/cert-manager/cert-manager/README.md
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0004-Update-cert-manager-namespace-config.patch
  projects/cert-manager/cert-manager/manifests/cert-manager.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/GOLANG_VERSION
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0040-Use-controller-runtime-patch-for-restmapper-cache.patch
Labels: approved, lgtm, size/XXL

#2958 add capi patch to enable kubeadm feature flags mutation
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0041-enable-kubeadm-feature-flags-mutation.patch
Labels: approved, lgtm, size/XXL

#2959 Automate Bottlerocket release version updates
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/git/git.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/util/file/file.go
  tools/version-tracker/pkg/util/slices/slices.go
Labels: approved, lgtm, size/XL
