Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-12, with the labels that each got.

#4107 Fix artifacts path for KVM image builds
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
Labels: approved, lgtm, size/XS

#4106 Upgrade eks-anywhere-packages to v0.4.5
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/S

#4108 Bump Ipxedust to latest version
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/ipxedust/CHECKSUMS
  projects/tinkerbell/ipxedust/GIT_TAG
  projects/tinkerbell/ipxedust/README.md
Labels: approved, lgtm, size/S

#4109 Add patch to fix state for Ansible RHSM repository module
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: size/M

#4118 Fixing typos in README 🐛
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#4121 Always download Nutanix source images and delete them after build
  projects/aws/image-builder/builder/types.go
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/M

#4122 [release-0.20] Add 2ez4szliu to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#4115 Update CAPT and Tink stack components to latest release for consuming L3 provisioning changes
  UPSTREAM_PROJECTS.yaml
  build/lib/helm_replace.sh
  projects/replicatedhq/troubleshoot/CHECKSUMS
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/GOLANG_VERSION
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/charts/GIT_TAG
  projects/tinkerbell/charts/README.md
  projects/tinkerbell/charts/helm/patches/0001-Load-stream-model-for-nginx-and-update-http2-command.patch
  projects/tinkerbell/charts/helm/patches/0002-Use-smee-default-values-for-flags-when-running-in-ho.patch
  projects/tinkerbell/charts/helm/sedfile.template
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/GOLANG_VERSION
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Allow-inUse-and-provisioned-to-be-used-to-check-hard copy.patch
  projects/tinkerbell/hegel/ATTRIBUTION.txt
  projects/tinkerbell/hegel/CHECKSUMS
  projects/tinkerbell/hegel/GIT_TAG
  projects/tinkerbell/hegel/GOLANG_VERSION
  projects/tinkerbell/hegel/README.md
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/GOLANG_VERSION
  projects/tinkerbell/rufio/README.md
  projects/tinkerbell/tinkerbell-crds/GIT_TAG
  projects/tinkerbell/tinkerbell-crds/README.md
  projects/tinkerbell/tinkerbell-crds/chart/Chart.yaml
  projects/tinkerbell/tinkerbell-crds/chart/templates/rufio/bmc.tinkerbell.org_jobs.yaml
  projects/tinkerbell/tinkerbell-crds/chart/templates/rufio/bmc.tinkerbell.org_machines.yaml
  projects/tinkerbell/tinkerbell-crds/chart/templates/rufio/bmc.tinkerbell.org_tasks.yaml
  projects/tinkerbell/tinkerbell-crds/chart/templates/tink-controller/tinkerbell.org_hardware.yaml
  projects/tinkerbell/tinkerbell-crds/chart/templates/tink-controller/tinkerbell.org_templates.yaml
  projects/tinkerbell/tinkerbell-crds/chart/templates/tink-controller/tinkerbell.org_workflows.yaml
  projects/tinkerbell/tinkerbell-crds/chart/values.yaml
  projects/tinkerbell/tinkerbell-crds/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#4126 Bump nutanix-cloud-native/cloud-provider-nutanix to v0.4.1
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cloud-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cloud-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cloud-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cloud-provider-nutanix/GOLANG_VERSION
  projects/nutanix-cloud-native/cloud-provider-nutanix/README.md
Labels: approved, lgtm, size/L, ok-to-test

#4127 Fix Helm sedfile template for Tinkerbell charts
  projects/tinkerbell/charts/helm/sedfile.template
Labels: approved, lgtm, size/XS

#4128 Fix checksums for replicatedhq/troubleshoot
  projects/replicatedhq/troubleshoot/CHECKSUMS
Labels: size/XS

#4133 breaks kind batch build up even more
  Common.mk
  build/lib/generate_staging_buildspec.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/buildspecs/base-images.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/binaries.yml
  projects/kubernetes-sigs/kind/buildspecs/node-images.yml
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XL

#4135 Remove unnecessary builds from batch buildspecs
  Common.mk
  build/lib/validate_release_buildspecs.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: size/L

#4134 [release-0.20] breaks kind batch build up even more
  Common.mk
  build/lib/generate_staging_buildspec.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/buildspecs/base-images.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/binaries.yml
  projects/kubernetes-sigs/kind/buildspecs/node-images.yml
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XL

#4137 [release-0.20] Remove unnecessary builds from batch buildspecs
  Common.mk
  build/lib/validate_release_buildspecs.sh
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes/cloud-provider-aws/Makefile
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#4139 Fix ARM64 checksum for replicatedhq/troubleshoot
  projects/replicatedhq/troubleshoot/CHECKSUMS
Labels: approved, lgtm, size/XS

#4140 Add containerd, CAPX, runc projects to upgrade skip list
  tools/version-tracker/SKIPPED_PROJECTS
Labels: size/XS

#4154 breaks kind batch build up even more
  Common.mk
  build/lib/generate_staging_buildspec.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/buildspecs/base-images.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/binaries.yml
  projects/kubernetes-sigs/kind/buildspecs/node-images.yml
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XL

#4131 Bump down Rufio and bump up Tink versions
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
  projects/tinkerbell/tink/ATTRIBUTION.txt
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/build/create_manifests.sh
  projects/tinkerbell/tink/expected_artifacts
  projects/tinkerbell/tink/patches/0001-Remove-oneshell-from-Makefile.patch
  projects/tinkerbell/tink/patches/0002-Fix-Makefile-goal.patch
Labels: approved, lgtm, size/L

#4155 Add batch buildspec for Tinkerbell Rufio project
  Makefile
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/buildspecs/batch-build.yml
  projects/tinkerbell/tinkerbell-chart/Makefile
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/L

#4157 Add batch buildspec for Tinkerbell Rufio project
  projects/aws/cluster-api-provider-aws-snow/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/tinkerbell-chart/Makefile
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#4158 Add depends-on condition for Rufio combine-images stage
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/buildspecs/batch-build.yml
  release/staging-build.yml
Labels: approved, lgtm, size/XS

#4160 Add missing Rufio buildspec
  Makefile
  projects/tinkerbell/rufio/buildspecs/batch-build.yml
Labels: approved, lgtm, size/M

#4138 improves batch build generation
  Common.mk
  Makefile
  build/lib/generate_staging_buildspec.sh
  build/lib/setup.sh
  build/lib/validate_release_buildspecs.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/upgrader/Makefile
  projects/aws/upgrader/buildspecs/batch-build.yml
  projects/containerd/containerd/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/buildspecs/batch-build.yml
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/buildspecs/batch-build.yml
  projects/isc-projects/dhcp/Makefile
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/br.yml
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/node-images.yml
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/buildspecs/batch-build.yml
  projects/opencontainers/runc/Makefile
  projects/replicatedhq/troubleshoot/Makefile
  projects/tinkerbell/boots/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/buildspecs/batch-build.yml
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/ipxedust/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/buildspecs/batch-build.yml
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/buildspecs/batch-build.yml
  projects/torvalds/linux/Makefile
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#4171 Updated helm patch to include properties for eksa-packages in values.schema.json.
  projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
  projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
  projects/cert-manager/cert-manager/helm/patches/0004-Update-cert-manager-namespace-config.patch
  projects/cert-manager/cert-manager/helm/patches/0005-Update-values.schema.json-for-schema-validation.patch
  projects/cert-manager/cert-manager/helm/schema.json
Labels: approved, lgtm, size/L

#4178 Add env binary to the image
  projects/tinkerbell/tink/docker/linux/tink-relay-init/Dockerfile
Labels: approved, lgtm, size/XS

#4174 Add end of standard support dates for all kubernetes versions above 1.28
  EKSD_LATEST_RELEASES
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/types/types.go
Labels: approved, lgtm, size/S
