Repository aws/eks-anywhere-build-tooling, pull requests merged in 2024-01, with the labels that each got.

#2792 Update Metrics Server Helm Chart
  projects/kubernetes-sigs/metrics-server/1-24/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-25/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-25/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-26/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-28/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-29/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/schema.json
Labels: approved, lgtm, size/XXL

#2795 Bump eks-d to latest versions
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/S

#2798 Fix in-place upgrade script to properly upgrade etcd
  projects/aws/upgrader/upgrade.sh
Labels: approved, lgtm, size/XS

#2745 Deprecate 1-24 release branch builds for projects
  UPSTREAM_PROJECTS.yaml
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/metrics-server/1-24/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-24/helm/sedfile.template
  projects/kubernetes/autoscaler/1-24/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-24/CHECKSUMS
  projects/kubernetes/autoscaler/1-24/GIT_TAG
  projects/kubernetes/autoscaler/1-24/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-24/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-24/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
  projects/kubernetes/autoscaler/1-24/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-24/helm/schema.json
  projects/kubernetes/autoscaler/1-24/helm/sedfile.template
  projects/kubernetes/autoscaler/1-24/patches/0001-Replace-cloud-provider-azure.patch
  projects/kubernetes/autoscaler/1-24/patches/0002-Replace-broken-Go-module-for-Distribution-project-re.patch
  projects/kubernetes/autoscaler/1-24/patches/0003-Fix-CVE-2021-3538-for-version-1.24.patch
  projects/kubernetes/autoscaler/1-24/patches/0004-Fix-CVE-2022-1996-for-1.24.patch
  projects/kubernetes/autoscaler/1-24/patches/0005-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-24/patches/0006-Remove-Deps-for-Other-Cloud-Providers.patch
  projects/kubernetes/cloud-provider-aws/1-24/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-24/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-24/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-24/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-24/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-24/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#2802 Run OVA image builds against dev vCenter
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
Labels: approved, lgtm, size/S

#2703 Add rhel9 support for cloudstack
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0015-adds-support-for-raw-ubuntu-22.04-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0016-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
  projects/kubernetes-sigs/image-builder/patches/0017-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0018-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch
  projects/kubernetes-sigs/image-builder/patches/0019-Add-proxy-register-with-satellite-and-pull-packages-.patch
  projects/kubernetes-sigs/image-builder/patches/0020-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch
  projects/kubernetes-sigs/image-builder/patches/0021-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0022-TEMP-skip-python-3.9-check-if-ansible-already-instal.patch
  projects/kubernetes-sigs/image-builder/patches/0023-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0024-Fix-redhat-9-cloud-init-feature-flags-bug.patch
  projects/kubernetes-sigs/image-builder/patches/0025-Fix-ensure-iptables-present-for-rhel.patch
  projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0027-Adds-support-for-cloudstack-rhel-9.patch
Labels: approved, lgtm, size/L

#2806 fixes kindnetd manifest (again)
  build/lib/common.sh
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/manifests/kindnetd.yaml
Labels: approved, lgtm, size/L

#2695 add image builder dependency version tracker
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/REQUIRED_DEPENDENCY_VERSIONS.yaml
  projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
  projects/kubernetes-sigs/image-builder/build/update_required_deps.sh
  projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
  projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
  projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
  projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Adds-support-for-cloudstack-rhel-9.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
  projects/kubernetes-sigs/image-builder/patches/0011-revert-rhel-9-netowork-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
  projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
  projects/kubernetes-sigs/image-builder/patches/0016-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
  projects/kubernetes-sigs/image-builder/patches/0018-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch
  projects/kubernetes-sigs/image-builder/patches/0020-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch
  projects/kubernetes-sigs/image-builder/patches/0022-TEMP-skip-python-3.9-check-if-ansible-already-instal.patch
  projects/kubernetes-sigs/image-builder/patches/0024-Fix-redhat-9-cloud-init-feature-flags-bug.patch
  projects/kubernetes-sigs/image-builder/patches/0025-Fix-ensure-iptables-present-for-rhel.patch
  projects/kubernetes-sigs/image-builder/patches/0027-disable-gpg-for-extra-rpms.patch
  projects/kubernetes-sigs/image-builder/patches/0028-Remove-old-kernels.patch
  projects/kubernetes-sigs/image-builder/patches/0029--Export-ova-file-independently-to-ignore-nvram-file-t.patch
  projects/kubernetes-sigs/image-builder/patches/0030-Download-and-include-the-nvram.patch
Labels: approved, lgtm, size/XXL

#2810 Update 0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
Labels: approved, lgtm, size/XS

#2811 Add CloudStack dependency version Make target to list
  projects/kubernetes-sigs/image-builder/Makefile
Labels: size/XS

#2801 Update ADOT to v0.36.0
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/helm/patches/0001-image-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0002-namespace-patch.yaml
  projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/L

#2815 Bump up MetalLb to v0.13.12
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/GOLANG_VERSION
  projects/metallb/metallb/README.md
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/L

#2799 Detect PACKER_ACTIVE_INTERFACE with "/proc/net/route" if possible
  projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
Labels: approved, lgtm, size/M, ok-to-test

#2820 Update etcdadm controller to latest tag
  UPSTREAM_PROJECTS.yaml
  projects/aws/etcdadm-controller/CHECKSUMS
  projects/aws/etcdadm-controller/GIT_TAG
  projects/aws/etcdadm-controller/README.md
Labels: approved, lgtm, size/S

#2817 Exclude kernel updates from yum updates in RHEL support and improvements patch
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
Labels: approved, lgtm, size/M

#2824 Fix Bad Metrics Server Schema
  projects/kubernetes-sigs/metrics-server/1-25/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-26/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-28/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-29/helm/schema.json
Labels: approved, lgtm, size/M

#2835 Update ADOT patch to use logging instead of debug exporter
  projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml
Labels: approved, lgtm, size/M

#2825 Bump EKS-D releases to latest
  EKSD_LATEST_RELEASES
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
Labels: approved, lgtm, size/S

#2837 Bump EKS-D releases to latest
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#2836 Bump Bottlerocket release version to latest
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/M

#2842 Add support for cloudstack rhel-9 on aws image-builder
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/cmd/build.go
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
  projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
  projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
  projects/kubernetes-sigs/image-builder/buildspecs/raw.yml
Labels: approved, lgtm, size/S

#2822 ✨ Add CAPI patch to support in-place upgrade in KCP
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0037-Add-support-for-in-place-upgrade-in-KCP.patch
Labels: approved, lgtm, size/L

#2841 Handle race condition when upgrading capi CRDs
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0037-Restart-controller-if-RESTMapping-outdated-cache-is-.patch
Labels: approved, lgtm, size/L

#2840 Disable TCP Checksum Offloading(TCO) on RHEL for vSphere
  projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
Labels: approved, lgtm, size/M

#2847 Add Nutanix Cloud Provider Manager project
  UPSTREAM_PROJECTS.yaml
  projects/nutanix-cloud-native/cloud-provider-nutanix/.gitignore
  projects/nutanix-cloud-native/cloud-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cloud-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cloud-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cloud-provider-nutanix/GOLANG_VERSION
  projects/nutanix-cloud-native/cloud-provider-nutanix/Help.mk
  projects/nutanix-cloud-native/cloud-provider-nutanix/Makefile
  projects/nutanix-cloud-native/cloud-provider-nutanix/README.md
  projects/nutanix-cloud-native/cloud-provider-nutanix/docker/linux/Dockerfile
  projects/nutanix-cloud-native/cloud-provider-nutanix/expected_artifacts
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL, needs-ok-to-test

#2851 ✨ Add support for in-place upgrades in MachineDeployments
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0038-Restart-controller-if-RESTMapping-outdated-cache-is-.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
Labels: approved, lgtm, size/L

#2854 Revert "revert all changes made to update kernels and keep 1 kernel o…
  projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
Labels: approved, lgtm, size/M

#2852 Monitor govc session to ensure full VMDK downloads
  EKSD_LATEST_RELEASES
  projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
  projects/aws/eks-a-admin-image/build/validate-release-manifest-version.sh
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
Labels: approved, lgtm, size/M

#2853 Bump Autoscaler to latest version for release branch 1-28
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/autoscaler/1-28/CHECKSUMS
  projects/kubernetes/autoscaler/1-28/GIT_TAG
  projects/kubernetes/autoscaler/1-28/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-28/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0003-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-28/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/L

#2857 Remove CAPI kube-vip hostPath patch
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
Labels: approved, lgtm, size/S

#2858 Update Cluster Autoscaler 1-26 to latest
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/autoscaler/1-26/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-26/CHECKSUMS
  projects/kubernetes/autoscaler/1-26/GIT_TAG
  projects/kubernetes/autoscaler/1-26/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-26/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-26/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-26/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-26/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-26/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-26/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-26/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-26/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/XL

#2860 Remove raymond-zhang00 from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#2861 Update cluster autoscaler 1-25 to the latest version
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/autoscaler/1-25/CHECKSUMS
  projects/kubernetes/autoscaler/1-25/GIT_TAG
  projects/kubernetes/autoscaler/1-25/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-25/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-25/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-25/patches/0001-Fix-CVE-2021-3538-for-version-1.25.patch
  projects/kubernetes/autoscaler/1-25/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-25/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/XXL

#2863 Use super-admin.conf Kubeconfig for kube-vip from Kubernetes v1.29 onwards
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_join.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/kubeadm.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/utils.go
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/worker_join.go
Labels: approved, lgtm, size/L

#2866 Fix condition for Kubernetes 1.29 check
  projects/aws/bottlerocket-bootstrap/CHECKSUMS
  projects/aws/bottlerocket-bootstrap/pkg/kubeadm/controlplane_init.go
Labels: approved, lgtm, size/XS

#2864 Remove instance of ambassador.namespace in emissary helm chart
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch
Labels: approved, lgtm, size/M

#2865 Update cluster autoscaler 1-29 to latest
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes/autoscaler/1-29/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-29/CHECKSUMS
  projects/kubernetes/autoscaler/1-29/GIT_TAG
  projects/kubernetes/autoscaler/1-29/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-29/helm/patches/0001-Configure-image-digest.patch
  projects/kubernetes/autoscaler/1-29/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-29/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-29/helm/patches/0003-Add-regcred-secret.patch
  projects/kubernetes/autoscaler/1-29/helm/patches/0003-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-29/helm/patches/0004-Use-eks-anywhere-default-registry.patch
  projects/kubernetes/autoscaler/1-29/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
  projects/kubernetes/autoscaler/1-29/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-29/patches/0002-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/README.md
Labels: approved, lgtm, size/XXL

#2867 Add release notes to PR description
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#2870 Fix metallb patch
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/M
