Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-09, with the labels that each got.

#4795 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS, needs-ok-to-test, do-not-merge/invalid-owners-file

#4799 [release-0.22] Bump bottlrocket release version to latest
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/S

#4800 [release-0.22] Bump kubernetes-sigs/image-builder version to v0.1.44
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Make-configurable-Nutanix-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-non-EFI-builds-for-RHEL-9-OVA.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Update-Packer-VM-hardware-version-to-support-RHEL-9.patch
Labels: approved, lgtm, size/L

#4821 Fix ecr-credential-provider checksums for new builder-base
  projects/kubernetes/cloud-provider-aws/1-32/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-33/CHECKSUMS
Labels: approved, lgtm, size/XS

#4820 Preserve missing binary checksums
  build/lib/update_checksums.sh
Labels: approved, lgtm, size/S

#4837 Increase default disk size for raw image-builder builds
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
Labels: approved, lgtm, size/M

#4845 Fix kind build
  Common.mk
  projects/containerd/containerd/Makefile
Labels: lgtm, size/XS

#4851 Upgrade hook to 0.11.1 and linux-kernel to 6.6.y
  UPSTREAM_PROJECTS.yaml
  build/lib/fetch_binaries.sh
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/GOLANG_VERSION
  projects/tinkerbell/hook/HOOK_BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/HOOK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/LINUX_KERNEL_VERSION
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
  projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
  projects/tinkerbell/hook/patches/0003-use-tmpfs-for-var-lib-docker.patch
  projects/tinkerbell/hook/patches/0004-support-overriding-linuxkit-version-to-use-eksa-buil.patch
Labels: approved, lgtm, size/L

#4856 Add image_url for Nutanix Ubuntu 24.04
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/XS

#4862 increase disk size of Snow admin machine from 60G to 70G
  projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl
Labels: approved, lgtm, size/XS, needs-ok-to-test
