Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-08, with the labels that each got.

#4748 Patch smee deployment.yaml on upstream chart
  projects/tinkerbell/charts/helm/patches/0001-Load-stream-model-for-nginx-and-update-http2-command.patch
  projects/tinkerbell/charts/helm/patches/0002-Fix-smee-deployment-tolerations-rendering.patch
Labels: approved, lgtm, size/M

#4755 Revert "Bump image builder version to v0.1.45"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-non-EFI-builds-for-RHEL-9-OVA.patch
Labels: approved, lgtm, size/M

#4756 Revert "[release-0.23] Bump image builder version to v0.1.45"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-non-EFI-builds-for-RHEL-9-OVA.patch
Labels: approved, lgtm, size/M

#4764 Update ecr credential provider to fix proxy usecase
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/S

#4769 Resume helm updates
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#4758 Bump iPXE commit to latest upstream
  projects/tinkerbell/ipxedust/CHECKSUMS
  projects/tinkerbell/ipxedust/patches/0001-do-not-use-nix-shell-for-building.patch
  projects/tinkerbell/ipxedust/patches/0002-Enhance-iPXE-boot-script-interface-checks-retries-VL.patch
  projects/tinkerbell/ipxedust/patches/0003-Bump-Ipxe-commit-and-fix-gcc-build-issues.patch
Labels: approved, lgtm, size/L

#4773 image-builder: update checksum for Bottlerocket's new root.json
  projects/kubernetes-sigs/image-builder/bottlerocket-root-json-checksum
Labels: approved, lgtm, size/XS, ok-to-test

#4783 Upgrade metallb to v0.15.2
  UPSTREAM_PROJECTS.yaml
  projects/metallb/metallb/ATTRIBUTION.txt
  projects/metallb/metallb/CHECKSUMS
  projects/metallb/metallb/GIT_TAG
  projects/metallb/metallb/GOLANG_VERSION
  projects/metallb/metallb/README.md
  projects/metallb/metallb/helm/patches/0001-packages-patches.patch
Labels: approved, lgtm, size/XXL
