Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-03, with the labels that each got.

#4399 Update Bottlerocket host containers source extraction logic
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#4403 Remove patch which reverted additional source for EnvironmentFile in kubelet service
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Make-configurable-Nutanix-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Revert-Optionally-source-etc-default-kubelet-in-kube.patch
Labels: approved, lgtm, size/L

#4398 Update CAPAS to v0.2.0
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/README.md
Labels: approved, lgtm, size/XS, ok-to-test

#4404 Make Nutanix source image import names specific to image name
  projects/kubernetes-sigs/image-builder/build/build_image.sh
Labels: approved, lgtm, size/M

#4415 Update RHEL OS version validation from image builder
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
Labels: approved, lgtm, size/S

#4416 Add patch to fix RHEL 9 OVA builds
  projects/kubernetes-sigs/image-builder/build/validate_ova_kubelet.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Make-configurable-Nutanix-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Update-Packer-VM-hardware-version-to-support-RHEL-9.patch
Labels: approved, lgtm, size/L

#4422 Fix kubelet file check inside image
  projects/kubernetes-sigs/image-builder/build/validate_ova_kubelet.sh
Labels: approved, lgtm, size/XS

#4438 Revert "[release-0.22] Bump kubernetes-sigs/cluster-api to latest release"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-changes-to-support-kubeadm-v1beta4-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Disable-MachineSetPreflightChecks-Beta-feature.patch
Labels: approved, lgtm, size/L

#4442 Revert "Bump kubernetes-sigs/cluster-api to latest release"
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-changes-to-support-kubeadm-v1beta4-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Disable-MachineSetPreflightChecks-Beta-feature.patch
Labels: approved, lgtm, size/L

#4444 Pin CAPI project to version v1.9.4
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#4427 Add non-EFI builds for RHEL 9 OVA
  projects/aws/image-builder/ATTRIBUTION.txt
  projects/aws/image-builder/GIT_TAG
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/cmd/build.go
  projects/aws/image-builder/cmd/build_test.go
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/build/build_image.sh
  projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
  projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
  projects/kubernetes-sigs/image-builder/patches/0004-RHEL-support-and-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0006-adds-retries-and-timeout-to-packer-image-builder.patch
  projects/kubernetes-sigs/image-builder/patches/0007-Networking-improvements.patch
  projects/kubernetes-sigs/image-builder/patches/0008-Support-and-improvements-for-RHEL-9-EFI.patch
  projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
  projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0012-Make-configurable-Nutanix-image-size.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Update-Packer-VM-hardware-version-to-support-RHEL-9.patch
  projects/kubernetes-sigs/image-builder/patches/0014-Add-non-EFI-builds-for-RHEL-9-OVA.patch
Labels: approved, lgtm, size/L

#4460 bump capas version to v0.2.1
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/README.md
  projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml
  projects/aws/cluster-api-provider-aws-snow/manifests/metadata.yaml
Labels: approved, lgtm, size/XL, ok-to-test

#4463 Update package controller to v0.4.6
  build/lib/common.sh
  projects/aws/eks-anywhere-packages/ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/CHECKSUMS
  projects/aws/eks-anywhere-packages/CREDENTIALPROVIDER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt
  projects/aws/eks-anywhere-packages/GIT_TAG
  projects/aws/eks-anywhere-packages/GOLANG_VERSION
  projects/aws/eks-anywhere-packages/README.md
Labels: approved, lgtm, size/M

#4488 Bump Rufio to v0.6.5:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
Labels: approved, lgtm, size/S
