Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-06, with the labels that each got.

#4617 Cleanup OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#4625 Fix capd issue in the patch to skip provider check for etcd machines
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
Labels: approved, lgtm, size/M

#4627 Add InPlace rollout strategy in enum type for kcp and add missing cert bundles
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-changes-to-support-kubeadm-v1beta4-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Disable-MachineSetPreflightChecks-Beta-feature.patch
Labels: approved, lgtm, size/L

#4616 Add patch to increase QPS and auto-patch reboot on server-side
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/patches/0002-Increase-client-QPS-and-auto-patch-on-reboot-action.patch
Labels: approved, lgtm, size/M

#4632 Bump Rufio to latest commit on main
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
Labels: approved, lgtm, size/S

#4636 Add image-builder task status for 1.33
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS

#4637 Change latest release branch from 1.28 to 1.29 and remove 1.28 related builds
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/eks-anywhere-packages/Help.mk
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  projects/kubernetes/cloud-provider-aws/Makefile
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#4648 Add patch for cloudstack to remove kube rbac proxy
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/build/create_manifests.sh
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch
  projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0002-Remove-kube-rbac-proxy.patch
Labels: approved, lgtm, size/L

#4646 Add build status for 1.28 back
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS
