Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-05, with the labels that each got.

#4560 Added patch to fix CVE for prometheus image
  projects/prometheus/prometheus/ATTRIBUTION.txt
  projects/prometheus/prometheus/CHECKSUMS
  projects/prometheus/prometheus/patches/0001-fix-golang-CVE-2024-45337.patch
Labels: approved, lgtm, size/L

#4565 [release-0.21] Revert EKS-D 1.28 back to 1.28-43
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#4547 upgrade distribution/distribution to v3.0.0
  UPSTREAM_PROJECTS.yaml
  projects/distribution/distribution/ATTRIBUTION.txt
  projects/distribution/distribution/CHECKSUMS
  projects/distribution/distribution/GIT_TAG
  projects/distribution/distribution/GOLANG_VERSION
  projects/distribution/distribution/README.md
  projects/distribution/distribution/patches/0001-harbor-patch.patch
  projects/distribution/distribution/patches/0002-migrate-to-go-module.patch
Labels: approved, lgtm, size/XXL

#4574 Update checksums from build of distrbution upgrade
  projects/distribution/distribution/CHECKSUMS
  projects/distribution/distribution/Makefile
Labels: approved, lgtm, size/S

#4577 Bump capt to v0.6.5
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
Labels: approved, lgtm, size/M

#4580 Remove hardcoded version pin for capi project in upgrader
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#4576 Bump emissary golang version to 1.23
  UPSTREAM_PROJECTS.yaml
  projects/emissary-ingress/emissary/ATTRIBUTION.txt
  projects/emissary-ingress/emissary/CHECKSUMS
  projects/emissary-ingress/emissary/GOLANG_VERSION
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/patches/0001-Update-go.mod-and-go.sum.patch
Labels: approved, lgtm, size/M

#4578 Add 1-33 as a supported release branch
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes/autoscaler/1-33/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-33/CHECKSUMS
  projects/kubernetes/autoscaler/1-33/GIT_TAG
  projects/kubernetes/autoscaler/1-33/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-33/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-33/helm/patches/0001-Set-CAPI-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-33/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-33/helm/patches/0003-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-33/helm/schema.json
  projects/kubernetes/autoscaler/1-33/helm/sedfile.template
  projects/kubernetes/autoscaler/1-33/patches/0001-Remove-Cloud-Provider-Builders-Except-CAPI.patch
  projects/kubernetes/autoscaler/1-33/patches/0002-Remove-additional-GCE-Dependencies.patch
  projects/kubernetes/autoscaler/1-33/patches/0003-Update-go.mod-Dependencies.patch
  projects/kubernetes/cloud-provider-aws/1-32/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-33/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-33/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-33/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-33/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-33/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-33/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-33/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-33/GOLANG_VERSION
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#4579 change distribution/distribution to batch build
  Makefile
  projects/distribution/distribution/CHECKSUMS
  projects/distribution/distribution/Makefile
  projects/distribution/distribution/buildspecs/batch-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#4588 Upgrade go version for harbor-scanner-trivy to 1.24
  UPSTREAM_PROJECTS.yaml
  projects/distribution/distribution/ATTRIBUTION.txt
  projects/distribution/distribution/CHECKSUMS
  projects/distribution/distribution/GIT_TAG
  projects/distribution/distribution/GOLANG_VERSION
  projects/distribution/distribution/README.md
  projects/distribution/distribution/patches/0001-harbor-patch.patch
  projects/distribution/distribution/patches/0002-migrate-to-go-module.patch
  projects/distribution/distribution/patches/0003-update-go.mod-and-go.sum.patch
  projects/distribution/distribution/patches/0004-upgrade-go-version-to-1.24.2-and-fix-CVE.patch
  projects/goharbor/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/goharbor/harbor-scanner-trivy/CHECKSUMS
  projects/goharbor/harbor-scanner-trivy/GOLANG_VERSION
  projects/goharbor/harbor-scanner-trivy/patches/0001-upgrade-go-to-1.24.2.patch
Labels: approved, lgtm, size/XXL

#4589 Bump CAPI to v1.9.6
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CAPD_ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/GIT_TAG
  projects/kubernetes-sigs/cluster-api/README.md
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
Labels: approved, lgtm, size/M

#4590 Fix CVE for Harbor
  UPSTREAM_PROJECTS.yaml
  projects/goharbor/harbor/ATTRIBUTION.txt
  projects/goharbor/harbor/CHECKSUMS
  projects/goharbor/harbor/GOLANG_VERSION
  projects/goharbor/harbor/patches/0004-fix-CVE.patch
  projects/goharbor/harbor/patches/0005-modify-session-to-fit-newer-beego-version.patch
  projects/goharbor/harbor/patches/0006-upgrade-dompurify-to-v2.5.0.patch
Labels: approved, lgtm, size/L

#4591 fix: Updated autoscaler schema and patch for metrics-server
  projects/kubernetes-sigs/metrics-server/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes/autoscaler/1-30/helm/schema.json
  projects/kubernetes/autoscaler/1-31/helm/schema.json
  projects/kubernetes/autoscaler/1-32/helm/schema.json
  projects/kubernetes/autoscaler/1-33/helm/schema.json
Labels: approved, lgtm, size/L

#4592 skip packages on attribution generation for release branches
  Makefile
Labels: approved, lgtm, size/XS

#4596 Adds subbu vakati to owners
  OWNERS
Labels: approved, lgtm, size/XS

#4593 fix: remove pinned version of base and compiler image from emissary
  projects/emissary-ingress/emissary/Makefile
Labels: approved, lgtm, size/XS

#4566 Add BR release version for 1.33
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS
