Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-04, with the labels that each got.

#4385 Updated schema.json for emissary helm chart
  projects/emissary-ingress/emissary/helm/schema.json
Labels: approved, lgtm, size/XXL, sig/curated-packages

#4497 Revert "Bump helm/helm to latest release (#4238)"
  UPSTREAM_PROJECTS.yaml
  projects/helm/helm/ATTRIBUTION.txt
  projects/helm/helm/CHECKSUMS
  projects/helm/helm/GIT_TAG
  projects/helm/helm/GOLANG_VERSION
  projects/helm/helm/README.md
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#4491 Update OWNERS add Amelia
  OWNERS
Labels: approved, lgtm, size/XS, needs-ok-to-test

#4510 Allow vmx_version to be configurable in image-builder cli
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
Labels: approved, lgtm, size/S

#4511 [release-0.22] Allow vmx_version to be configurable in image-builder cli
  projects/aws/image-builder/CHECKSUMS
  projects/aws/image-builder/README.md
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
Labels: approved, lgtm, size/S

#4490 Updated build source for metrics server image to EKS AddOn ECR repo
  projects/kubernetes-sigs/metrics-server/1-26/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-27/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-28/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-28/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-28/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-29/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-29/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-29/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-30/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-30/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-30/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-31/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-31/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-31/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/1-32/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-32/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-32/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-32/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-32/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/EKS_ADDON_IMAGE_TAG
  projects/kubernetes-sigs/metrics-server/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/Makefile
  projects/kubernetes-sigs/metrics-server/README.md
  projects/kubernetes-sigs/metrics-server/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/helm/schema.json
  projects/kubernetes-sigs/metrics-server/helm/sedfile.template
Labels: approved, lgtm, size/XXL

#4527 Update ADOT from version v0.42.0 to v0.43.1
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/helm/schema.json
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/L

#4541 Add EKS add-on registry to policy.json and credHelpers list
  config/docker-ecr-config.json
  config/policy.json
Labels: approved, lgtm, size/XS

#4544 Update metrics server to latest EKS Addon Image version
  projects/kubernetes-sigs/metrics-server/EKS_ADDON_IMAGE_TAG
Labels: approved, lgtm, size/XS

#4543 Upgrade trivy to v0.61.1 and harbor-trivy-scanner to v0.33.0-rc.2
  UPSTREAM_PROJECTS.yaml
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/GIT_TAG
  projects/aquasecurity/trivy/GOLANG_VERSION
  projects/aquasecurity/trivy/README.md
  projects/aquasecurity/trivy/patches/0001-Replace-dependency-to-mitigate-license-issues.patch
  projects/aquasecurity/trivy/patches/0001-replace-dependecy-to-mitigate-license-issues.patch
  projects/goharbor/harbor-scanner-trivy/ATTRIBUTION.txt
  projects/goharbor/harbor-scanner-trivy/CHECKSUMS
  projects/goharbor/harbor-scanner-trivy/GIT_TAG
  projects/goharbor/harbor-scanner-trivy/README.md
Labels: approved, lgtm, size/L
