Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-07, with the labels that each got.

#4700 [release-0.22] Fix nutanix rhel 8 release 0.22
  projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
Labels: approved, lgtm, size/S

#4702 Revert "[release-0.22] Bump EKS Distro base image tag files to latest"
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
Labels: approved, lgtm, size/S

#4703 Revert "[release-0.23] Bump EKS Distro base image tag files to latest"
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
Labels: approved, lgtm, size/S

#4712 Add retry mechanism and increase timeout for network link wait
  projects/tinkerbell/ipxedust/CHECKSUMS
  projects/tinkerbell/ipxedust/Makefile
  projects/tinkerbell/ipxedust/ipxe-config/boot.ipxe
  projects/tinkerbell/ipxedust/ipxe-config/custom.h
Labels: approved, lgtm, size/M

#4725 Use archived apt repositories for buster as original ones are deprecated
  projects/goharbor/harbor/docker/linux/harbor-portal/Dockerfile
Labels: approved, lgtm, size/XS

#4728 Add robust multi-interface boot logic in iPXE script with retry mechanism
  projects/tinkerbell/ipxedust/CHECKSUMS
  projects/tinkerbell/ipxedust/Makefile
  projects/tinkerbell/ipxedust/ipxe-config/boot.ipxe
  projects/tinkerbell/ipxedust/ipxe-config/custom.h
  projects/tinkerbell/ipxedust/patches/0001-do-not-use-nix-shell-for-building.patch
  projects/tinkerbell/ipxedust/patches/0002-Enhance-iPXE-boot-script-interface-checks-retries-VL.patch
Labels: approved, lgtm, size/L

#4729 Revert "Bump EKS Distro base image tag files to latest"
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
Labels: approved, lgtm, size/S

#4733 Add robust multi-interface boot logic in iPXE script with retry mecha…
  projects/tinkerbell/ipxedust/CHECKSUMS
  projects/tinkerbell/ipxedust/patches/0001-do-not-use-nix-shell-for-building.patch
  projects/tinkerbell/ipxedust/patches/0002-Enhance-iPXE-boot-script-interface-checks-retries-VL.patch
Labels: approved, lgtm, size/L

#4730 Revert "[release-0.22] Bump EKS Distro base image tag files to latest"
  EKS_DISTRO_BASE_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_DOCKER_CLIENT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_GIT_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.11_AL2023_TAG_FILE
  EKS_DISTRO_MINIMAL_BASE_PYTHON_3.9_AL2023_TAG_FILE
Labels: approved, lgtm, size/S

#4674 Removes cilium manifest from bundle as it's unused
  projects/cilium/cilium/Makefile
  projects/cilium/cilium/build/create_manifests.sh
  projects/cilium/cilium/expected_artifacts
  projects/cilium/cilium/manifests/cilium-eksa.yaml
Labels: approved, lgtm, size/M

#4741 Bump image builder version to v0.1.45
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/GIT_TAG
  projects/kubernetes-sigs/image-builder/README.md
  projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
  projects/kubernetes-sigs/image-builder/patches/0013-Add-non-EFI-builds-for-RHEL-9-OVA.patch
Labels: approved, lgtm, size/M
