Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-01, with the labels that each got.

#4180 Add getopt binary to tink-relay-init image
  projects/tinkerbell/tink/docker/linux/tink-relay-init/Dockerfile
Labels: approved, lgtm, size/XS

#4185 Bump CAPT to latest version
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
Labels: approved, lgtm, size/S, ok-to-test

#4189 Allow specifying maximum semvers for projects
  tools/version-tracker/SKIPPED_PROJECTS
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: size/M

#4195 Add EKS Distro base tag files to version-tracker automation
  Makefile
  build/lib/generate_staging_buildspec.sh
  buildspecs/upgrade-eks-distro-build-tooling-buildspec.yml
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#4199 Add EKS Distro base tag files to version-tracker automation
  Makefile
  build/lib/generate_staging_buildspec.sh
  buildspecs/upgrade-eks-distro-build-tooling-buildspec.yml
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#4200 Add EKS Distro base tag files to version-tracker automation
  Makefile
  build/lib/generate_staging_buildspec.sh
  buildspecs/upgrade-eks-distro-build-tooling-buildspec.yml
  tools/version-tracker/buildspecs/upgrade.yml
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/commands/listprojects/listprojects.go
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/constants/constants.go
Labels: approved, lgtm, size/L

#4202 improves batch build generation
  Common.mk
  Makefile
  build/lib/generate_staging_buildspec.sh
  build/lib/setup.sh
  build/lib/validate_release_buildspecs.sh
  projects/aws/bottlerocket-bootstrap/Makefile
  projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
  projects/aws/eks-anywhere-build-tooling/Makefile
  projects/aws/upgrader/Makefile
  projects/aws/upgrader/buildspecs/batch-build.yml
  projects/containerd/containerd/Makefile
  projects/emissary-ingress/emissary/Makefile
  projects/emissary-ingress/emissary/buildspecs/batch-build.yml
  projects/goharbor/harbor/Makefile
  projects/goharbor/harbor/buildspecs/batch-build.yml
  projects/isc-projects/dhcp/Makefile
  projects/kubernetes-sigs/cri-tools/Makefile
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes-sigs/image-builder/buildspecs/br.yml
  projects/kubernetes-sigs/kind/Makefile
  projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
  projects/kubernetes-sigs/kind/buildspecs/node-images.yml
  projects/kubernetes/cloud-provider-vsphere/Makefile
  projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
  projects/opencontainers/runc/Makefile
  projects/replicatedhq/troubleshoot/Makefile
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/buildspecs/batch-build.yml
  projects/tinkerbell/hub/Makefile
  projects/tinkerbell/rufio/Makefile
  projects/tinkerbell/rufio/buildspecs/batch-build.yml
  projects/tinkerbell/tink/Makefile
  projects/tinkerbell/tink/buildspecs/batch-build.yml
  projects/torvalds/linux/Makefile
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#4215 Trim trailing newlines in file before string comparison
  tools/version-tracker/pkg/commands/upgrade/upgrade.go
  tools/version-tracker/pkg/util/file/file.go
Labels: size/S

#4225 Update attribution file and checksums for kube-vip/kube-vip
  projects/kube-vip/kube-vip/ATTRIBUTION.txt
  projects/kube-vip/kube-vip/CHECKSUMS
Labels: size/XS

#4194 Add eksd release for 1.32
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/image-builder/Makefile
  projects/kubernetes/autoscaler/1-32/ATTRIBUTION.txt
  projects/kubernetes/autoscaler/1-32/CHECKSUMS
  projects/kubernetes/autoscaler/1-32/GIT_TAG
  projects/kubernetes/autoscaler/1-32/GOLANG_VERSION
  projects/kubernetes/autoscaler/1-32/HELM_GIT_TAG
  projects/kubernetes/autoscaler/1-32/helm/patches/0001-Set-clusterapi-as-default-cloud-provider.patch
  projects/kubernetes/autoscaler/1-32/helm/patches/0002-Add-image-values.patch
  projects/kubernetes/autoscaler/1-32/helm/patches/0003-Authorize-MachinePool-Operations.patch
  projects/kubernetes/autoscaler/1-32/helm/schema.json
  projects/kubernetes/autoscaler/1-32/helm/sedfile.template
  projects/kubernetes/autoscaler/1-32/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
  projects/kubernetes/autoscaler/1-32/patches/0002-Remove-additional-GCE-Dependencies.patch
  projects/kubernetes/autoscaler/1-32/patches/0003-Update-go.mod-Dependencies.patch
  projects/kubernetes/autoscaler/README.md
  projects/kubernetes/cloud-provider-aws/1-32/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-aws/1-32/CHECKSUMS
  projects/kubernetes/cloud-provider-aws/1-32/GIT_TAG
  projects/kubernetes/cloud-provider-aws/1-32/GOLANG_VERSION
  projects/kubernetes/cloud-provider-vsphere/1-32/ATTRIBUTION.txt
  projects/kubernetes/cloud-provider-vsphere/1-32/CHECKSUMS
  projects/kubernetes/cloud-provider-vsphere/1-32/GIT_TAG
  projects/kubernetes/cloud-provider-vsphere/1-32/GOLANG_VERSION
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XXL

#4231 Migrate csaf-poc/csaf_distribution to gocsaf/csaf
  projects/aquasecurity/trivy/ATTRIBUTION.txt
  projects/aquasecurity/trivy/CHECKSUMS
  projects/aquasecurity/trivy/Makefile
  projects/aquasecurity/trivy/patches/0002-Update-CSAF-module-dependency-from-csaf-poc-to-gocsa.patch
Labels: approved, lgtm, size/M

#4244 Bump Smee and Rufio to latest versions
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/boots/ATTRIBUTION.txt
  projects/tinkerbell/boots/CHECKSUMS
  projects/tinkerbell/boots/GIT_TAG
  projects/tinkerbell/boots/README.md
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
Labels: approved, lgtm, size/L

#4243 Add BR release version for 1.32
  projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
Labels: approved, lgtm, size/XS

#4251 Fix endOfSupport date for 1-32
  EKSD_LATEST_RELEASES
Labels: approved, lgtm, size/XS

#4257 Update CAPAS to v0.1.30
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/README.md
Labels: approved, lgtm, size/XS, ok-to-test

#4256 Add hook as iso to our builds
  UPSTREAM_PROJECTS.yaml
  projects/linuxkit/linuxkit/CHECKSUMS
  projects/linuxkit/linuxkit/Makefile
  projects/linuxkit/linuxkit/patches/0001-source-mkimage-iso-efi-initrd-image-from-env.patch
  projects/linuxkit/linuxkit/patches/0002-add-moby-config-to-dockerfiles-for-packages-used-by-.patch
  projects/linuxkit/linuxkit/patches/0003-init-dockerfile-to-use-eks-a-built-bins.patch
  projects/linuxkit/linuxkit/patches/0004-pass-cpu-host-when-running-qemu-to-support-testing-a.patch
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/GIT_TAG
  projects/tinkerbell/hook/HOOK_BOOTKIT_ATTRIBUTION.txt
  projects/tinkerbell/hook/HOOK_DOCKER_ATTRIBUTION.txt
  projects/tinkerbell/hook/LINUX_KERNEL_VERSION
  projects/tinkerbell/hook/Makefile
  projects/tinkerbell/hook/README.md
  projects/tinkerbell/hook/expected_artifacts
  projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
Labels: approved, lgtm, size/L

#4274 Bump kind from v0.25.0 to v0.26.0
  UPSTREAM_PROJECTS.yaml
  projects/kubernetes-sigs/kind/ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/CHECKSUMS
  projects/kubernetes-sigs/kind/GIT_TAG
  projects/kubernetes-sigs/kind/GOLANG_VERSION
  projects/kubernetes-sigs/kind/KINDNETD_ATTRIBUTION.txt
  projects/kubernetes-sigs/kind/README.md
  projects/kubernetes-sigs/kind/build/node-image-build-args.sh
  projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
  projects/kubernetes-sigs/kind/patches/0002-skip-ctr-pulling-required-images-since-the-build-rem.patch
  projects/kubernetes-sigs/kind/patches/0003-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/kind/patches/0004-Disable-cgroupns-private-to-fix-cluster-creation-on-.patch
  projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch
  projects/kubernetes-sigs/kind/patches/0006-Use-docker_tag-file-to-fetch-Kubernetes-source-versi.patch
Labels: approved, lgtm, size/M

#4283 Update hook kernel with missing modules
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
Labels: approved, lgtm, size/M
