Repository aws/eks-anywhere-build-tooling, pull requests merged in 2025-02, with the labels that each got.

#4284 update corefiles patch for 1.11.4
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Update-coredns-corefile-migration-to-support-1.11.4.patch
Labels: approved, lgtm, size/M

#4285 Update corefile-migration patch to support CoreDNS v1.11.4
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Update-coredns-corefile-migration-to-support-1.11.4.patch
Labels: approved, lgtm, size/M

#4286 Update corefile-migration patch to support CoreDNS v1.11.4
  projects/kubernetes-sigs/cluster-api/ATTRIBUTION.txt
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Update-coredns-corefile-migration-to-support-1.11.4.patch
Labels: approved, lgtm, size/M

#4282 Update hook kernel with missing modules
  projects/tinkerbell/hook/CHECKSUMS
  projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
Labels: approved, lgtm, size/M

#4280 Bump cilium to v1.15.13-eksa.1
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
  projects/cilium/cilium/manifests/cilium-eksa.yaml
Labels: approved, lgtm, size/S

#4268 Bump CAPT and Tink to latest version
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
  projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
  projects/tinkerbell/cluster-api-provider-tinkerbell/GIT_TAG
  projects/tinkerbell/cluster-api-provider-tinkerbell/README.md
  projects/tinkerbell/tink/CHECKSUMS
  projects/tinkerbell/tink/GIT_TAG
  projects/tinkerbell/tink/README.md
  projects/tinkerbell/tink/patches/0001-Patch-tink-controller-to-update-reboot-action-to-suc.patch
Labels: approved, lgtm, size/M

#4293 Update Rufio version:
  UPSTREAM_PROJECTS.yaml
  projects/tinkerbell/rufio/ATTRIBUTION.txt
  projects/tinkerbell/rufio/CHECKSUMS
  projects/tinkerbell/rufio/GIT_TAG
  projects/tinkerbell/rufio/README.md
Labels: approved, lgtm, size/S, area/dependencies

#4296 Revert "Update CAPAS to v0.1.30 (#4291)"
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/README.md
Labels: approved, lgtm, size/XS

#4297 Update CAPAS to v0.1.30 (#4291)
  projects/aws/cluster-api-provider-aws-snow/GIT_TAG
  projects/aws/cluster-api-provider-aws-snow/README.md
Labels: approved, lgtm, size/XS

#4306 Workaround for replica issue on CAPI 1.9.4
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-changes-to-support-kubeadm-v1beta4-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Requeue-reconcilation-if-ControlPlaneEndpoint-is-not.patch
Labels: approved, lgtm, size/L

#4305 Add Nutanix optional parameter to define image size
  projects/aws/image-builder/builder/builder.go
  projects/aws/image-builder/builder/constants.go
  projects/aws/image-builder/builder/types.go
  projects/aws/image-builder/cmd/build.go
  projects/kubernetes-sigs/image-builder/patches/0014-Make-configurable-Nutanix-image-size.patch
Labels: approved, lgtm, size/M, ok-to-test

#4288 Bump nutanix-cloud-native/cluster-api-provider-nutanix to latest release
  UPSTREAM_PROJECTS.yaml
  projects/aws/image-builder/cmd/build_test.go
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/GIT_TAG
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/README.md
  projects/nutanix-cloud-native/cluster-api-provider-nutanix/patches/0001-Update-ntnx-api-golang-clients-Go-mod-to-fix-licensi.patch
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
Labels: approved, lgtm, size/L, area/dependencies

#4314 Add rajeshvenkata to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#4330 Update cilium 1.14 to fix issue with hostport functionality
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#4335 Improve display command for version tracker
  tools/version-tracker/cmd/display.go
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/types/types.go
  tools/version-tracker/pkg/util/version/version.go
Labels: approved, lgtm, size/L

#4337 Support envoyproxy/envoy, isc-projects/dhcp projects in display command
  tools/version-tracker/go.mod
  tools/version-tracker/go.sum
  tools/version-tracker/pkg/commands/display/display.go
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
  tools/version-tracker/pkg/github/github.go
  tools/version-tracker/pkg/util/semver/semver.go
Labels: approved, lgtm, size/L

#4334 Remove the patch of retrying reconcilation when kcp is not found
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-changes-to-support-kubeadm-v1beta4-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Requeue-reconcilation-if-ControlPlaneEndpoint-is-not.patch
Labels: approved, lgtm, size/L

#4341 Update cilium 1.15 to fix issue with hostport functionality
  UPSTREAM_PROJECTS.yaml
  projects/cilium/cilium/GIT_TAG
  projects/cilium/cilium/README.md
  projects/cilium/cilium/images/cilium-chart/IMAGE_DIGEST
  projects/cilium/cilium/images/cilium/IMAGE_DIGEST
  projects/cilium/cilium/images/operator-generic/IMAGE_DIGEST
Labels: approved, lgtm, size/S

#4342 Add release branch 1-32 for metrics server
  projects/kubernetes-sigs/metrics-server/1-32/HELM_GIT_TAG
  projects/kubernetes-sigs/metrics-server/1-32/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
  projects/kubernetes-sigs/metrics-server/1-32/helm/patches/0002-Remove-Addon-Resizer.patch
  projects/kubernetes-sigs/metrics-server/1-32/helm/schema.json
  projects/kubernetes-sigs/metrics-server/1-32/helm/sedfile.template
  projects/kubernetes-sigs/metrics-server/README.md
Labels: approved, lgtm, size/XXL

#4348 Set 1-28 as latest release branch
  EKSD_LATEST_RELEASES
  UPSTREAM_PROJECTS.yaml
  projects/aws/eks-anywhere-packages/Help.mk
  projects/aws/eks-anywhere-packages/Makefile
  projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
  projects/kubernetes/cloud-provider-aws/Makefile
  release/SUPPORTED_RELEASE_BRANCHES
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/M

#4363 Fix ECR Public latest version retrieval
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
Labels: size/S

#4365 Fix ECR Public latest version retrieval
  tools/version-tracker/pkg/constants/constants.go
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
Labels: size/S

#4371 Skip CoreDNS phase for K8s 1.32+ in kubeadm
  projects/aws/upgrader/CHECKSUMS
  projects/aws/upgrader/docker/linux/Dockerfile
  projects/aws/upgrader/upgrade/kubeadm.go
  projects/aws/upgrader/upgrade/kubeadm_test.go
Labels: approved, lgtm, size/L

#4372 Use LINUX_CONTAINER as build platform for fluxcd/source-controller
  projects/fluxcd/source-controller/Makefile
  release/checksums-build.yml
  release/staging-build.yml
  tools/version-tracker/buildspecs/upgrade.yml
Labels: approved, lgtm, size/XS

#4358 Add image-builder task status for 1.32
  projects/kubernetes-sigs/image-builder/README.md
Labels: approved, lgtm, size/XS, ok-to-test

#4384 Upgrade ADOT to v0.42.0
  UPSTREAM_PROJECTS.yaml
  projects/aws-observability/aws-otel-collector/GIT_TAG
  projects/aws-observability/aws-otel-collector/HELM_GIT_TAG
  projects/aws-observability/aws-otel-collector/README.md
  projects/aws-observability/aws-otel-collector/helm/patches/0001-Update-image-repo.patch
  projects/aws-observability/aws-otel-collector/helm/patches/0002-Add-namespace-to-charts.patch
  projects/aws-observability/aws-otel-collector/helm/patches/0003-Update-default-values.patch
  projects/aws-observability/aws-otel-collector/helm/schema.json
  projects/aws-observability/aws-otel-collector/images/collector/IMAGE_DIGEST
Labels: approved, lgtm, size/L

#4386 Add patch to disable MachineSetPreflightChecks in CAPI
  projects/kubernetes-sigs/cluster-api/CHECKSUMS
  projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
  projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
  projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
  projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
  projects/kubernetes-sigs/cluster-api/patches/0008-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
  projects/kubernetes-sigs/cluster-api/patches/0009-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0010-Add-node-labels-support-for-bottlerocket.patch
  projects/kubernetes-sigs/cluster-api/patches/0011-Support-worker-node-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0012-support-bottle-rocket-control-plane-taints.patch
  projects/kubernetes-sigs/cluster-api/patches/0013-Support-configuring-bottlerocket-control-container-u.patch
  projects/kubernetes-sigs/cluster-api/patches/0014-Change-format-for-storing-etcd-machine-address.patch
  projects/kubernetes-sigs/cluster-api/patches/0015-Parse-provider-id-from-kubelet-extra-args.patch
  projects/kubernetes-sigs/cluster-api/patches/0016-Add-feature-to-specifiy-additional-host-containers-i.patch
  projects/kubernetes-sigs/cluster-api/patches/0017-Add-bottlerocket-custom-bootstrap-containers-config-.patch
  projects/kubernetes-sigs/cluster-api/patches/0018-Support-configuring-bottlerocket-admin-container-ima.patch
  projects/kubernetes-sigs/cluster-api/patches/0019-Make-bottlerocket-admin-control-custom-bootstrap-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0020-Mark-etcd-machine-status-to-running-after-etcd-contr.patch
  projects/kubernetes-sigs/cluster-api/patches/0021-add-support-for-registry-credentials.patch
  projects/kubernetes-sigs/cluster-api/patches/0022-Add-support-for-configuring-NTP-servers-on-bottleroc.patch
  projects/kubernetes-sigs/cluster-api/patches/0023-set-hostname-for-BR-nodes.patch
  projects/kubernetes-sigs/cluster-api/patches/0024-Add-bottlerocket-k8s-settings-support.patch
  projects/kubernetes-sigs/cluster-api/patches/0025-add-br-kernel.sysctl-settings.patch
  projects/kubernetes-sigs/cluster-api/patches/0026-add-boot-kernel-settings-for-BR.patch
  projects/kubernetes-sigs/cluster-api/patches/0027-Patch-haproxy-maxconn-value-to-avoid-ulimit-issue.patch
  projects/kubernetes-sigs/cluster-api/patches/0028-Add-support-for-custom-cert-bundles-in-BR-21.patch
  projects/kubernetes-sigs/cluster-api/patches/0029-CAPI-Move-Cluster-Filter.patch
  projects/kubernetes-sigs/cluster-api/patches/0030-Move-objects-with-force-move-label-and-no-cluster-te.patch
  projects/kubernetes-sigs/cluster-api/patches/0031-allow-registry-mirror-configurations-to-be-mutable-f.patch
  projects/kubernetes-sigs/cluster-api/patches/0032-Add-support-for-external-etcd-machines-in-Kind-mappe.patch
  projects/kubernetes-sigs/cluster-api/patches/0033-disable-cgroupns-private-to-fix-AL2.patch
  projects/kubernetes-sigs/cluster-api/patches/0034-Add-support-for-in-place-upgrade-in-KCP.patch
  projects/kubernetes-sigs/cluster-api/patches/0035-Add-support-for-in-place-upgrades-in-MachineDeployme.patch
  projects/kubernetes-sigs/cluster-api/patches/0036-Adding-support-for-multiple-registry-mirrors-in-bott.patch
  projects/kubernetes-sigs/cluster-api/patches/0037-Fix-MD-controller-reconcilation-with-in-place.patch
  projects/kubernetes-sigs/cluster-api/patches/0038-Add-Bottlerocket-kubernetes-settings-for-kubelet-con.patch
  projects/kubernetes-sigs/cluster-api/patches/0039-Add-changes-to-support-kubeadm-v1beta4-types.patch
  projects/kubernetes-sigs/cluster-api/patches/0040-Disable-MachineSetPreflightChecks-Beta-feature.patch
Labels: approved, lgtm, size/L

#4388 Fix latest semver detection for release branches
  tools/version-tracker/pkg/util/version/version.go
Labels: size/S

#4390 More fixes to latest semver detection for release branches
  tools/version-tracker/pkg/ecrpublic/ecrpublic.go
  tools/version-tracker/pkg/github/github.go
Labels: size/S
